### ISSUE TITLE
Marksman's Honours has not been updated to new version

### ISSUE THREAD

**Issue by dode74** [BSData/wh40k#5684] opened 2019-09-21 23:18 UTC
**File/Catalogue:Space Marines 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes

**Description:** Marksmans' Honours has changed in the new codex and now reads:
"Add 1 to the Damage characteristic of ranged weapons this
Warlord is equipped with. This does not apply to Grenades
or Relics."

Source: Codex: Space Marines page 178

**Comment by Mad-Spy** [comment] 2019-09-23 07:44
Duplicate of #5632

**Closed by Mad-Spy** 2019-09-23 07:44 UTC
Labels: Area: text/rule/profile, Type: bug, ✔ Res: duplicate, 💾 Cat: Imperium - Space Marines

**Comment by dode74** [comment] 2019-09-23 08:21
This is not a duplicate of #5632 - that one references a typo in the old version, this references the changed version in SM19.
