### ISSUE TITLE
Imperium - Grey Knights - CA2018 FW Units Updates

### ISSUE THREAD

**Issue by flaminsouljah** [BSData/wh40k#3964] opened 2018-12-08 01:05 UTC
Updated Unit Costs

Apothecary
Brother-Captain
Brotherhood Ancient
Brotherhood Champion
Chaplain
Dreadnought
Grand Master
Grand Master In Nemesis Dreadknight
Interceptor Squad
Land Raider
Land Raider Crusader
Land Raider Redeemer
Librarian
Paladin Ancient
Paladin Squad
Purifier Squad
Servitors
Techmarine
Terminator Squad
Venerable Dreadnought
Brother Captain-Stern
Castellan Crowe
Grand Master Voldus
Lord Kaldor Draigo

Updated Wargear Costs

Combi-Flamer
Combi-Melta
Combi-Plasma
Flamer
Heavy Flamer
Heavy Incinerator
Heavy Plasma Cannon
Heavy Psycannon
Icarus Stormcannon
Incinerator
Incinerator (Terminator)
Missile Launcher
Multi-Melta
Plasma Cannon
Plasma Cutter
Psilencer (Terminator)
Psycannon
Psycannon (Terminator)
Twin Heavy Plasma Cannon
Twin Lascannon
Twin Multi-Melta
Typhoon Missile Launcher

**Comment by Mad-Spy** [comment] 2018-12-08 01:12
Duplicate of #3923

**Closed by Mad-Spy** 2018-12-08 01:12 UTC
Labels: Area: costs, ✔ Res: duplicate, 💾 Cat: Imperium - Grey Knights, 📋 Task: update (new publication)
