### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4133] opened 2018-12-16 02:24 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** The price for Chaos Spawn is still showing as 33 in the files, but was dropped to 25 in Chapter Approved 2018

**Comment by Kohato** [comment] 2018-12-16 04:44
Duplicate of #4078

**Closed by Kohato** 2018-12-16 04:44 UTC
