### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2696] opened 2018-03-21 03:57 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** Yes

**Description:** The option for Stimulant Injectors is no longer showing up.  I understand that it is not available in the codex, but as per GW Designers Commentary and their released flowchart, it is still a legal option to take.  Please correct this.

**Comment by amis92** [comment] 2018-03-21 07:02
Indeed, as explained in, and duplicate of #2634

**Closed** 2018-03-21 07:47 UTC
Labels: Bug - choice, Resolution - duplicate, T'au
