### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2890] opened 2018-04-18 14:46 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** Helbrute is now able to replace both Power Fists with Power Scourges according to the FAQs.
Chosens - Each Chosen can take a weapon from the melee weapons list, but only chainsword/boltgun option is available for Chosens not wielding a special weapon.

**Comment by GenWilhelm** [comment] 2018-04-18 17:42
Duplicate of #2872.

**Closed by GenWilhelm** 2018-04-18 17:42 UTC
