### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7037] opened 2020-04-22 11:04 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.18

**Platform:** Android

**Dropbox:** No

**Description:** "Tank Aces" as a feature is broken. When one model is selected as the Warlord in an Astra Militarum detachment, and then given a Main Battle Tank Tank Ace ability, the app shows an error saying that there are 1 too many selections from Main Battle Tank Tank Ace abilities (Maximum 0). This error goes away when the strategem called Tank Aces is added to the list. This should not be like this, as a model may select a Tank Ace ability instead of a Warlord Trait, and the strategem is only required if the player desires to have a second Tank Ace in their army.

**Comment by alphalas** [comment] 2020-04-23 22:19
duplicate of #6945

**Closed by alphalas** 2020-04-23 22:19 UTC
