### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5370] opened 2019-08-05 17:46 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.01

**Platform:** Android

**Dropbox:** No

**Description:** Trying to load a space marine list other than a super heavy detachment causes BS to stop before it has loaded. I have reinstalled the app, cleared all my old lists, updated the data files, etc and still can't load anything to do with marines. I have 1gb of ram on my phone and plenty of storage free. PC version freezes for a few seconds then works, phone version crashes. Problem started in the last few weeks, not sure of exact version but latest I can load

**Comment by Mad-Spy** [comment] 2019-08-05 22:28
Duplicate of #5324

**Closed by Mad-Spy** 2019-08-05 22:28 UTC
