### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2710] opened 2018-03-23 14:39 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** No option for a warlord in the spacemarine list so can't select warlord traits.

**Comment by Mad-Spy** [comment] 2018-03-25 18:27
Duplicate of #1838

**Closed by Mad-Spy** 2018-03-25 18:27 UTC
Labels: Imperium - Space Marines, Request - Edit UX enhancement, Resolution - duplicate
