### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6007] opened 2019-11-22 08:52 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.08

**Platform:** Mac

**Dropbox:** No

**Description:** I use a Salamanders Successor army. My warlord is a chaplain venerable dreadnought, and since it can't take a relic i put it on my captain in cataphractii armour. Battlescribe says I have "1 too many selections from chapter relics (maximum 0), though, to the best of my ability, I believe that I am allowed to take 1 chapter relic for my captain without spending 1CP for an additional relic.

**Comment by WindstormSCR** [comment] 2019-11-22 09:14
Duplicate of #5998

**Closed by WindstormSCR** 2019-11-22 09:14 UTC
