### ISSUE TITLE
[Anon] Bug report: Aeldari - Craftworlds.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3177] opened 2018-05-28 14:27 UTC
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.01.19

**Platform:** Android

**Dropbox:** No

**Description:** Issue started with new harlequin update. There is no illic nightspear option for Craftworld.

**Comment by amis92** [comment] 2018-05-28 14:29
Duplicate of #3173

**Closed by amis92** 2018-05-28 14:29 UTC
Labels: Area: selections, Type: bug, ✔ Res: duplicate, 💾 Cat: Aeldari - Craftworlds
