### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6019] opened 2019-11-24 13:26 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.15

**Platform:** Android

**Dropbox:** No

**Description:** If you add more relic by the stratagem on the Ultramarines, you still have the error for too many relic in your army

**Comment by WindstormSCR** [comment] 2019-11-24 14:37
Duplicate of #5998

**Closed by WindstormSCR** 2019-11-24 14:37 UTC
