### ISSUE TITLE
Imperium - Astra Militarum: Lord Commissar should not have Voice of Command

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7262] opened 2020-06-22 18:58 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.00

**Platform:** Android

**Dropbox:** No

**Description:** It says that Lord commissar has the voice of command but  they dont.

**Comment by alphalas** [comment] 2020-06-23 14:31
duplicate of #7251 ((and like 6 other reports...

**Closed by alphalas** 2020-06-23 14:31 UTC
Labels: Area: text/rule/profile, Type: bug, 💾 Cat: Imperium - Astra Militarum

**Comment by alphalas** [comment] 2020-06-23 21:10
https://github.com/BattleScribe/Release/issues/218
