### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Custodes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6857] opened 2020-03-08 11:07 UTC
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.18

**Platform:** Android

**Dropbox:** No

**Description:** The cost for a caladius grav-tank and aquilon custodians are off. Battlescribe does not seem to have updated the costs from the chapter approved 2019 FAQ.

**Comment by Mad-Spy** [comment] 2020-03-09 08:33
Duplicate of #6767. Fixed in next release

**Closed by Mad-Spy** 2020-03-09 08:33 UTC
Labels: Area: costs, Type: bug, ✔ Res: deprecated, 💾 Cat: Imperium  - Adeptus Custodes
