### ISSUE TITLE
[Anon] Bug report: Imperium - Blood Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4187] opened 2018-12-17 10:21 UTC
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 1.21.28

**Platform:** Android

**Dropbox:** No

**Description:** Blood angels storm shields on characters are currently 15 points, should be 10 as per CA 2018

**Comment by GenWilhelm** [comment] 2018-12-17 11:18
Duplicate of #4184

**Closed by GenWilhelm** 2018-12-17 11:18 UTC
