### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2680] opened 2018-03-19 16:41 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 1.09.99

**Platform:** Windows

**Dropbox:** No

**Description:** The MV4 Shield Drone is listed at 11 points per model but in the codex it is actually 10 points per model.  The MV52 Shield Drone is 11.

**Comment by Kohato** [comment] 2018-03-19 17:20
Duplicate of #2666

**Closed by Kohato** 2018-03-19 17:20 UTC
Labels: Bug - cost, Resolution - duplicate, T'au
