### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4745] opened 2019-03-18 08:58 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.23

**Platform:** Android

**Dropbox:** No

**Description:** Hi
Latest Shadowspear updates do not appear under SPACE WOLVES roster list choices , altjough they appear ok for regular Space Marines

**Comment by Mad-Spy** [comment] 2019-03-18 08:58
Duplicate of #4742

**Closed by Mad-Spy** 2019-03-18 08:58 UTC
