### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4554] opened 2019-02-02 09:29 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** The "view" option  dosen't work. It don't show the army list.

**Comment by Thairne** [comment] 2019-02-02 11:09
#4541

**Comment by Thairne** [comment] 2019-02-02 11:10
Duplicate of #4541

**Closed by Thairne** 2019-02-02 11:09 UTC
Labels: Area: BattleScribe app, ✔ Res: duplicate
