### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6434] opened 2019-12-19 09:40 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** Aeldari - Craftworlds. 
Dire Avengers Squad - Exarch Weapon choices
Shimmershield & Power Glaive option should cost 9 (5 for Shimmershield and 4 for Power Glaive) points per CA2019. 
Currently listed incorrectly at 14.

Thank you.

**Comment by Mad-Spy** [comment] 2019-12-19 10:23
Duplicate of #6329

**Closed by Mad-Spy** 2019-12-19 10:23 UTC

**Comment by NickTheSecond** [comment] 2019-12-19 10:47
@Mad-Spy 
Hi, sorry to bother, but I am afraid in v89 it is still listed under old value.

**Comment by Mad-Spy** [comment] 2019-12-19 11:38
Apologies, it's fixed in the unreleased v90. It'll be in the next dataset release.
