### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3179] opened 2018-05-28 18:29 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.19

**Platform:** Android

**Dropbox:** No

**Description:** In Aeldari - Craftworlds, you seem to be missing 3 hqs: Illic Nightspear, Eldrad Ulthran, and Prince Yriel.

**Comment by Kohato** [comment] 2018-05-28 21:46
Duplicate of #3173

**Closed by Kohato** 2018-05-28 21:46 UTC
Labels: Area: selections, Type: bug, ✔ Res: duplicate, 💾 Cat: Aeldari - Craftworlds
