### ISSUE TITLE
[Anon] Bug report: Chaos - Death Guard.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7145] opened 2020-05-19 20:28 UTC
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.03.13

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I can’t put missiles and another range weapon on the hellbrute 
With out getting flagged saying you can’t have the missile launcher hidden

**Comment by Mad-Spy** [comment] 2020-05-19 20:36
It's a bug caused by a change to Battlescribe. It'll be fixed in the next release.

Duplicate of #7104

**Closed by Mad-Spy** 2020-05-19 20:36 UTC
