### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4981] opened 2019-04-24 14:59 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I just can see one catalogue (chaos renegade knights) everything eles is missing.

**Comment by fuckingenglish** [comment] 2019-04-24 16:01
Duplicate of #4959. just relax its being looked into

**Closed** 2019-04-24 21:54 UTC
