### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5095] opened 2019-05-05 13:57 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.02.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Terrax assault drill is missing from the dedicated Transport for space wolves

**Comment by WindstormSCR** [comment] 2019-05-05 17:14
duplicate of #5094

**Closed by WindstormSCR** 2019-05-05 17:14 UTC
