### ISSUE TITLE
[Anon] Bug report: Aeldari - Craftworlds.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6804] opened 2020-02-26 16:40 UTC
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.12

**Platform:** Windows

**Dropbox:** No

**Description:** Autarch with Wings (Legends) has a power sword by default but removing it invalidates the list. Suggestion: could an "includes legends" tag be added to the army configuration section so that, if checked, only the relevant wargear options appear in the right panel instead of having two entries for the same model?

**Comment by Mad-Spy** [comment] 2020-02-26 16:49
Duplicate of #6645

**Closed by Mad-Spy** 2020-02-26 16:49 UTC
