### ISSUE TITLE
Imperium: Dark Angels incorrect points

### ISSUE THREAD

**Issue by rtho782** [BSData/wh40k#6146] opened 2019-12-10 12:11 UTC
**File/Catalogue:** Dark Angels v119//40k 8th v113

**Description:** Tactical Marines should be 12 pts rather than 13 pts as per MFM2019

**Comment by Mad-Spy** [comment] 2019-12-10 12:21
Duplicate of #6133

**Closed by Mad-Spy** 2019-12-10 12:21 UTC
