### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3768] opened 2018-10-25 23:44 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** The Riptide HBC is mistakenly changed to Swift strike Burst Cannon.

**Comment by amis92** [comment] 2018-10-26 08:13
Duplicate of #3766

**Closed by amis92** 2018-10-26 08:13 UTC
Labels: Area: selections, Area: text/rule/profile, Type: bug, ✔ Res: duplicate, 💾 Cat: T'au Empire
