### ISSUE TITLE
[Anon] Bug report: Chaos - Death Guard.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1491] opened 2017-09-19 16:12 UTC
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** Plague marines - bubotic axe is 5 points (terminators bubotic axe is ok), not 6 as in CSM codex

**Comment by GenWilhelm** [comment] 2017-09-19 16:28
Duplicate of #1490.

**Closed by GenWilhelm** 2017-09-19 16:28 UTC
