### ISSUE TITLE
Imperium - Deathwatch: Librarian in Terminator Armor cost

### ISSUE THREAD

**Issue by propheadprops** [BSData/wh40k#3068] opened 2018-05-14 18:08 UTC
File: Imperium - Deathwatch.cat

BattleScribe version: 2.01.17.272

Platform: Android

Dropbox: No

Description: The Librarian in Terminator Armor has a base points cost of 120 in the new Deathwatch Codex but has a value of 142 in the current datafile.

**Comment by WindstormSCR** [comment] 2018-05-14 18:09
This has already been fixed for next release

Duplicate of #3063

**Closed by WindstormSCR** 2018-05-14 18:09 UTC
