### ISSUE TITLE
T'au Empire: Unable to take Cyclic Ion Blaster on XV86 Coldstar

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4146] opened 2018-12-16 09:14 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Cyclic Ion blaster unavailable to Coldstar  Commander

**Comment by amis92** [comment] 2018-12-16 12:53
It's specifically forbidden. Duplicate of #3411

**Closed by amis92** 2018-12-16 12:53 UTC
Labels: Area: selections, Type: bug, ✔ Res: duplicate, ✔ Res: invalid, 💾 Cat: T'au Empire
