### ISSUE TITLE
[Anon] Bug report: Imperium - Deathwatch.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7016] opened 2020-04-16 09:50 UTC
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.12

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When you equip Deathwatch terminators with cyclone missile launcher and storm bolter BS is showing error. According to the codex it is a 100% legal combination. Points are ok

**Comment by Mad-Spy** [comment] 2020-04-17 14:11
Duplicate of #6900

**Closed by Mad-Spy** 2020-04-17 14:11 UTC
