### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4284] opened 2018-12-20 16:50 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Astra Militarum: Battalion Detachment: Elite: Rein and Raus forces a warlord trait selection validation error.

**Comment by Kohato** [comment] 2018-12-20 16:57
Duplicate of #4226

**Closed by Kohato** 2018-12-20 16:57 UTC
