### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5620] opened 2019-09-06 10:00 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** There are no more options for custom characters in open play games. Why are they gone.

**Comment by Mad-Spy** [comment] 2019-09-06 10:02
Duplicate of #5619

**Closed by Mad-Spy** 2019-09-06 10:02 UTC
