### ISSUE TITLE
[Anon] Bug report: Chaos - Daemons.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4062] opened 2018-12-15 12:53 UTC
**File:** Chaos - Daemons.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Lord of change with baleful sword is showing 280 when in Chapter Approve, there is an entry for the Lord of change w/ baleful sword to be 275.

**Comment by GenWilhelm** [comment] 2018-12-15 14:02
Duplicate of #4053

**Closed by GenWilhelm** 2018-12-15 14:02 UTC
