### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4988] opened 2019-04-24 21:15 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Tau Stealth Suit Fusion blaster limitations are not properly implemented. A single fusion blaster in a unit small than 6 throws an error. Should allow 1 fusion at 3 models and 2 fusion at 6 models.

**Comment by WindstormSCR** [comment] 2019-04-24 21:55
Duplicate of #4958

**Closed by WindstormSCR** 2019-04-24 21:55 UTC
