### ISSUE TITLE
Imperium - Deathwatch: Watch Captain wargear selections

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5166] opened 2019-05-25 00:43 UTC
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.02.03

**Platform:** Android

**Dropbox:** No

**Description:** When selecting equipment for a Deathwatch Watch Captain the currently(since latest FAQ) legal loadout of Relic blade+ stormshield throws the following error:

Watch Captain has 1 too many selections from Chainsword Replacement (maximum 0)

This bug occurs because the correct way of getting that loadout, according to the codex/FAQ is to swap your chainsword for a chainsword and swapping that second chainsword for a relic blade. Selecting said second chainsword in addition to the relic blade and stormshield changes the error to:

Watch Captain has 1 too many selections from Weapon Options(maximum 2)

**Comment by WindstormSCR** [comment] 2019-05-25 12:31
duplicate of #5139

**Closed by WindstormSCR** 2019-05-25 12:31 UTC
Labels: Area: validation, Type: bug, 💾 Cat: Imperium - Deathwatch
