### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5349] opened 2019-07-28 23:46 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** in the astra militarium codex, there is a glitch with the tank commander where every cannon option for the leman russ is selected and this creates errors where it says there is too many options selected but there’s no way to deselect them

**Comment by DrTobogganMD** [comment] 2019-07-29 00:00
Duplicate of #5338

**Closed by DrTobogganMD** 2019-07-29 00:00 UTC
Labels: Area: selections, Type: bug, ✔ Res: duplicate, 💾 Cat: Imperium - Astra Militarum
