### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4577] opened 2019-02-06 20:36 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Change the models per unit value for Skyclaws to read ‘5-15’.

**Comment by Mad-Spy** [comment] 2019-02-07 08:20
Duplicate of #4569

**Closed by Mad-Spy** 2019-02-07 08:20 UTC
