### ISSUE TITLE
[Anon] Bug report: Orks.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5515] opened 2019-08-24 08:19 UTC
**File:** Orks.catz

**BattleScribe version:** 2.03.00

**Platform:** Android

**Dropbox:** No

**Description:** The Warboss has disappeared from the "HQ" options. Now in the "Uncategorised" section, which is odd.

**Comment by Mad-Spy** [comment] 2019-08-24 18:21
Duplicate of #5496

**Closed by Mad-Spy** 2019-08-24 18:21 UTC
