### ISSUE TITLE
[Anon] Bug report: Imperium - Dark Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5303] opened 2019-07-14 15:01 UTC
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** Yes

**Description:** new repulsor executioner is not il dark angel unit list.

**Comment by Mad-Spy** [comment] 2019-07-15 07:09
Duplicate of #5275

**Closed by Mad-Spy** 2019-07-15 07:09 UTC
