### ISSUE TITLE
Necrons Immortals

### ISSUE THREAD

**Issue by fejjn** [BSData/wh40k#2814] opened 2018-04-09 15:37 UTC
**File/Catalogue:** 
Necrons v22
**BattleScribe version:** 2.01.
v2.01.10.101
**Platform:** Windows/iOS/Android/Mac/Linux
windows
**Dropbox:** Yes/No
no
**Description:** Detailed issue description.
When i add Multiple Immortals units, and start adding models in them - all of the immortal-units gets models and not just that one unit. just as they are linked somehow(?)

**Comment by Kohato** [comment] 2018-04-09 15:42
Duplicate of #2807 

This is a known bug with Jon's newest desktop release - the only workaround is to save your list and re-enter it.  Or use a mobile editor.

**Closed by Kohato** 2018-04-09 15:42 UTC
