### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7009] opened 2020-04-13 23:57 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.14

**Platform:** Windows

**Dropbox:** No

**Description:** Raganar point cost are still 100pts and should be 120pts, thanks

**Comment by Mad-Spy** [comment] 2020-04-14 08:18
Duplicate of #7007

**Closed by Mad-Spy** 2020-04-14 08:18 UTC
