### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5964] opened 2019-11-13 05:09 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Salamanders Space marine captain with jump pack can take drake-smiter as a relic thunder hammer. Doesn’t show up as an option.

**Comment by Mad-Spy** [comment] 2019-11-13 06:30
Duplicate of #5961

**Closed by Mad-Spy** 2019-11-13 06:30 UTC
