### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1684] opened 2017-10-28 23:13 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 1.00.61

**Platform:** Android

**Dropbox:** No

**Description:** The renegade and heretics list is out of date. Astra militrum units like leman Russ tanks which were updated with the astra militrum codex, have not been updated in the renegade database.

**Comment by ilaunchbury** [comment] 2017-10-28 23:20
Duplicate of #1679

**Closed by ilaunchbury** 2017-10-28 23:20 UTC
Labels: Resolution - duplicate
