### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3312] opened 2018-06-27 08:00 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.14

**Platform:** Windows

**Dropbox:** No

**Description:** Hey guys, made a list tonight, and noticed I'm allowed to contain more than one commander in a detachment. Tau codex only allows one commander per detachment, thanks :)

**Comment by amis92** [comment] 2018-06-27 10:48
Please read resolution of #3285. Closing as duplicate of #3285.

**Closed by amis92** 2018-06-27 10:48 UTC
Labels: Area: validation, Type: bug, ✔ Res: duplicate, 💾 Cat: T'au Empire
