### ISSUE TITLE
[Anon] Bug report: Imperium - Questor Imperialis.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4501] opened 2019-01-24 03:34 UTC
**File:** Imperium - Questor Imperialis.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** In regards to the updated system of command points. In no force org  status request for option of three CP set to null. for the 6+ cp given when  Titanic keyword is used . does not check for keywords in current build.

**Comment by WindstormSCR** [comment] 2019-01-24 07:37
duplicate of #4500

**Closed by WindstormSCR** 2019-01-24 07:37 UTC
