### ISSUE TITLE
[Anon] Bug report: Orks.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5526] opened 2019-08-25 09:12 UTC
**File:** Orks.catz

**BattleScribe version:** 2.03.00

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Ork Hq - regular “warboss” is missing

Xxxxxxxxxxxxxx

**Comment by Guy-Markman** [comment] 2019-08-25 09:16
Duplicate of #5496

**Closed** 2019-08-26 15:46 UTC
