### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4743] opened 2019-03-18 04:44 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** Yes

**Description:** wolf guard battle leader attack profile characteristic Is written as 4 attack but as per codex it should be 3 only.

**Comment by Mad-Spy** [comment] 2019-03-18 07:59
Duplicate of #4699

**Closed by Mad-Spy** 2019-03-18 07:59 UTC
Labels: Area: text/rule/profile, Type: bug, ✔ Res: duplicate, 💾 Cat: Imperium - Space Wolves
