### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5708] opened 2019-09-29 10:41 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.03

**Platform:** Android

**Dropbox:** Yes

**Description:** Iron hands Dreadnought. please add box for march of the ancient stratagems (make it a character. add another box for warlord trait stratagems. and warlord boxes. thank you.

**Comment by WindstormSCR** [comment] 2019-09-29 21:31
Duplicate of #5702

**Closed by WindstormSCR** 2019-09-29 21:31 UTC
