### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5506] opened 2019-08-23 21:48 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.09

**Platform:** Android

**Dropbox:** No

**Description:** The ratlings entry is missing from the elites section of the Astra Militarum roster.

**Comment by Mad-Spy** [comment] 2019-08-24 18:12
Duplicate of #5496

**Closed by Mad-Spy** 2019-08-24 18:12 UTC
