### ISSUE TITLE
T'au: Equipment error in Coldstar Battlesuit

### ISSUE THREAD

**Issue by undesconocido** [BSData/wh40k#7038] opened 2020-04-22 18:01 UTC
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** iOS

**Dropbox:** Yes

**Description:** The error prompted is: "Commander in XV86 battlesuit must have 1 more selections of Missile pod (minimun 1)

http://wahapedia.ru/wh40k8ed/factions/tau-empire/Commander-in-XV86-Coldstar-Battlesuit

```
A Commander in XV86 Coldstar Battlesuit is a single model equipped with a high-output burst cannon and missile pod. It may be accompanied by up to 2 Tactical Drones (Power Rating +1).
```
```
WARGEAR OPTIONS 
 • This model may replace its high-output burst cannon and missile pod with two items from the Ranged Weapons and/or Support Systems lists. 
• This model may take two additional items from the Ranged Weapons and/or Support Systems lists.

```

You can replace the missile pod for any other weapon or system but the app prompts you with the mandatory missile.

**Comment by DrTobogganMD** [comment] 2020-04-22 18:06
You have to replace both. You can't replace just one.

Duplicate of #2936

**Closed by DrTobogganMD** 2020-04-22 18:06 UTC
