### ISSUE TITLE
[Anon] Bug report: Imperium - Deathwatch.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5223] opened 2019-06-18 09:58 UTC
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 1.30.06

**Platform:** Android

**Dropbox:** No

**Description:** -On the Warhammer 40.000 v1.3.06 
-Imperium-Deathwatch
-Troops-Veterans-> Heavy Thunder Hammer is allowed. In the error's not.
I checked the updated list, and it is allowed. Please update it.

Tank you

**Comment by amis92** [comment] 2019-06-18 11:20
Duplicate of #5195

**Closed by amis92** 2019-06-18 11:20 UTC
Labels: Area: validation, Type: bug, 💾 Cat: Imperium - Deathwatch
