### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4850] opened 2019-04-02 23:01 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.17

**Platform:** Windows

**Dropbox:** Yes

**Description:** After the 4/2/19 release, Chaos Biker champions can no longer select a second combi-bolter as their Champion Equipment option. Rhinos seem to have the same problem.

**Comment by Mad-Spy** [comment] 2019-04-02 23:31
Duplicate of #4849

**Closed by Mad-Spy** 2019-04-02 23:31 UTC
Labels: ✔ Res: duplicate
