### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Custodes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4507] opened 2019-01-25 16:31 UTC
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** https://whc-cdn.games-workshop.com/wp-content/uploads/2019/01/Forgeworld_Custodes_Datasheets-1.pdf
to day was a update to bata rules for the adeptus custodes from forge world models

**Comment by GenWilhelm** [comment] 2019-01-25 16:34
Duplicate of #4505.

**Closed by GenWilhelm** 2019-01-25 16:34 UTC
