### ISSUE TITLE
[Anon] Bug report: Imperium - Grey Knights.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4109] opened 2018-12-15 21:29 UTC
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 1.20.00

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Grey Knight Terminator w/ psycannon is currently set to incorrect value of 52 points, should be set to 50 point total.

**Comment by tekton** [comment] 2018-12-15 22:56
Duplicate of 4091

**Closed by tekton** 2018-12-15 22:56 UTC
Labels: ✔ Res: duplicate, 💤 Pending: check required, 💾 Cat: Imperium - Grey Knights
