### ISSUE TITLE
T'au Empire: Iridium battlesuit validation error on XV8s

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7077] opened 2020-04-29 17:10 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.03.16

**Platform:** Windows

**Dropbox:** No

**Description:** XV8 Crisis Battlesuits do not allow the correct number of Iridium battlesuits. In the codex, it outlines that for every three models in the unit, one can take an iridium battlesuit. Currently, with a unit of 9, battlescribe only allows one regular suit to take an iridium suit, with a second being forced to be taken on the Shas'vre. This is incorrect as up to three iridium should be able to be taken on any of the suits in the unit.

**Comment by amis92** [comment] 2020-04-30 10:13
Same as #7068 - I'll just blindly guess it's a new BattleScribe's bug. Needs verification though, and I don't have time now.

**Comment by DrTobogganMD** [comment] 2020-04-30 19:05
Duplicate indeed. I verified the original issue #

Duplicate of #7068

**Closed by DrTobogganMD** 2020-04-30 19:05 UTC
Labels: Area: BattleScribe app, Area: validation, Type: bug, ✔ Res: duplicate, 💾 Cat: T'au Empire
