### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4542] opened 2019-01-31 21:00 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** On all 40k rosters, when I click view, the page is white with no data. everything is enabled that should be. I have changed no settings. I am not in low ram mode.

**Comment by WindstormSCR** [comment] 2019-01-31 21:51
Duplicate of #4541

**Closed by WindstormSCR** 2019-01-31 21:51 UTC
