### ISSUE TITLE
[Anon] Bug report: Aeldari - Ynnari.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2848] opened 2018-04-14 04:03 UTC
**File:** Aeldari - Ynnari.catz

**BattleScribe version:** 2.01.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** O cant create an ynnari detachment because it give me only the option for hq and nothing more

**Comment by amis92** [comment] 2018-04-14 07:36
Duplicate of #2801

**Closed by amis92** 2018-04-14 07:36 UTC
Labels: Aeldari - Ynnari, Bug - choice, Resolution - duplicate
