### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4093] opened 2018-12-15 17:55 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Chaos havocs Auto cannon points are incorrect, chaos landraider twin lascannon points are incorrect .

**Comment by GenWilhelm** [comment] 2018-12-15 20:51
Duplicate of #4078

**Closed by GenWilhelm** 2018-12-15 20:51 UTC
