### ISSUE TITLE
[Anon] Bug report: Imperium - Blood Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4160] opened 2018-12-16 17:38 UTC
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** All changes in Chapter Approved 2018 for Blood Angels are NOT in effect :) - Tried refreshing data, Tried deleting and reloading the data and so on. I have the newest version of Battlescribe.

Astorath is 143 (should be 105)
Corbulo is 94 (should be 83)
Captain Tycho is 95 (should be 85)
Dante is 215 (should be 175)
Lemartes is 129 (should be 100)
Mephiston is 145 (should be 160)
Sanguinor is 170 (should be 150)
That is only the HQ edits. There are as you know a ton of weapon edits and non- HQ changes as well but for some reason, it will not show your changes after the chapter approved 2018 update to your 40k lists regarding Blood Angels.

**Comment by GenWilhelm** [comment] 2018-12-16 18:08
Duplicate of #4077

**Closed by GenWilhelm** 2018-12-16 18:08 UTC
