### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1620] opened 2017-10-12 14:52 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** **Accidentally sent this issue to Blood Angels instead of Astra Militarum. Sorry, you can delete that issue.** Astra Militarum, Heavy Weapons Team in individual units cost the same amount of points of 1 model but count as 2 models. Stuff like Infantry Heavy weapons Teams cost 4 points Base, but I believe they count as 2 models, and cost 8 points together. Same for Veteran Heavy Weapons Teams, and Command Squad Heavy Weapons Teams.

**Comment by ilaunchbury** [comment] 2017-10-12 15:17
Duplicate of #1619

**Closed by ilaunchbury** 2017-10-12 15:17 UTC
