### ISSUE TITLE
[Anon] Bug report: Tyranids.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1757] opened 2017-11-14 22:47 UTC
**File:** Tyranids.catz

**BattleScribe version:** 2.01.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Heavy Venom Cannon in the Harpy should be 25 points per gun. This is the same for the Stranglethorn Cannon 25 points per gun

**Comment by GenWilhelm** [comment] 2017-11-15 01:13
Duplicate of #1755.

**Closed by GenWilhelm** 2017-11-15 01:13 UTC
