### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5598] opened 2019-09-01 17:44 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.01

**Platform:** Android

**Dropbox:** No

**Description:** For the standard Primaris Marine Captain, I am unable to equip a power sword without receiving a roster error.

**Comment by Mad-Spy** [comment] 2019-09-01 22:10
Duplicate of #5597

**Closed by Mad-Spy** 2019-09-01 22:10 UTC
