### ISSUE TITLE
All Deathwatch Intercessor [Auto|Stalker] Bolt Rifles are incorrect

### ISSUE THREAD

**Issue by ambis** [BSData/wh40k#6313] opened 2019-12-11 22:03 UTC
**File/Catalogue:** Deathwatch v80 40k 1.4.1

**BattleScribe version:** 2.03.06

**Platform:** iOS

**Dropbox:** No

**Description:** 

Deathwatch Intercessor Bolt Rifles are listed as 1pts where as they should be 0 points.

Also auto bolt rifles are 2 pts, sould be 1 and stalker bolt rifle should also be 0, not 1pts.

**Comment by Mad-Spy** [comment] 2019-12-11 22:06
Duplicate of #6140

**Closed by Mad-Spy** 2019-12-11 22:06 UTC

**Comment by BlackKnightSrc** [comment] 2019-12-11 22:22
#6140 does not fully update the Primaris costs. Intercessor Bolt Rifles are still 1pt when they should be 0.

**Comment by ambis** [comment] 2019-12-13 10:27
@Mad-Spy Can you please re-open, bolt-rifles are still 1pts (should be 0), even with the latest update which correctly lowered stalker to 0 and auto bolt rifle to 1pts.

**Comment by BlackKnightSrc** [comment] 2019-12-13 12:16
There is a set pts to 1 rule in the markup which is overriding the correct update points, it needs to be removed from the Intercessors and Intercessor Sergeant's load out.
