### ISSUE TITLE
[Anon] Bug report: Fallen.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7056] opened 2020-04-25 07:43 UTC
**File:** Fallen.catz

**BattleScribe version:** 2.03.21

**Platform:** Android

**Dropbox:** No

**Description:** Fallen sorcerer with jump pack point cost are wrong. Please fix

**Comment by Mad-Spy** [comment] 2020-04-25 09:52
Duplicate of #7051

**Closed by Mad-Spy** 2020-04-25 09:52 UTC
