### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4102] opened 2018-12-15 20:46 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** Yes

**Description:** Chaos Spawn point values have not been adjusted to CA values.

**Comment by GenWilhelm** [comment] 2018-12-15 20:52
Duplicate of #4078

**Closed by GenWilhelm** 2018-12-15 20:52 UTC
