### ISSUE TITLE
Imperium - Dark Angels: Unable to select Chaplain

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5216] opened 2019-06-15 13:56 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 1.03.06

**Platform:** Android

**Dropbox:** No

**Description:** Dark Angel's cannot select a chaplain as an HQ option.

**Comment by Thairne** [comment] 2019-06-17 07:27
Duplicate of #5202

**Closed by Thairne** 2019-06-17 07:27 UTC
Labels: Area: selections, Type: bug, ✔ Res: duplicate, 💾 Cat: Imperium - Dark Angels
