### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4887] opened 2019-04-05 17:21 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.21

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** If “Field Commander” has been purchased an error is flagged when selecting the specialist warlord trait if another character in the same detachment has been named warlord and given a codex warlord trait.

**Comment by Mad-Spy** [comment] 2019-04-07 18:46
Duplicate of #4876

**Closed by Mad-Spy** 2019-04-07 18:46 UTC
