### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5437] opened 2019-08-21 07:38 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** No

**Description:** Lightning claws as a pair should be 10pts, currently 12. I know you've probably had loads to do with this dex drop, thank you for all your hard work and making everyones gaming experience so much better. - Sorry I posted this by accident in the main stream.

**Comment by WindstormSCR** [comment] 2019-08-21 14:13
Duplicate of #5436

**Closed by WindstormSCR** 2019-08-21 14:13 UTC
