### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4423] opened 2019-01-09 15:07 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Request to merge and flatten captain of the primaries . The current data sheet is the anniversary card. And the same reason why English is hard. The primaries Are the same in regards to in equipment as  The troop  wording. May I have it done.

**Comment by Mad-Spy** [comment] 2019-01-09 15:40
Duplicate of #4421

**Closed by Mad-Spy** 2019-01-09 15:40 UTC
Labels: Type: request, ✔ Res: duplicate, 💾 Cat: Imperium - Space Marines
