### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4999] opened 2019-04-25 01:02 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** The only catalogue available to build lists is Chaos Knights

**Comment by fuckingenglish** [comment] 2019-04-25 01:15
the issue has been fixed pleas update the app

**Comment by WindstormSCR** [comment] 2019-04-25 14:07
duplicate of #4959

**Closed by WindstormSCR** 2019-04-25 14:07 UTC
