### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5837] opened 2019-10-25 20:44 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 1.03.25

**Platform:** Windows

**Dropbox:** No

**Description:** Raven Guard and Raven Guard Successor chapters need a stratagem for "Master of the Trifold Path" which allows you to add a second warlord trait to your warlord for 1 cp.

**Comment by Mad-Spy** [comment] 2019-10-26 20:18
Duplicate of #5712

**Closed by Mad-Spy** 2019-10-26 20:18 UTC
