### ISSUE TITLE
[Anon] Bug report: Aeldari - Harlequins.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6041] opened 2019-11-30 10:36 UTC
**File:** Aeldari - Harlequins.catz

**BattleScribe version:** 1.03.30

**Platform:** Android

**Dropbox:** Yes

**Description:** Curtain fall is not visible as an option as a relic for dreaming shadow. It says hidden selection. It is also unfindable under others as well

**Comment by Mad-Spy** [comment] 2019-12-02 08:30
Duplicate of #5986

**Closed by Mad-Spy** 2019-12-02 08:30 UTC
