### ISSUE TITLE
Imperium - Deathwatch: Add Repulsor Executioner

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5289] opened 2019-07-10 16:15 UTC
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.02.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Deathwatch does not have access to the Repulsor executioner, even though it’s been added to the other space marine lists.

**Comment by Mad-Spy** [comment] 2019-07-11 08:11
It's currently only been added to Space Marines, because we haven't seen full rules to see whether it's actually available to anyone else.

**Comment by Thairne** [comment] 2019-07-12 13:59
essentially duplicate of #5275

**Closed** 2019-07-16 11:45 UTC
Labels: Area: selections, Type: request, 💤 Pending: check required, 💾 Cat: Imperium - Deathwatch
