### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5298] opened 2019-07-13 14:56 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.02.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** The Transport rules for the Repulsor Executioner are wrong. In the files they say it may transport 10 models but the actual rules are that it may only transport 6 models.

**Comment by Mad-Spy** [comment] 2019-07-13 19:10
Duplicate of #5276

**Closed by Mad-Spy** 2019-07-13 19:10 UTC
