### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Custodes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5583] opened 2019-08-30 14:50 UTC
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Units from forge world are no longer in beta. There’s  is a point increase and a  adjustment  To units type. Alongside this is a new release .

**Comment by GenWilhelm** [comment] 2019-08-30 17:23
Duplicate of #5582

**Closed by GenWilhelm** 2019-08-30 17:23 UTC
