### ISSUE TITLE
Deathwatch relic stratagem doesn't work

### ISSUE THREAD

**Issue by GuillermoDiazGarcia** [BSData/wh40k#6324] opened 2019-12-12 01:40 UTC
**File/Catalogue:** wh40k

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:**

I updated the file (deleting first) to version 1.4.1.
Deathwatch can't use extra relics even if you use the armory of the watch fortress stratagem, which should allow you to take those extra relics (it says limit: 0)

**Comment by Mad-Spy** [comment] 2019-12-12 16:04
I don't think we can count on getting this fixed in BS any time soon, so it's probably worth just updating the constraints.

**Comment by Mad-Spy** [comment] 2019-12-13 12:43
Duplicate of #6040

**Closed by Mad-Spy** 2019-12-13 12:43 UTC
Labels: Area: BattleScribe app, 💾 Cat: Imperium - Deathwatch
