### ISSUE TITLE
[Anon] Bug report: Aeldari - Ynnari.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2849] opened 2018-04-14 06:28 UTC
**File:** Aeldari - Ynnari.catz

**BattleScribe version:** 2.01.10

**Platform:** Windows

**Dropbox:** No

**Description:** I can no longer add any units to a Ynnari detachment other than Yvraine, The Visarch, and The Yncarne. There are no other units available in the Ynnari tree.

**Comment by amis92** [comment] 2018-04-14 07:35
Duplicate of #2801

**Closed** 2018-04-14 07:35 UTC
Labels: Aeldari - Ynnari, Bug - choice, Resolution - duplicate
