### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Mechanicus.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4553] opened 2019-02-02 02:58 UTC
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Myself and a friend downloaded the latest patch (updating files) since then the view mode for 40k warhammer, Necromunda gang war, Age of Sigmar and Kill team 40k yields nothing.

The window opens but is blank.

We have reinstalled updated and deleted/renewed Battlescribe as a download. Nothing we have tried including following the guidelines on the website and bug reporting disclaimer fixes this.

**Comment by WindstormSCR** [comment] 2019-02-02 03:37
Duplicate of #4541

**Closed by WindstormSCR** 2019-02-02 03:37 UTC
