### ISSUE TITLE
T'au Empire: Plasma Accelerator profile incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2685] opened 2018-03-20 01:19 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** Plasma Accelerator Rifle has the wrong stat-line. It should be range: 30", type: Rapid Fire 1, S: 7, AP: -3, D:2

**Comment by amis92** [comment] 2018-03-20 08:52
Duplicate of already resolved #2669

**Closed by amis92** 2018-03-20 08:52 UTC
Labels: Bug - text/rule/profile, Resolution - deprecated, T'au
