### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1054] opened 2017-07-31 19:16 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** Aggressor Squad: Point cost is calculated the wrong way, most likely because points for auto boltstorm gauntlets are added twice instead of just once.
Redemptor Dreadnought: Point cost is calculated the wrong way, most likely due to not all weapon options being present and Heavy Onslaught Gatling Cannon, Icarus Rocket Pod and Fragstorm Grenade Launchers are wrongly provided as free.
Repulsor: Point cost is off, most likely due to several weapon options wrongly provided as free.

**Comment by acebaur** [comment] 2017-07-31 22:36
I could fix this in a about 5 mins, but I can't figure out how to upload files to here

**Comment by alphalas** [comment] 2017-07-31 22:37
@acebaur before you try to fix things, join us on gitter.

**Comment by acebaur** [comment] 2017-07-31 22:38
Where would that be?

**Comment by alphalas** [comment] 2017-07-31 22:40
https://gitter.im/BSData/wh40k

It's linked on the first page of the repo, also.

**Comment by flakpanda** [comment] 2017-07-31 23:53
Duplicate of many

**Closed by flakpanda** 2017-07-31 23:53 UTC
