### ISSUE TITLE
[Anon] Bug report: Imperium - FW Adeptus Astartes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#873] opened 2017-07-19 15:05 UTC
**File:** Imperium - FW Adeptus Astartes.catz

**BattleScribe version:** 2.01.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Hello. Love your work.
The file doesn't seem to include a whirlwind scorpius entry however.
That is all :)
Thank you.

**Comment by ilaunchbury** [comment] 2017-07-19 20:10
The Scorpius will be in the next release.

**Comment by ilaunchbury** [comment] 2017-07-19 20:10
Duplicate of #868.

**Closed by ilaunchbury** 2017-07-19 20:10 UTC
Labels: Resolution - duplicate
