### ISSUE TITLE
[Anon] Bug report: Chaos - Daemons.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5156] opened 2019-05-21 23:01 UTC
**File:** Chaos - Daemons.catz

**BattleScribe version:** 2.02.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The blissbringer unit will modify the points value but not the power level for the unit where it is included.

**Comment by Mad-Spy** [comment] 2019-05-22 03:52
Duplicate of #5151. Fixed in next release.

**Closed by Mad-Spy** 2019-05-22 03:52 UTC
Labels: Area: costs, Type: bug, ✔ Res: duplicate, 💾 Cat: Chaos - Daemons
