### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5513] opened 2019-08-24 02:37 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.00

**Platform:** Android

**Dropbox:** No

**Description:** The wyvern unit entry and the ratlings unit entry are missing from the astra militarum roster. They need to be re-added to data

**Comment by Mad-Spy** [comment] 2019-08-24 18:21
Duplicate of #5496

**Closed by Mad-Spy** 2019-08-24 18:21 UTC
