### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2698] opened 2018-03-21 18:38 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** Attempting to submit a file update for the T'au empire v20. After selection the file and inputting the description and hitting submit I get an error that says "There was an error submitting your file. Please try again later." The updated file was incremented and saved. And I've tried multiple times to submit the update.

Update was as follows.
"Un-hid support system option "stimulant injector [index]" in the shared support system list to reflect wargear available in the index that is not in the codex per the GW designers commentary."

Please respond to Greenwolff77@msn.com with an answer if possible.

**Comment by Kohato** [comment] 2018-03-21 19:51
Duplicate of #2696

**Closed by Kohato** 2018-03-21 19:51 UTC
Labels: Bug - choice, Resolution - duplicate, T'au
