### ISSUE TITLE
[Anon] Bug report: Imperium - Inquisition.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6064] opened 2019-12-02 17:28 UTC
**File:** Imperium - Inquisition.catz

**BattleScribe version:** 2.03.06

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When selecting inquisitor greyfax in a reinforcements detachment, you cannot select her Ordo Hereticus specific psychic power for her. Only the 6 defaults are shown. This may also effect other inquisitors’ and may not be exclusive to reinforcements detachment. If a quarry selection is needed for this option, none are selectable in a reinforcement detachment and would need a solution.

**Comment by Mad-Spy** [comment] 2019-12-03 09:24
Duplicate of #5991

**Closed by Mad-Spy** 2019-12-03 09:24 UTC
Labels: Area: selections, Type: bug, ✔ Res: duplicate, 💾 Cat: Imperium - Inquisition
