### ISSUE TITLE
Redemptor

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1035] opened 2017-07-30 13:11 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Redemption Dreadnought war gear point totals area wrong. Aggressor Squad war gear total is 108 when it should be 54.

**Comment by alphalas** [comment] 2017-07-30 17:39
Dupe of #1020 #1036

**Closed by alphalas** 2017-07-30 17:39 UTC
