### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5638] opened 2019-09-11 00:15 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.03

**Platform:** Android

**Dropbox:** No

**Description:** The stormhawk interceptor has a change in its armor.  The infernum halo-launcher it doesn't let the controller reroll 1s on saves anymore.

**Comment by Mad-Spy** [comment] 2019-09-11 08:44
Duplicate of #5633

**Closed by Mad-Spy** 2019-09-11 08:44 UTC
Labels: Area: text/rule/profile, Type: bug, ✔ Res: duplicate, 💾 Cat: Imperium - Space Marines
