### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7011] opened 2020-04-14 08:51 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.12

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** If I am not mistaken Ragnar Blackmane is 120points not 100points.

Ps: Keep up the great work.
Regards
Andrew

**Comment by Mad-Spy** [comment] 2020-04-14 09:11
Duplicate of #7007

**Closed by Mad-Spy** 2020-04-14 09:11 UTC
