### ISSUE TITLE
Death Guard - messed up

### ISSUE THREAD

**Issue by miklus** [BSData/wh40k#906] opened 2017-07-21 16:46 UTC
**File/Catalogue:** 
Death Guard
**BattleScribe version:** 2.01.
2.01.03
**Platform:** Windows/iOS/Android/Mac/Linux
Windows
**Dropbox:** Yes/No
No
**Description:** Detailed issue description.
Death Guard has so many errors/issues, that it is not event worth noting everything separately.
From Plague Champion taking combi weapon, which returns error (which I already reported and it was fixed and fine), Chaos Lord when he takes 2 plasma pistols (which I already reported  and it was fixed and fine), to the fact that I must for most units with grenades/smite always check its option or it returns error (why? just why?).

**Comment by ilaunchbury** [comment] 2017-07-21 20:37
Please can you give a little more information on exactly what the problems you are seeing are?

From the limited information you've given, I think there's a problem with the following:

- Plague Champion taking a combi weapon. I'm not sure what the issue is here, it appears to be working correctly but maybe we're interpreting the rules differently?
- Chaos Lord validation error when taking 2 plasma pistols. Yes, it looks like there's a problem with that. I'll get it fixed.
- It does also appear that I've missed some constraints for grenades and Smite on a couple of units. Again, I'll get it fixed.

If there are any other issues you have found, please let me know the details and I'll do my best to get them sorted out for you.

**Comment by ilaunchbury** [comment] 2017-07-21 20:45
Chaos Lord is now fixed, and the only unit I could find a problem with Blight Grenades and Smite was the Malignant Plaguecaster, which is also fixed.

If you let me know the details of the problem with the Plague Champion, I'll look at that as well.

**Comment by miklus** [comment] 2017-07-21 21:33
Plague Champion - he can take 2 items from the Champion equipment or he can take one weapon from combi list (so if he replaces on of his weapons he can take only one  wepon, but if he replaces both he can take combi weapon instead from what i understand from index). Currently, when I choose combi-melta is says, that I have to have 1 more selection for him.
Typhus also has problem with blight grenade and smite (Plaguecaster also has checkbox for krak grenades, which should be hidden along with blight).
My suggestion - culstis champion should not have "None" weapon option, as it is redundant (I suggest to simply set autogun as default)
Also in plague champion it says "Fallen Champion Equipment" when choosing equipment, should be "Plague Champion Equipment".
Noxious Blightbringer also has redundant option for Blight Grenades

This is all errors I'm getting with my current rooster.

**Comment by Wyvern350** [comment] 2017-07-21 21:40
That's a misinterpretation of the rules.  He can take two items from the Champion Equipment list, or he can take one item from the Champion Equipment list and one item from the Combi-Weapon list.  The indexes word it poorly, I had the same issue when I built my Iron Warriors.  The intent is to keep a champion from dual-wielding combi-weapons.

**Comment by miklus** [comment] 2017-07-21 23:54
Wyvern350 is it confirmed anywhere in official sources? Because for me it looks like you may take 2 from one list OR (Alternatively) 1 from second list, which makes more sense as combi-weapons are basically 2 in 1, so no matter if you choose option 1 or option 2 you still get 2 weapons max

**Comment by alphalas** [comment] 2017-07-22 00:04
Yeah it's the same as SM, BA, or the Guard Commissar. You can take 2 from one list, OR may take one from the other.

**Comment by Wyvern350** [comment] 2017-07-22 00:12
Just that that's the way it was explained to me when I reported the error when 8th first launched.  It works that way currently for both CSM aspiring champions and Space Marine Sergeants.  If you select a combi-weapon, Battlescribe still wants you to pick a weapon for the other hand, like a power sword.

**Comment by ilaunchbury** [comment] 2017-07-22 07:49
@alphalas, that's not how Marine Sergeants work at present in the catalogue. I can select a melee/pistol 
 weapon and a combi-weapon with no validation error.

I think that is the correct way it should work. The model should always end up with two weapons in the end, but only one of them can be a "rifle"-type weapon. That is how it is currently implemented.

**Comment by miklus** [comment] 2017-07-22 10:41
Yeah, but when you take combi weapon you basically end up with 2 weapons. And if you want to shoot both you have to take -1, which makes sense, as none of the combi weapons are available in the list to take 2 of, and the weapons that you can take 2 of are less powerfull (but you are not getting -1)

**Comment by ilaunchbury** [comment] 2017-07-22 12:52
In the absence of any other reports of this as an issue and given that it matches the implementation in other catalogues, I'm going to leave the champion as is for now.

I'll get the other issues sorted as soon as I can.

**Closed** 2017-07-22 15:11 UTC
