### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Custodes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3407] opened 2018-08-08 13:08 UTC
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Intercessor Sergeant  cant equip with auto bolt rifle , bolt rifle or stalker bolt rifle.

Updated 16/04/2018

Official Update Version 1.2
CODEX: SPACE MARINES
WARHAMMER 40,000 

Page 148 – Intercessor Squad, Wargear Options
Change the third bullet point to read:
‘The Intercessor Sergeant may either replace their
bolt rifle with a power sword, or take a power sword in
addition to their other weapons.’

**Comment by FarseerVeraenthis** [comment] 2018-08-08 13:53
duplicate of #3408

**Closed by FarseerVeraenthis** 2018-08-08 13:53 UTC
Labels: ✔ Res: duplicate
