### ISSUE TITLE
T'au: Commander in XV86 Coldstar weapon validation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3742] opened 2018-10-12 21:35 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Commander in Commander in XV86 Coldstar Battlesuit gets an error saying "Commander in XV86 Coldstar Battlesuit must have 1 more sections of Missile pod (minimum 1)" when High-output burst cannon is equipped while Missile pod is set to 0.
While the codex says "This model may replace its high-output burst cannon and/or missile pod with two items from the Ranged Weapons and/or Support Systems lists.". Since it says "and/or" it should be working but it gives said an error instead.

**Comment by amis92** [comment] 2018-10-12 21:56
Duplicate of #2936.

**Closed** 2018-10-14 09:50 UTC
Labels: Area: validation, Type: bug, ✔ Res: duplicate, 💾 Cat: T'au Empire
