### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2928] opened 2018-04-20 14:44 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** As of the 2018 FAQ Gulliman should be 400 points but he is instead 385. I've updated the app and I am using imperium - space marines v44. This bug is on the desktop version too.
It seems this has been missed off from the list update, as other changes that were implemented in the FAQ are reflected in this data list.

**Comment by GenWilhelm** [comment] 2018-04-20 15:51
Duplicate of #2891.

**Closed by GenWilhelm** 2018-04-20 15:51 UTC
