### ISSUE TITLE
[Anon] Bug report: Chaos - FW Heretic Astartes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2956] opened 2018-04-25 18:35 UTC
**File:** Chaos - FW Heretic Astartes.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** The point value of the Fire Raptor in the FW section isn't updated.

**Comment by Mad-Spy** [comment] 2018-04-25 18:36
Duplicate of #2872

**Closed by Mad-Spy** 2018-04-25 18:36 UTC
