### ISSUE TITLE
[Anon] Bug report: Aeldari - Harlequins.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6069] opened 2019-12-03 18:32 UTC
**File:** Aeldari - Harlequins.catz

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** No

**Description:** Harlequin Death Jester (Dreaming Shadow) cannot access the Curtainfall relic. Curtainfall is a death jester only relic that replaces the shrieker cannon profile.

**Comment by Mad-Spy** [comment] 2019-12-04 09:29
Duplicate of #6032

**Closed by Mad-Spy** 2019-12-04 09:29 UTC
