### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5184] opened 2019-06-01 20:16 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.02.03

**Platform:** Android

**Dropbox:** No

**Description:** When using the Stalker Pack spacialist detachment, the relic Ironfang of Ammagrimgul (replaces the power axe) cannot be given to the Wolf Guard Battle Leader. Given that HQ is a character and has the Battle Leader tag, it should be possible to give him that relic.

**Comment by Mad-Spy** [comment] 2019-06-04 05:24
Duplicate of #5176

**Closed by Mad-Spy** 2019-06-04 05:24 UTC
Labels: Area: selections, Type: bug, ✔ Res: duplicate, 💾 Cat: Imperium - Space Wolves
