### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4733] opened 2019-03-17 17:33 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.15

**Platform:** Mac

**Dropbox:** Yes

**Description:** Hey there, 

thank you for adding the Chaos Space Marine Shadowspear stuff so fast. I just wanted to let you know, that the new "Greater Possessed" unit is lacking its stats. 

best wishes, 
Bastian

**Comment by Mad-Spy** [comment] 2019-03-17 18:22
Duplicate of #4724

**Closed by Mad-Spy** 2019-03-17 18:22 UTC
