### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6020] opened 2019-11-25 04:36 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.15

**Platform:** Android

**Dropbox:** No

**Description:** The Space Marines always have access to every Salamanders tactic, , relic, special issue wargear, every thing Slamandeds, even when I have other Chapters selected.

**Comment by Mad-Spy** [comment] 2019-11-25 08:56
Duplicate of #5981

**Closed by Mad-Spy** 2019-11-25 08:56 UTC
