### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5995] opened 2019-11-19 02:41 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.07

**Platform:** Windows

**Dropbox:** No

**Description:** Select any chapter for your battalion, example Chapter Raven Guard, add a captain into HQ.  Make him a warlord.  The Salamander traits, relics, and stratagems are available on the list, including the Raven Guard ones.  The Salamander selections should be filtered out.  I tried it with Ultramarines, and all the Salamander selections are still possible.

**Comment by cqvo** [comment] 2019-11-20 13:14
Also shows up with White Scars selected

**Comment by williamcaw** [comment] 2019-11-20 19:59
Also when selecting relics

**Comment by Mad-Spy** [comment] 2019-11-20 21:34
Duplicate of #5981

**Closed by Mad-Spy** 2019-11-20 21:34 UTC
Labels: ✔ Res: duplicate
