### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4975] opened 2019-04-24 06:17 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.00

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The only catalogue I can load is the Renegade Knight. No other catalogue is available.

**Comment by williamcaw** [comment] 2019-04-24 06:28
Duplicate of #4959

**Closed** 2019-04-24 07:20 UTC
Labels: Area: BattleScribe app, ✔ Res: duplicate
