### ISSUE TITLE
Adeptus Custodes Storm Shield point costs swapped (already fixed)

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6143] opened 2019-12-10 11:49 UTC
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** Adeptus Custodes troop Storm Shield is 10 points, should be 5 points (it is only 10 points on characters).

**Comment by tekton** [comment] 2019-12-10 12:06
Duplicate of #6118

**Closed** 2019-12-10 12:45 UTC
Labels: Area: costs, ✔ Res: duplicate, 💾 Cat: Imperium  - Adeptus Custodes
