### ISSUE TITLE
Imperium - Blood Angels: Bolt sniper round profiles not updated

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5614] opened 2019-09-04 17:31 UTC
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.01

**Platform:** Windows

**Dropbox:** No

**Description:** The profile of each of the eliminators bolt sniper rifle rounds has not been updated to match the changes in the space marine summer update

**Comment by Mad-Spy** [comment] 2019-09-06 07:51
Duplicate of #5480

**Closed by Mad-Spy** 2019-09-06 07:51 UTC
Labels: Area: text/rule/profile, 💾 Cat: Imperium - Blood Angels, 📋 Task: update (new publication)
