### ISSUE TITLE
[Anon] Bug report: Imperium - Deathwatch.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5036] opened 2019-04-28 03:28 UTC
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.02.01

**Platform:** Android

**Dropbox:** No

**Description:** Using the boltgun option under deathwatch equipment gives an error, and never has before.  It says veteran has too many selections of from deathwatch equipment list (maximum 0)

**Comment by GenWilhelm** [comment] 2019-04-28 11:30
Duplicate of #5011

**Closed by GenWilhelm** 2019-04-28 11:30 UTC
