### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5105] opened 2019-05-08 04:14 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.02.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** The terrax pattern assault drill is missing from the dedicated transport section of the space wolf faction. It is specifically stated that they can have the assault drill as a transport but it can not use it for Wulfen or Primaris.

**Comment by WindstormSCR** [comment] 2019-05-08 15:38
Duplicate of #5094

**Closed by WindstormSCR** 2019-05-08 15:38 UTC
