### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4993] opened 2019-04-24 22:16 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.02.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** All the 40k lists have gone apart from chaos renegade knights,

**Comment by DrTobogganMD** [comment] 2019-04-24 22:17
Take a look at the stickies: Duplicate of #4959

**Closed by DrTobogganMD** 2019-04-24 22:17 UTC
