### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5000] opened 2019-04-25 04:34 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** For the warhammer 40k repository updated yesterday I can only access the Chaos Renegades army list when making a new list or adding a new detachment.

**Comment by fuckingenglish** [comment] 2019-04-25 04:46
the issue has been fixed pleas update the app

**Comment by WindstormSCR** [comment] 2019-04-25 14:07
duplicate of #4959

**Closed by WindstormSCR** 2019-04-25 14:07 UTC
