### ISSUE TITLE
Beasts of Nurgle - Wrong Keyword

### ISSUE THREAD

**Issue by Guy-Markman** [BSData/wh40k#5505] opened 2019-08-23 20:07 UTC
**File/Catalogue:** Chaos - Demons

**BattleScribe version:** 2.02.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:**
Beasts of Nurgle have the Faction: Khorne and Flesh Hounds keywords

**Comment by Mad-Spy** [comment] 2019-08-23 22:50
Duplicate of #5391. Already fixed.

**Closed by Mad-Spy** 2019-08-23 22:50 UTC
