### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6270] opened 2019-12-11 09:35 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** No

**Description:** The Missile Launcher should have dropped 5 points, from 15 to 10.

**Comment by Mad-Spy** [comment] 2019-12-11 10:31
Duplicate of #6264

**Closed by Mad-Spy** 2019-12-11 10:31 UTC
Labels: Area: costs, Type: bug, ✔ Res: duplicate, 💾 Cat: Imperium - Astra Militarum
