### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2676] opened 2018-03-19 11:51 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** The point cost for MV4 Shield Drone is not correct. It should be 10pts instead of 11pts.
11pts is for MV52 Shield drone, different variant.

**Comment by GenWilhelm** [comment] 2018-03-19 12:28
Duplicate of #2666.

**Closed by GenWilhelm** 2018-03-19 12:28 UTC
