### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2678] opened 2018-03-19 15:26 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The cost of the Shield Drone was wrong,it cost 10 points ecah,not 11.

Thank you

**Comment by Kohato** [comment] 2018-03-19 15:30
The MV4 was 1 point too high. It has been fixed, pending release.

Duplicate of #2666

**Closed by Kohato** 2018-03-19 15:30 UTC
Labels: Bug - cost, Resolution - duplicate, T'au
