### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4990] opened 2019-04-24 21:26 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.00

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When starting a new roster only given the option for Chaos-Renegade Knights v 15. Only started happening after recent update.

**Comment by WindstormSCR** [comment] 2019-04-24 21:56
Duplicate of #4959

**Closed by WindstormSCR** 2019-04-24 21:56 UTC
