### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3037] opened 2018-05-10 01:02 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.12

**Platform:** Windows

**Dropbox:** No

**Description:** Warlord's traits in Narrative gametype (Stronghold assault) are inverted.

**Comment by Mad-Spy** [comment] 2018-05-10 07:09
Duplicate of #3036

**Closed by Mad-Spy** 2018-05-10 07:09 UTC
Labels: Resolution - duplicate
