### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4693] opened 2019-03-08 08:55 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** New publication placeholder, new discipline psychic powers,  Area :  selection of

**Comment by Mad-Spy** [comment] 2019-03-08 10:29
Duplicate of #4674

**Closed by Mad-Spy** 2019-03-08 10:29 UTC
