### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4982] opened 2019-04-24 15:01 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Where it says to add a faction I only have renegade knights please help

**Comment by fuckingenglish** [comment] 2019-04-24 16:00
Duplicate of #4959 its being worked upon

**Closed** 2019-04-24 21:54 UTC
