### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2747] opened 2018-04-01 12:00 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** I cant choose a Warlord on my Space Marine roster... I can on the other I try, just not Space marines

**Comment by Kohato** [comment] 2018-04-01 12:28
Duplicate of #2736

**Closed by Kohato** 2018-04-01 12:28 UTC
Labels: Imperium - Space Marines, Resolution - duplicate
