### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1945] opened 2017-12-06 08:00 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.07

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The cost of wulfen stormshield and thunder hammer should be 21 points (16+5) not 25

**Comment by ilaunchbury** [comment] 2017-12-06 08:55
Duplicate of #1887.

**Closed by ilaunchbury** 2017-12-06 08:55 UTC
Labels: Bug - cost, Imperium - Space Wolves, Resolution - duplicate
