### ISSUE TITLE
[Anon] Bug report: Chaos - Death Guard.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4606] opened 2019-02-14 22:36 UTC
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Index Daemon Prince is still listed as a HQ choice in matched play as per the Designers Commentary flowchart it is no longer a legal choice for Death Guard armies. The vanilla Daemon Prince model has a datasheet in 2 different codices  (Chaos Space Marines & Thousand Sons) which would replace the datasheet in the index. The Daemon Prince datasheet in those two codices cannot replace <Legion> or Thousand Sons as per the rules in the respective codices.

**Comment by williamcaw** [comment] 2019-02-15 02:32
dupe of #4604

**Closed** 2019-02-15 08:33 UTC
Labels: Area: selections, Type: bug, ✔ Res: duplicate, 💾 Cat: Chaos - Death Guard
