### ISSUE TITLE
Aeldari - Craftworlds: Missing CA 2018 point changes

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4157] opened 2018-12-16 16:59 UTC
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Craftworld Eldar point costs still need updated for a few things post CA 2018. Two death spinners should be 12 as they are now 6 each. Dire avenger Exarch taking two avenger catapults also needs updated. It’s like the double weapon entries didn’t get updated. Also the DA Exarch shimmershield needs updated.

**Comment by WindstormSCR** [comment] 2018-12-16 20:00
Duplicate of #4030

**Closed by WindstormSCR** 2018-12-16 20:00 UTC
Labels: Area: costs, Type: bug, ✔ Res: duplicate, 💾 Cat: Aeldari - Craftworlds
