### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Custodes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4233] opened 2018-12-18 11:13 UTC
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.01.15

**Platform:** Mac

**Dropbox:** No

**Description:** In the adeptus custodes stormshield should be 10 points for everyone. At the moment stormshields for non-characters are have a point value of 2. This only is valid for for lesser mortals and not demigods (unfortunately) ;P

**Comment by Mad-Spy** [comment] 2018-12-18 11:46
Duplicate of #4213

**Closed by Mad-Spy** 2018-12-18 11:46 UTC
Labels: Area: costs, Type: bug, ✔ Res: duplicate, 💾 Cat: Imperium  - Adeptus Custodes
