### ISSUE TITLE
[Anon] Bug report: Imperium - Dark Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5520] opened 2019-08-24 17:18 UTC
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.00

**Platform:** Android

**Dropbox:** Yes

**Description:** Dark Angels don't seem to have assault marines when they should

**Comment by Mad-Spy** [comment] 2019-08-24 18:36
Duplicate of #5496

**Closed by Mad-Spy** 2019-08-24 18:36 UTC
