### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2729] opened 2018-03-27 23:11 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Rotigus in the Chaos Daemons data still has the old 12+ Wound track. It should be.

W        M  S  A
10-18  7"  7  5
5-9      5"  6  4
1-4      3"  5  3

**Comment by GenWilhelm** [comment] 2018-03-27 23:14
Duplicate of #2730.

**Closed by GenWilhelm** 2018-03-27 23:14 UTC
