### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4986] opened 2019-04-24 21:06 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When you try to add a new detachment the only option is to pick renegade knights.

**Comment by WindstormSCR** [comment] 2019-04-24 21:55
Duplicate of #4959

**Closed by WindstormSCR** 2019-04-24 21:55 UTC
