### ISSUE TITLE
Imperium - Astra Militarum: Regimental Heirlooms Not Available In Mixed Detachments

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3000] opened 2018-05-02 05:47 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Vostroyan Heirloom of Conquest, “The Armour of Graf Toschenko” is not available.

**Comment by GenWilhelm** [comment] 2018-05-02 09:36
It's available if you select Vostroyan as your regimental doctrine,
It should also be available in mixed (ie. Astra Militarum/Imperium) detachments, which it currently isn't.

**Comment by Kohato** [comment] 2018-05-03 02:24
Just a note for Joe and Alpha: Part one is a Duplicate of #2973 and has been fixed internally by Joe.

**Closed** 2018-05-20 23:51 UTC
Labels: Area: validation, Type: bug, 💾 Cat: Imperium - Astra Militarum
