### ISSUE TITLE
[Anon] Bug report: Chaos - FW Heretic Astartes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#843] opened 2017-07-17 22:35 UTC
**File:** Chaos - FW Heretic Astartes.catz

**BattleScribe version:** 2.01.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Missing entry for Slaanesh Sonic Dreadnought. Forgeworld affirms In the FAQ that this is still a unit

**Comment by GenWilhelm** [comment] 2017-07-17 22:46
Duplicate of #810.

**Closed by GenWilhelm** 2017-07-17 22:46 UTC
