### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2610] opened 2018-03-07 20:17 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Whenever I try to add my FW relic elites to my list it says I can’t have them which is really irritating.

**Comment by WindstormSCR** [comment] 2018-03-07 20:53
Duplicate of #2611

**Closed by WindstormSCR** 2018-03-07 20:53 UTC
Labels: Resolution - duplicate
