### ISSUE TITLE
T'au Empire: Battlesuit equipment validation bug

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6510] opened 2019-12-29 20:03 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** No

**Description:** Commander in XV84 Crisis Battlesuit don't checks number of a Commander Wargear Wargear choises. I can take 2+ guns and it don't write about, while it still checking drone count.

**Comment by derasoft** [comment] 2019-12-29 20:15
Update: support systems counts, but weapons don't. Also, its true for all commanders.

**Comment by amis92** [comment] 2019-12-29 22:29
I'll just call it a duplicate of #6510

**Closed by amis92** 2019-12-29 22:29 UTC
Labels: Area: BattleScribe app, Area: validation, Type: bug, 💾 Cat: T'au Empire
