### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6716] opened 2020-02-08 18:51 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.03.17

**Platform:** Android

**Dropbox:** No

**Description:** The support item selection is incorrect for the riptide suit it should be limited to 2 and you can select 3 and the broadsides are also wrong they should be limited to 1

**Comment by GenWilhelm** [comment] 2020-02-09 18:51
Duplicate of #6672

**Closed by GenWilhelm** 2020-02-09 18:51 UTC
