### ISSUE TITLE
[Anon] Bug report: Imperium - FW Adeptus Astartes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3654] opened 2018-09-21 12:14 UTC
**File:** Imperium - FW Adeptus Astartes.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Mortis Dreadnought has the option to take the cyclone missile launcher, as of FAQ v1.2 and above (https://whc-cdn.games-workshop.com/wp-content/uploads/2017/11/imperial_armour_index_forces_of_the_adeptus_astartes-1.pdf), this is no longer a legal option. Please remove the cyclone option from the Mortis Dreadnought (as much as I would like it to stay...!).

**Comment by Mad-Spy** [comment] 2018-09-21 14:27
Duplicate of #3487. Fixed in next release.

**Closed by Mad-Spy** 2018-09-21 14:27 UTC
Labels: Area: selections, Type: bug, ✔ Res: duplicate, 💾 Cat: Imperium - FW Adeptus Astartes
