### ISSUE TITLE
[Anon] Bug report: Imperium - Blood Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4314] opened 2018-12-23 20:42 UTC
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Blood Angels heavy onslaught gatling cannon is 6 points too expensive for redemptor dreadnought.

**Comment by Mad-Spy** [comment] 2018-12-23 21:18
Duplicate of #4294

**Closed by Mad-Spy** 2018-12-23 21:18 UTC
Labels: Area: costs, Type: bug, ✔ Res: duplicate, 💾 Cat: Imperium - Blood Angels
