### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5002] opened 2019-04-25 09:36 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Cannot load any Warhammer 40k 8th Ed (latest data) catalogues apart from Chaos Renegade Knights

**Comment by WindstormSCR** [comment] 2019-04-25 14:07
duplicate of #4959

**Closed by WindstormSCR** 2019-04-25 14:07 UTC
