### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2671] opened 2018-03-19 01:55 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** The point cost of the MV4 shield drone should be 10 pts instead of 11.  It is the MV52 shield drone that is 11 pts which only Shadowsun can take. Thank you.

**Comment by tekton** [comment] 2018-03-19 05:45
Duplicate of #2666

**Closed by tekton** 2018-03-19 05:45 UTC
Labels: Bug - cost, Resolution - duplicate, T'au
