### ISSUE TITLE
Imperium - Space Wolves - Thunderwolf missing Wolf Claw option

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#796] opened 2017-07-13 22:56 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** No

**Description:** Spaces Wolves - Thunderwolf Calvary - Add wolf claw to options to replace bolt pistol.

**Comment by penguin20000** [comment] 2017-07-14 09:08
Dupe of #712 :)

**Closed by penguin20000** 2017-07-14 09:08 UTC
Labels: Bug - choice
