### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3774] opened 2018-10-27 20:23 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Riptide's "Heavy Burst Cannon" was incorrectly replaced with "Swiftstrike Burst Cannon".

**Comment by GenWilhelm** [comment] 2018-10-27 22:33
Duplicate of #3766.

**Closed by GenWilhelm** 2018-10-27 22:33 UTC
