### ISSUE TITLE
Codex: Imperial Knights v3 bug item cant be selected /iOS/Android/

### ISSUE THREAD

**Issue by williamcaw** [BSData/wh40k#3247] opened 2018-06-11 15:03 UTC
File/Catalogue: Codex: Imperial Knights

BattleScribe version: 2.01.18

Platform: /iOS/Android/

Dropbox: no

Description: no force org slot house tradition selection can’t change. Default to Questor Imperialis. can’t change to Mechanicus houses. Area: selections Cat: Imperium - Questor Imperialis Type: bug

@Kohato
Contributor
Kohato commented 3 hours ago •
Yes you can, you need to go one level deeper. First radio button flips Imperialis/Mechanicus. Then you go one deeper to choose the house. It's not the most amazing UX, but it's used this way to make relic validation cleaner (and FW knight validation too, since they can't be Questor Mechanicus)

have done so as you have sated bug still persist on in iOS and Android systems . Household Choice cant be selected at all item keeps flowing to set preset of Questor Imperialis. as of june 10 2018 item was updated to be able to select Questor Mechanicus this cant be selected in the IOS and Android systems

 @alphalas
Contributor
alphalas commented 8 minutes ago
Duplicate #3243

 @alphalas alphalas closed this 8 minutes ago
@Kohato
Contributor
Kohato commented 2 minutes ago
@williamcaw - are you trying to assign Questor Mechanicus to a FW Knight? If so, that is not allowed. They are hard written to be Questor Imperialis as a faction keyword.

 @williamcaw
  
williamcaw commented a minute ago
selecting edit in only flows to the next level of choice of what houses to choose of default houses of cadmus griffith, hawkshroud , mortan and terryn this are the only house to be selected

 @williamcaw
  
williamcaw commented 40 seconds ago
this is not fw

 @williamcaw
  
williamcaw commented 20 seconds ago
read the path

**Comment by williamcaw** [comment] 2018-06-11 15:04
ill keep doing this tell you do a change of codeing

**Comment by amis92** [comment] 2018-06-11 15:05
Please don't or I'll have to ban you. You can comment on closed issues. Please don't open new ones.

**Comment by williamcaw** [comment] 2018-06-11 15:05
this is not a frken Duplicate

**Comment by alphalas** [comment] 2018-06-11 15:05
@williamcaw please see my response in #3243; this is not a bug and is functioning as expected

**Comment by amis92** [comment] 2018-06-11 15:06
Dupe of #3243.

**Comment by alphalas** [comment] 2018-06-11 15:06
@williamcaw yes it does.
First, go into the house selection, and tap the radio button
![383607d6-35a4-4e08-baf1-21488311aa9d](https://user-images.githubusercontent.com/15703066/41238799-d682b2a6-6d64-11e8-809d-799dcb8356bd.jpeg)

You’ll see a list of 3 options, all with radio buttons; tap the buttons to change
![31959675-dac7-4d35-93a1-5df853fab19d](https://user-images.githubusercontent.com/15703066/41238869-0714ca08-6d65-11e8-823a-489992ac07f8.jpeg)

Then hit the check mark, and click on the orange box or the name of the alignment 
![e51e3c26-2d0d-4e61-b467-a9816eb71823](https://user-images.githubusercontent.com/15703066/41238923-286e8306-6d65-11e8-8e45-40fcf60ad35d.jpeg)

That brings up another radio button, click it
![27029585-511f-46d6-ab2d-b07f7b2e5211](https://user-images.githubusercontent.com/15703066/41238957-4640a42c-6d65-11e8-81b6-dd5117239bc9.jpeg)

Which then brings up all the houses aligned to that allegiance.
![05647fd0-2380-45dc-b968-84b2fb40b3c6](https://user-images.githubusercontent.com/15703066/41239014-6fc0ff18-6d65-11e8-9f06-d65e04e94714.jpeg)

It does indeed work.

**Closed by amis92** 2018-06-11 15:06 UTC
Labels: ✔ Res: duplicate
