### ISSUE TITLE
Too many multi melta options doesn't allow 4 twin lascannon and missile launcher

### ISSUE THREAD

**Issue by xenoterracide** [BSData/wh40k#6060] opened 2019-12-02 01:07 UTC
**File/Catalogue:** chaos space Marines

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes

**Description:** Detailed issue description.

**Comment by Mad-Spy** [comment] 2019-12-02 08:50
Duplicate of #6027

**Closed by Mad-Spy** 2019-12-02 08:50 UTC
