### ISSUE TITLE
Aeldari - Craftworlds: Scattershield cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6281] opened 2019-12-11 11:28 UTC
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** The Wraithknight Ghostglaive and scattershield should cost 45 points as scattershield dropped from 30 to 15

**Comment by KalChoedan** [comment] 2019-12-11 11:31
Duplicate of #6130

**Closed** 2019-12-11 12:06 UTC
Labels: Area: costs, Type: bug, ✔ Res: duplicate, 💾 Cat: Aeldari - Craftworlds
