### ISSUE TITLE
Necrons: Command Barge missing keyword

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1604] opened 2017-10-10 12:37 UTC
**File:** Necrons.catz

**BattleScribe version:** 2.01.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Catacomb Command Barge is missing the "Character" keyword. This keyword was added in the Xenos 1 1.0 Errata.

**Comment by ilaunchbury** [comment] 2017-10-10 12:41
Duplicate of #1576 which has been fixed and will be in the next release.

**Closed by ilaunchbury** 2017-10-10 12:41 UTC
Labels: Bug - text/rule/profile, Necrons, Resolution - duplicate
