### ISSUE TITLE
[Anon] Bug report: Aeldari - Craftworlds.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5826] opened 2019-10-24 15:53 UTC
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Bonesingers are Craftworld Psykers that know the “Smite” power. Theoretically they should be eligible to trade out Smite for a Rune of Fortune power, but they currently do not have that option.

**Comment by Mad-Spy** [comment] 2019-10-24 15:55
Duplicate of #5823. Fixed in next release.

**Closed by Mad-Spy** 2019-10-24 15:55 UTC
