### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3945] opened 2018-12-04 20:30 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** Yes

**Description:** There are both no relics or Warlord traits for Space Wolves. This was working before.

**Comment by Mad-Spy** [comment] 2018-12-05 07:59
Duplicate of #3944

**Closed by Mad-Spy** 2018-12-05 07:59 UTC
