### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2675] opened 2018-03-19 10:14 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** Tau codex - mv4 shield drones 1 point over cost.  Should be 10 not 11

Thanks for a great app and data keep up the good work

**Comment by Mad-Spy** [comment] 2018-03-19 11:10
Duplicate of #2666

**Closed by Mad-Spy** 2018-03-19 11:10 UTC
Labels: Bug - cost, Resolution - duplicate, T'au
