### ISSUE TITLE
T'au Empire: Forgeworld T'au shield generator cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3720] opened 2018-10-06 07:45 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** For the forgeworld t'au special riptides like yvahra the point value of the shield generator should be 8 points since the Codex only excludes stormsurges and yvahra should be treated like a Ghostkeel.

T'au Empire > Fast Attack > XV109 Y'vahra Battlesuit > Support Systems > Shield generator ponit value should be 8.

**Comment by amis92** [comment] 2018-10-06 18:36
It's a duplicate of #3092.

Y'vahra isn't in the Codex, so it didn't get a specific update. It has a specific cost points entry in Index. General update doesn't override Y'vahra's specific row from FW Index.

**Closed** 2018-10-06 18:37 UTC
Labels: Area: costs, Type: bug, ✔ Res: duplicate, 💾 Cat: T'au Empire
