### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2293] opened 2018-01-21 17:04 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** Company Veterans on Bikes have an error:
Veteran Biker sergeant does not have the option to take a storm shield.

**Comment by ilaunchbury** [comment] 2018-01-21 21:59
Duplicate of #2292

**Closed by ilaunchbury** 2018-01-21 21:59 UTC
