### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4991] opened 2019-04-24 21:54 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Upon updating to the newest version, the Warhammer 40K data repository only allows me to select Chaos: Renegade Knights as a faction instead of all others.

**Comment by WindstormSCR** [comment] 2019-04-24 21:56
Duplicate of #4959

**Closed by WindstormSCR** 2019-04-24 21:56 UTC
