### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4970] opened 2019-04-24 00:38 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I updated the data on my iPhone 6s and noticed that the points were always 0 at the top of the screen. After deleting the list i tried to create a new one but the only army listed that the data shows is Renegade Knights (as cool as they are it was not the army I wanted to make).
Please help. 
Ulfhednir86@gmail.com

**Comment by williamcaw** [comment] 2019-04-24 01:36
This has been referred to the main thread

**Comment by DrTobogganMD** [comment] 2019-04-24 02:14
Duplicate of #4959

**Closed by DrTobogganMD** 2019-04-24 02:14 UTC
Labels: Area: BattleScribe app, Type: bug, ✔ Res: duplicate
