### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3195] opened 2018-05-31 13:44 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.13

**Platform:** Linux

**Dropbox:** No

**Description:** In Aldeari - Craftworlds v45 the Autarch on foot have automatically assigned the star glaive (6 pts) and cannot be removed even when using index wargear.

**Comment by WindstormSCR** [comment] 2018-05-31 13:55
Duplicate of #3194

**Closed by WindstormSCR** 2018-05-31 13:55 UTC
Labels: ✔ Res: deprecated, 💾 Cat: Aeldari - Craftworlds
