### ISSUE TITLE
Bug report: Imperium - Space Wolves - Intercessors

### ISSUE THREAD

**Issue by timbrown81** [BSData/wh40k#4064] opened 2018-12-15 13:14 UTC
**File/Catalogue:**  Imperium - Space Wolves.cat

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** Yes

**Description:** Chapter Approved included a new datasheet for Intercessors giving the Pack Leader the option to either exchange his bolt rifle for a chainsword, power sword or power fist.  Or the Pack Leader can take a chainsword, power sword or power fist.

**Comment by GenWilhelm** [comment] 2018-12-15 14:09
Duplicate of #4042

**Closed by GenWilhelm** 2018-12-15 14:09 UTC
