### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5509] opened 2019-08-24 01:21 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.00

**Platform:** Android

**Dropbox:** No

**Description:** Chaplain Grimaldus is missing the following:
This model knows the Litany of Hate (see below) and one litany from the Litanies of Battle (see Codex: Space 
Marines). At the start of the battle round, this model can recite one litany it knows that has not already been 
recited by a friendly model that battle round. Roll one D6; on a 3+ the recited litany is inspiring and takes effect 
until the end of that battle round.
Litany of Hate: If this Litany is inspiring, you can re-roll hit rolls for attacks made with melee weapons by models 
in friendly Black Templars units whilst their unit is within 6" of this mod

**Comment by Mad-Spy** [comment] 2019-08-24 18:18
Duplicate of #5508

**Closed by Mad-Spy** 2019-08-24 18:18 UTC
