### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Custodes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4263] opened 2018-12-19 15:09 UTC
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.01.15

**Platform:** Mac

**Dropbox:** Yes

**Description:** Storm Shield for Custodian Guard is 2 points in Battlescribe. According to Codex: Adeptus Custodes, it should be 10 points (p.79). It was only the Storm Shield (Characters) that received a points change in Chapter Approved 2018. Thanks for all you do!

**Comment by Mad-Spy** [comment] 2018-12-19 15:14
Duplicate of #4213

**Closed by Mad-Spy** 2018-12-19 15:14 UTC
