### ISSUE TITLE
Eradicator MM Points: should be 50 (not 60)

### ISSUE THREAD

**Issue by asdf2134** [BSData/wh40k#8530] opened 2020-10-30 15:26 UTC
**File/Catalogue:** 
Warhammer 40k v9.1.0

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux
Windows

**Dropbox:** Yes/No
?
**Description:** Detailed issue description.

The codex states that Eradicators cost 40 points per model, and that Multi-melta is +10 pts, hence should be 50 pts. However Battlescribe has Eradicator with MM as 60 pts. 
![image](https://user-images.githubusercontent.com/73708488/97723890-a75f5900-1aa2-11eb-9866-1d78ac8ee59a.png)

**Comment by Mad-Spy** [comment] 2020-10-30 16:05
Duplicate of #8419

**Closed by Mad-Spy** 2020-10-30 16:05 UTC
