### ISSUE TITLE
[Anon] Bug report: Aeldari - Drukhari.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2825] opened 2018-04-11 12:56 UTC
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.01.10

**Platform:** Windows

**Dropbox:** No

**Description:** Haywire Blasters are listed as Assault 1 and should be Assault d3

**Comment by FarseerVeraenthis** [comment] 2018-04-11 13:06
Duplicate of #2808

**Closed by FarseerVeraenthis** 2018-04-11 13:06 UTC
