### ISSUE TITLE
Error with chapter special issue wargear

### ISSUE THREAD

**Issue by Drakamas** [BSData/wh40k#6038] opened 2019-11-29 19:42 UTC
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** iOS

**Description:** when selecting chapter specific special-issue wargear relics for my salamander successor chapter I’m receiving a “has to many selections of chapter relics (maximum 0)”
Attached are screen shots
![F2BB17BC-674C-499E-BD2D-A339DBBCD0BD](https://user-images.githubusercontent.com/58343595/69887710-aa642f00-12be-11ea-9ba8-eba9ac437f9f.jpeg)
![69EEA7B0-E909-43E0-8C77-F9317FA10555](https://user-images.githubusercontent.com/58343595/69887711-aafcc580-12be-11ea-8d3e-083e3308319a.jpeg)

**Comment by WindstormSCR** [comment] 2019-11-29 20:43
duplicate of #5998

**Closed by WindstormSCR** 2019-11-29 20:43 UTC
