### ISSUE TITLE
[Anon] Bug report: Aeldari - Harlequins.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5056] opened 2019-04-30 15:35 UTC
**File:** Aeldari - Harlequins.catz

**BattleScribe version:** 2.02.01

**Platform:** Android

**Dropbox:** No

**Description:** Aeldari harlequin shadowseer, am able to choose it as warlord, but not to choose warlord trait. Should be able to.

**Comment by WindstormSCR** [comment] 2019-04-30 18:26
Duplicate of #5050

**Closed by WindstormSCR** 2019-04-30 18:26 UTC
