### ISSUE TITLE
[Anon] Bug report: Aeldari - Craftworlds.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3176] opened 2018-05-28 04:55 UTC
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.01.19

**Platform:** Android

**Dropbox:** No

**Description:** Eldrad Ulthran has become hidden for some reason.  Can't take him even after selecting Ulthwe as my Craftworld.

**Comment by Kohato** [comment] 2018-05-28 13:42
Duplicate of #3173

**Closed by Kohato** 2018-05-28 13:42 UTC
