### ISSUE TITLE
[Anon] Bug report: Imperium - Blood Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3805] opened 2018-11-02 20:30 UTC
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** The sanguinary priest on bike is missing his twin boltgun.

**Comment by Mad-Spy** [comment] 2018-11-02 21:19
Duplicate of #3698

**Closed by Mad-Spy** 2018-11-02 21:19 UTC
Labels: Area: selections, Type: bug, ✔ Res: duplicate, 💾 Cat: Imperium - Blood Angels
