### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4087] opened 2018-12-15 17:05 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Maulerfiend os 140 anda should be 120, updated un thriller chapter approved

**Comment by GenWilhelm** [comment] 2018-12-15 20:50
Duplicate of #4078

**Closed by GenWilhelm** 2018-12-15 20:50 UTC
