### ISSUE TITLE
[Anon] Bug report: Imperium - Deathwatch.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6724] opened 2020-02-10 00:45 UTC
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** No

**Description:** Bolt Rifles carried by Deathwatch Intercessor Sergeants cost one point, but they should cost zero.

**Comment by fuckingenglish** [comment] 2020-02-10 01:53
#6723

**Comment by Mad-Spy** [comment] 2020-02-10 09:21
Duplicate of #6504

**Closed by Mad-Spy** 2020-02-10 09:21 UTC
