### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4996] opened 2019-04-24 23:41 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Only thing I can select is the renegade knights faction

**Comment by fuckingenglish** [comment] 2019-04-25 01:16
the issue has been fixed pleas update the app on ituns.

**Comment by WindstormSCR** [comment] 2019-04-25 14:06
duplicate of #4959

**Closed by WindstormSCR** 2019-04-25 14:06 UTC
