### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5351] opened 2019-07-29 06:07 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.29

**Platform:** Android

**Dropbox:** No

**Description:** Tank Commander gives one of every turret option by default

**Comment by Mad-Spy** [comment] 2019-07-29 20:27
Duplicate of #5338

**Closed by Mad-Spy** 2019-07-29 20:27 UTC
Labels: Area: validation, 💾 Cat: Imperium - Astra Militarum
