### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4974] opened 2019-04-24 06:05 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.00

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When attempting to make a new list in the most recently uploaded warhammer 40k option, only renagade knights are available to be selected as a faction. When editing a list the information for other factions that already existed in the list remain, but trying to add new forces to the list give the same problem of only being able to see renagade knights as an option.

**Comment by williamcaw** [comment] 2019-04-24 06:29
Duplicate of #4959

**Closed** 2019-04-24 07:21 UTC
Labels: ✔ Res: duplicate
