### ISSUE TITLE
[Anon] Bug report: Imperium - Grey Knights.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3013] opened 2018-05-05 02:50 UTC
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.01.12

**Platform:** Mac

**Dropbox:** No

**Description:** The system is calling a lineup invalid if multiple Grandmasters in Dreadknights do not have the same number of selections from Ranged weapons. They can be outfitted with different weapons and a different number of weapons

**Comment by tekton** [comment] 2018-05-07 03:42
I am not able to reproduce that in the v18 file; though I do wonder if it's a BattleScribe bug...

**Comment by tekton** [comment] 2018-05-07 16:31
I've now tried it on a bunch of systems and can't seem to replicate this so I'm going to close it out.

**Closed by tekton** 2018-05-07 16:31 UTC
Labels: Bug - choice, Imperium - Grey Knights
