### ISSUE TITLE
[Anon] Bug report: Aeldari - Drukhari.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2818] opened 2018-04-10 05:40 UTC
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.01.10

**Platform:** Windows

**Dropbox:** No

**Description:** Haywire blasters should be Assault D6 not Assault 1. Change Assault 1 to Assault D6

**Comment by GenWilhelm** [comment] 2018-04-10 12:57
Duplicate of #2808.

**Closed by GenWilhelm** 2018-04-10 12:57 UTC
