### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2672] opened 2018-03-19 02:22 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** Yes

**Description:** The tau mv4 shield drones are 10 points not 11 as listed currently

**Comment by tekton** [comment] 2018-03-19 05:44
Duplicate of #2671

**Closed by tekton** 2018-03-19 05:44 UTC
Labels: Resolution - duplicate
