### ISSUE TITLE
[Anon] Bug report: Imperium - Deathwatch.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5302] opened 2019-07-14 13:22 UTC
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.02.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Deathwatch (and every other space marine chapter besides the Default one, I.e. Blood angels, Dark angels and space wolves) still do not have access to the Primaris Repulsor Executioner.

**Comment by Mad-Spy** [comment] 2019-07-14 13:43
Duplicate of #5275. We haven't seen any rules to say that you can replace `<CHAPTER>` with those keywords yet.

**Closed by Mad-Spy** 2019-07-14 13:43 UTC
