### ISSUE TITLE
[Anon] Bug report: Aeldari - Craftworlds.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3175] opened 2018-05-28 04:12 UTC
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.13.10

**Platform:** Windows

**Dropbox:** No

**Description:** Craftworld Eldar Special Characters are not selectable even when you have correct craftworld selected

**Comment by Kohato** [comment] 2018-05-28 13:42
Duplicate of #3173

**Closed by Kohato** 2018-05-28 13:42 UTC
