### ISSUE TITLE
[Anon] Bug report: Imperium - Deathwatch.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6542] opened 2020-01-06 04:46 UTC
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.17

**Platform:** Android

**Dropbox:** No

**Description:** Deathwatch intercessor kill team Sargent weapons points are not correct

**Comment by Mad-Spy** [comment] 2020-01-06 09:04
Duplicate of #6504

**Closed by Mad-Spy** 2020-01-06 09:04 UTC
