### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5809] opened 2019-10-22 17:58 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** There isnt “Reiver” keyword if i choose 1 heavy bolt pistol and 1 combat knife in datasheet for Lieutenants in Phobos Armor. And Terror Troops ability too.

**Comment by Mad-Spy** [comment] 2019-10-22 20:29
Duplicate of #5691

**Closed by Mad-Spy** 2019-10-22 20:29 UTC
