### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4978] opened 2019-04-24 09:13 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** All catalouges are away....
I can only add Chaos renegade Knights to any rooster...

**Comment by amis92** [comment] 2019-04-24 10:20
Duplicate of #4959

**Closed by amis92** 2019-04-24 10:20 UTC
Labels: Area: BattleScribe app, Type: bug, ✔ Res: duplicate
