### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5811] opened 2019-10-22 22:43 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.05

**Platform:** Android

**Dropbox:** Yes

**Description:** Battlescribe V2.03.05.311.
Using SM V119, warhammer 40k V1.3.25.
The Impulsor doesn't have a power level. It should be power level 4.

**Comment by Mad-Spy** [comment] 2019-10-23 19:52
Duplicate of #5711

**Closed by Mad-Spy** 2019-10-23 19:52 UTC
