### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3653] opened 2018-09-21 03:33 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Wolf priest does not have warlord traits when given the warlord option

**Comment by Mad-Spy** [comment] 2018-09-21 06:48
Duplicate of #3610. Resolved in next release.

**Closed by Mad-Spy** 2018-09-21 06:48 UTC
Labels: Area: selections, Type: bug, ✔ Res: duplicate, 💾 Cat: Imperium - Space Wolves
