### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4983] opened 2019-04-24 17:55 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Warhammer 8th edition v96 since the update only has the chaos renegade knights codex nothing else

**Comment by williamcaw** [comment] 2019-04-24 20:43
Duplicate of #4959. It’s being worked upon.

**Closed** 2019-04-24 21:54 UTC
