### ISSUE TITLE
[Anon] Bug report: Chaos - Death Guard.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7157] opened 2020-05-23 10:54 UTC
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.03.13

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Myphitic Blight Hauler do not have the hability of Terna. That appear in the Death Guard Codex, when you have 3 Myphitic.

**Comment by Mad-Spy** [comment] 2020-05-23 16:12
Duplicate of #7158

**Closed by Mad-Spy** 2020-05-23 16:12 UTC
