### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4057] opened 2018-12-15 12:10 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** These CA 2018 point changes seem to be missing from space marines:
Power fist 
Aux. Grenade launcher of Intercessors

There might be more but these I noticed.

**Comment by GenWilhelm** [comment] 2018-12-15 14:11
Duplicate of #4059

**Closed by GenWilhelm** 2018-12-15 14:11 UTC
