### ISSUE TITLE
Imperium - Space Wolves: Companion's Blade not available

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7153] opened 2020-05-22 08:39 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.23

**Platform:** Android

**Dropbox:** Yes

**Description:** Relic of the Fang COMPANION'S BLADE
characters with a Power Sword or Master Crafted Power Sword. 
this relic is not listed as an option when a character is using a Power Sword nor Master Crafted PS. 
This option should be available to every non named Character using the above mentioned plus The Champion of The Chapter who uses MCPS always

**Comment by Mad-Spy** [comment] 2020-05-22 11:55
Duplicate of #7097

**Closed by Mad-Spy** 2020-05-22 11:55 UTC
Labels: Area: selections, Type: bug, 💾 Cat: Imperium - Space Wolves
