### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1272] opened 2017-08-17 16:20 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** In the Space Marine army list the Auxillary Grenade launcher is still listed as No Cost for the Primaris Intercessor squad.  It has been errata'd to cost 1 point from the GW website..

https://www.games-workshop.com/resources/PDF/Errata/Warhammer_40000/Codex_Space_Marines_ENG.pdf

**Comment by GenWilhelm** [comment] 2017-08-17 19:14
Duplicate of #1206.

**Closed by GenWilhelm** 2017-08-17 19:14 UTC
Labels: Resolution - duplicate
