### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5518] opened 2019-08-24 16:56 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.00

**Platform:** Android

**Dropbox:** No

**Description:** Conscripts should now be 3 points per model instead of 4. Also they should be in the troops category, they are currently uncategorised.

**Comment by Mad-Spy** [comment] 2019-08-24 18:25
Duplicate of #5496 and cost issue is incorrect as Conscripts have been 4pts since CA2018 came out.

**Closed by Mad-Spy** 2019-08-24 18:25 UTC
