### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5043] opened 2019-04-29 16:22 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** BIG FAQ ... 3? Or BIG FAQ 1, Year 2, Electric Boogaloo? #4932 item is now live

**Comment by fuckingenglish** [comment] 2019-04-29 16:27
https://www.warhammer-community.com/wp-content/uploads/2019/04/warhammer_40000_update_April_2019_en.pdf

**Comment by fuckingenglish** [comment] 2019-04-29 16:55
https://www.warhammer-community.com/wp-content/uploads/2019/04/warhammer_40000_imperium_nihilus_vigilus_ablaze_en.pdf

**Comment by DrTobogganMD** [comment] 2019-04-29 23:10
We're aware - each author is updating the cat files - we won't need another overall issue. I'll just mark things as Duplicate of #4932.

**Closed by DrTobogganMD** 2019-04-29 23:10 UTC
