### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Custodes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6232] opened 2019-12-10 21:41 UTC
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** No

**Description:** The stormshield on the custodes troop choice is still at 10 points. It should be 5.
Shared selection entries>custodian guard squad>custodian>storm shield point value 10 too 5
The storm shield shared entry seems unused.

**Comment by tekton** [comment] 2019-12-10 22:11
Thank you kindly! This is a duplicate of #6118 and will be fixed in the next release!

**Closed by tekton** 2019-12-10 22:11 UTC
