### ISSUE TITLE
[Anon] Bug report: Aeldari - Harlequins.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6010] opened 2019-11-22 20:17 UTC
**File:** Aeldari - Harlequins.catz

**BattleScribe version:** 2.03.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** It is not recognizing the masque selection therefore not letting you pick relics or warlord traits from the chosen masque. Thanks

**Comment by WindstormSCR** [comment] 2019-11-24 14:39
Duplicate of #5986

**Closed by WindstormSCR** 2019-11-24 14:39 UTC
