### ISSUE TITLE
[Anon] Bug report: Aeldari - Harlequins.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5061] opened 2019-05-01 16:24 UTC
**File:** Aeldari - Harlequins.catz

**BattleScribe version:** 2.02.01

**Platform:** Android

**Dropbox:** No

**Description:** Shadowseer can't take warlord traits since the ynnari update.

**Comment by Mad-Spy** [comment] 2019-05-01 19:20
Duplicate of #5050. Fixed in next release.

**Closed by Mad-Spy** 2019-05-01 19:20 UTC
