### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4156] opened 2018-12-16 16:13 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** XV95 Ghostkeel is set at 72 points should be 70 points base cost.

**Comment by GenWilhelm** [comment] 2018-12-16 16:17
Duplicate of #4035

**Closed by GenWilhelm** 2018-12-16 16:17 UTC
