### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2889] opened 2018-04-18 13:53 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** Lord Commissar cost 55, should cost 30

Commissar cost 30, should cost 15

**Comment by GenWilhelm** [comment] 2018-04-18 14:53
Duplicate of #2866.

**Closed by GenWilhelm** 2018-04-18 14:53 UTC
