### ISSUE TITLE
[Anon] Bug report: Necrons.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2784] opened 2018-04-07 22:28 UTC
**File:** Necrons.catz

**BattleScribe version:** 2.01.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Necron codex says "deathgaurd" are troops but are listed as elites in battle scribe.

**Comment by WindstormSCR** [comment] 2018-04-07 23:43
Duplicate of #2743

**Closed by WindstormSCR** 2018-04-07 23:43 UTC
Labels: Necrons, Resolution - duplicate
