### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3922] opened 2018-11-23 09:23 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Ork Elite Unit missing: Runtherd, see Codex Orks 2018 page 205 (ibook enhanced edition)
,

**Comment by Mad-Spy** [comment] 2018-11-23 10:50
As Runtherds don't take up a Force Org slot in Battle-forged armies, they have been moved to the No Force Org group.

Duplicate of #3899

**Closed by Mad-Spy** 2018-11-23 10:50 UTC
Labels: Area: selections, Type: bug, ✔ Res: duplicate, 💾 Cat: Orks
