### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5405] opened 2019-08-20 16:08 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.02.04

**Platform:** Android

**Dropbox:** No

**Description:** Space marine incursors points are wrong and I think the inviticus warsuit is wrong too. Thank you for your great work. Also the app seems to be running super slow now. It was fast until the last 2 updates

**Comment by WindstormSCR** [comment] 2019-08-20 17:22
Duplicate of #5403 #5404

**Closed by WindstormSCR** 2019-08-20 17:22 UTC
Labels: 💾 Cat: Imperium - Space Marines
