### ISSUE TITLE
[Anon] Bug report: Chaos - Death Guard.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3686] opened 2018-09-27 14:48 UTC
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Missing plaguebearers in the troops section, no data present

**Comment by Mad-Spy** [comment] 2018-09-27 14:52
Duplicate of #3684

**Closed by Mad-Spy** 2018-09-27 14:52 UTC
