### ISSUE TITLE
[Anon] Bug report: Orks.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5519] opened 2019-08-24 17:07 UTC
**File:** Orks.catz

**BattleScribe version:** 2.03.00

**Platform:** Windows

**Dropbox:** Yes

**Description:** The standard Warboss Hq choice is missing from the Ork roster.

**Comment by Mad-Spy** [comment] 2019-08-24 18:25
Duplicate of #5496

**Closed by Mad-Spy** 2019-08-24 18:25 UTC
