### ISSUE TITLE
[Anon] Bug report: Aeldari - Ynnari.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1796] opened 2017-11-22 04:31 UTC
**File:** Aeldari - Ynnari.catz

**BattleScribe version:** 2.01.05

**Platform:** Windows

**Dropbox:** Yes

**Description:** Maugan Ra's points need to be adjusted from 159 to 140. In fact, the entire Ynnari list needs to be updated to reflect the points drops brought about Codex Craftworlds.

**Comment by ilaunchbury** [comment] 2017-11-22 08:12
Duplicate of #1699

**Closed by ilaunchbury** 2017-11-22 08:12 UTC
Labels: Aeldari - Ynnari, Bug - cost, Resolution - duplicate
