### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1888] opened 2017-12-03 21:39 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.07

**Platform:** Android

**Dropbox:** No

**Description:** The cost of the autocannon is wrong (20). After CA it goes down from 20 to 15.

**Comment by GenWilhelm** [comment] 2017-12-04 01:52
Duplicate of #1862.

**Closed by GenWilhelm** 2017-12-04 01:52 UTC
