### ISSUE TITLE
Imperium - Astra Militarum: Make abilities visible in Summary view

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1712] opened 2017-11-03 15:20 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.05

**Platform:** Windows

**Dropbox:** No

**Description:** The ability rules for units are formatted such that they don't abide by the "Include Rules?" options in the viewer, and instead keep all their data in the "Include Profile?" section. This means, among other things, that changing the Profile option to summary view removes all ability names from the inline profiles.

**Comment by alphalas** [comment] 2017-12-01 16:25
Duplicate of #1853

**Closed by alphalas** 2017-12-01 16:25 UTC
Labels: Imperium - Astra Militarum, Task - massive
