### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7265] opened 2020-06-23 06:34 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Lord Commissars and Commissars have the Voice of Command special ability. This needs to be hidden or removed unless they are your Warlord and have the Master of Command Warlord Trait.

**Comment by Mad-Spy** [comment] 2020-06-23 08:15
Duplicate of #7262

**Closed by Mad-Spy** 2020-06-23 08:15 UTC

**Comment by alphalas** [comment] 2020-06-23 21:10
https://github.com/BattleScribe/Release/issues/218
