### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Custodes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5567] opened 2019-08-27 21:44 UTC
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.00

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Valdorus and other thing part of issue with #5496.

**Comment by Mad-Spy** [comment] 2019-08-27 22:51
Duplicate of #5496. Updating to Battlescribe 2.03.01 will resolve this.

**Closed by Mad-Spy** 2019-08-27 22:51 UTC
Labels: Area: BattleScribe app, Type: bug, ✔ Res: external

**Comment by Mad-Spy** [comment] 2019-08-28 01:27
Yes it is, as of 28/08/19.

![image](https://user-images.githubusercontent.com/29306451/63818975-610ce800-c93b-11e9-9f21-c43fa181c366.png)
