### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5967] opened 2019-11-13 19:26 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Hello, There is a mistake with chaplain Cassius. 
He knows Litany of Hate + 2 other litanies to choose among 6 (codex ultramarine p.65).
But we cannot choose 2 other litanies (2 max instead of 3)
Thank you !

**Comment by Mad-Spy** [comment] 2019-11-13 20:07
Duplicate of #5912

**Closed by Mad-Spy** 2019-11-13 20:07 UTC
Labels: Area: BattleScribe app, Type: bug
