### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3581] opened 2018-09-08 00:14 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** With the coldstar doesn't have options for more than one hobc nor can you just select that without a missile pod. same error exists in android

**Comment by amis92** [comment] 2018-09-08 10:57
Duplicate of #2936

Also, you cannot have multiple HOBCs - it's a default loadout and nowhere on the weapon lists to be found.

**Closed by amis92** 2018-09-08 10:57 UTC
Labels: Area: validation, Type: bug, ✔ Res: duplicate, ✔ Res: invalid, 💾 Cat: T'au Empire
