### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5637] opened 2019-09-10 17:00 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.01

**Platform:** Windows

**Dropbox:** No

**Description:** PL for hellblasters is incorrect.  With the Space Marines FAQ, this was increased to 8 from 6 for the first five, and to 8 from 6 for up to an additional five.

**Comment by Mad-Spy** [comment] 2019-09-11 08:44
Duplicate of #5630

**Closed by Mad-Spy** 2019-09-11 08:44 UTC
Labels: Area: costs, Type: bug, ✔ Res: duplicate, 💾 Cat: Imperium - Space Marines
