### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4967] opened 2019-04-23 20:46 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Hi, 

I have troubles with the rosters for 40k - I am using the Desktop (MAC) and IOS versions of BattleScribe and while all available factions show up in the desktop version, the iOS version only shows Chaos Knights. I tried disconnecting from Dropbox and refreshing the data including "delete old filed" without success, so I assume it is not an issue with the dropbox connection but with the actual data-catalogue interconnectivity for the faction data files.

Steps to reproduce:
desktop: new roster -> select faction from catalogue -> all factions listed in the pulldown
ios: roster overview - hit (+) - factions list only shows "Chaos Knights"

**Comment by WindstormSCR** [comment] 2019-04-23 22:13
Duplicate of #4959

**Closed by WindstormSCR** 2019-04-23 22:13 UTC
