### ISSUE TITLE
[Anon] Bug report: Chaos - FW Heretic Astartes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5009] opened 2019-04-25 13:46 UTC
**File:** Chaos - FW Heretic Astartes.catz

**BattleScribe version:** 2.02.01

**Platform:** Windows

**Dropbox:** No

**Description:** FW Heretic Astarters v31 -> Elites -> Hellforged Contemptor Dreadnought point go wrong when selecting two claw options (IE Chain/Death Claw) that are the same. It should give a point reduction in selecting two of the same but it does not do this correctly.

**Comment by WindstormSCR** [comment] 2019-04-25 14:10
duplicate of #5008

**Comment by williamcaw** [comment] 2019-04-25 14:10
Duplicate Of #5008

**Closed by WindstormSCR** 2019-04-25 14:10 UTC
