### ISSUE TITLE
Imperium - Blood Angels: Add Repulsor Executioner

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5291] opened 2019-07-11 02:47 UTC
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.29

**Platform:** Android

**Dropbox:** No

**Description:** The. Replsour excutioner data sheet is missing from the heavy support slot for blood angels

**Comment by Mad-Spy** [comment] 2019-07-11 08:12
It's currently only been added to Space Marines, because we haven't seen full rules to see whether it's actually available to anyone else.

**Comment by Thairne** [comment] 2019-07-12 13:59
essentially duplicate of #5275

**Comment by chainw0** [comment] 2019-08-10 08:58
Still isn't available in battlescribe...

**Closed** 2019-08-13 21:09 UTC
Labels: Area: selections, Type: request, 💤 Pending: check required, 💾 Cat: Imperium - Blood Angels
