### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2686] opened 2018-03-20 03:36 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** MV4 Shield Drones are supposed to be 10 points, not 11.

**Comment by Mad-Spy** [comment] 2018-03-20 08:26
Duplicate of #2666

**Closed by Mad-Spy** 2018-03-20 08:26 UTC
