### ISSUE TITLE
Imperium - Blood Angels: Various issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6283] opened 2019-12-11 11:39 UTC
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.06

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Few things
1. Blood angels chaplains or Astorath can’t select invocation of destruction without getting an error that can’t be fixed
2. No sokar pattern Stormbird in LOW choices
3. Intercessors sergeants and intercessors Death company cc Marine don’t have access to thunder hammers
4. Can only select one relic and no option to increase the armoury of Baal to include more relics like the space marine data files
5. Selecting a warlord does not give access to a relic
Sorry for pointing out so many but thought it would be smart to do it all at the same time, again thankyou for the amazing work

**Comment by onlyamonth** [comment] 2019-12-11 12:15
1. Astorath has invocation baked in. Can't reproduce error on chaplains or lemartes - i deleted existing data when updating, maybe this will help? 
3. Mine do, again, maybe deleting existing data when you update will help.
4. Whilst I cannot change armory of baal to more than one relic, I am able to add two relics to my list while using armory of baal.
5. Again, does for me. Your data may need cleaning.

**Comment by sfPanzer-BnC** [comment] 2019-12-11 12:16
Intercessor Sergeants and DC Intercessor with CCW definitely have access to Thunderhammers in the current version. Might be an update issue here.

**Comment by Mad-Spy** [comment] 2019-12-11 12:20
It's possible OP is still on v1.4.0, at least some of these issues were resolved in v1.4.1 (BA v107).

**Comment by Vb2341** [comment] 2019-12-11 22:38
I think the assault bolter points in 1.4.1 are somewhat incorrect.   The assault bolter (inceptor weapon) was reduced from 10 points to 8 points, however I think this is only reflected for the cost of the Sergeant's weapons.  The point total for 3 inceptors is 131.  That is 25x3 for the bodies, plus 2x8 + 2x10 + 2x10 (each inceptor carries two assault bolters).  The total cost for the unit should be 123 points, at 75 for 3 bodies and 48 (3 x 2 x 8) for the weapons.

**Comment by alphalas** [comment] 2019-12-12 18:17
merged into #6254

**Closed by alphalas** 2019-12-12 18:17 UTC
Labels: Area: selections, Type: bug, 💤 Pending: check required, 💾 Cat: Imperium - Blood Angels
