### ISSUE TITLE
[Anon] Bug report: Aeldari - Craftworlds.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3178] opened 2018-05-28 16:15 UTC
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.01.19

**Platform:** Android

**Dropbox:** No

**Description:** Craftworld specific characters aren't showing up in the HQ section, even when mixed or the specific craftworld are selected.

**Comment by amis92** [comment] 2018-05-28 17:13
Duplicate of #3173

**Closed by amis92** 2018-05-28 17:13 UTC
Labels: Area: selections, Type: bug, ✔ Res: duplicate, 💾 Cat: Aeldari - Craftworlds
