### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6015] opened 2019-11-24 02:33 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.08

**Platform:** Mac

**Dropbox:** No

**Description:** I am playing a Salamanders successor and my warlord is a Chaplain Venerable Dreadnought. I used 1 CP on Trust of Prometheus and gave my Captain in Cataphractii Armour the relic Vulkan's Sigil. Battlescribe says that I have too many relics in my army (maximum 0), even though I can give one character a relic.

**Comment by WindstormSCR** [comment] 2019-11-24 14:39
Duplicate of #5998

**Closed by WindstormSCR** 2019-11-24 14:39 UTC
