### ISSUE TITLE
CSM Red Corsairs Reaver Lord issue

### ISSUE THREAD

**Issue by p5freak** [BSData/wh40k#5254] opened 2019-06-27 11:04 UTC
**Catalogue** CSM v98

**BattleScribe version:** 2.02.04.125

**Platform:** Windows

**Dropbox:** No

**Description:** 

The Warlord Trait Reaver Lord for Red Corsairs allows any Red Corsairs CHARACTER to get a second Relic for free. Right now this free Relic can only be given to another Red Corsairs CHARACTER in the same Detachment. But Reaver Lord says any Relic Corsairs CHARACTER in your Army, so it shouldnt be limited to the Detachment where your Warlord is.

**Comment by Mad-Spy** [comment] 2019-06-28 07:18
Duplicate of #5203, which was released in v1.3.7 5 days ago. Please update your data.

**Closed by Mad-Spy** 2019-06-28 07:18 UTC
