### ISSUE TITLE
[Anon] Bug report: Tyranids.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1713] opened 2017-11-03 21:58 UTC
**File:** Tyranids.catz

**BattleScribe version:** 2.01.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** The Tyrannocyte rule "Invasion Organism" is incorrect says that it has to be deployed  at the beginning of the first battle round but before the first turn begins, this is incorrect it can be deployed at the end of any of your movement phases.

**Comment by ilaunchbury** [comment] 2017-11-04 07:56
Duplicate of #1695

**Closed by ilaunchbury** 2017-11-04 07:56 UTC
