### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5001] opened 2019-04-25 07:53 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** when i try to create a new roster the only faction that appears is chaos: renegade knights

**Comment by williamcaw** [comment] 2019-04-25 14:07
The issue is resolved please update this app.

**Comment by WindstormSCR** [comment] 2019-04-25 14:07
duplicate of #4959

**Closed by WindstormSCR** 2019-04-25 14:07 UTC
