### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5979] opened 2019-11-16 05:57 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.12

**Platform:** Android

**Dropbox:** No

**Description:** Created an Imperial Fists battalion detachment of space marines. I can select a warlord and warlord trait, but the list is labelled as invalid if I select a relic. This happens regardless of which HQ I use as a warlord, and which relic is selected.

**Comment by Mad-Spy** [comment] 2019-11-20 21:19
Duplicate of #5978

**Closed by Mad-Spy** 2019-11-20 21:19 UTC
Labels: ✔ Res: duplicate
