### ISSUE TITLE
[Anon] Bug report: Chaos - Death Guard.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1654] opened 2017-10-20 15:09 UTC
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** The description for the Great Plague Cleaver for plague marines says to subtract 2 from the to hit roll but should only subtract 1 from the to hit roll.

**Comment by GenWilhelm** [comment] 2017-10-20 16:13
Duplicate of #1642.

**Closed by GenWilhelm** 2017-10-20 16:13 UTC
