### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4962] opened 2019-04-23 17:37 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 1.03.00

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When it updated, it does not download new file. It says that all of my rosters Cannot be opened because it was created with the newer version of BattleScribe. When I download again it shows the exact same error.

**Comment by DrTobogganMD** [comment] 2019-04-23 18:05
Duplicate of #4959

**Comment by DrTobogganMD** [comment] 2019-04-23 18:06
This will be fixed with the new IOS version. Hopefully within 24 hours.

**Closed by DrTobogganMD** 2019-04-23 18:05 UTC
Labels: Area: BattleScribe app, Type: bug, ✔ Res: duplicate
