### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6909] opened 2020-03-21 07:45 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.10

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Imperium- Space Marines Chaplain Chapter Specific Litanies following Faith and Fury:
I do not see an option for the Ultramarines chapter litany "March for Macragge" for the Primaris Chaplain. This litany was made available through Faith and Fury. Thank you very much for your time.

**Comment by Mad-Spy** [comment] 2020-03-23 12:04
Duplicate of #6402. Chapter litanies are not being added at present to reduce logic in the file.

**Closed by Mad-Spy** 2020-03-23 12:04 UTC
