### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6635] opened 2020-01-26 19:09 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Lost building error when giving a sanctic power to infantry units for Grey Knights. It is listed as possible (which is good) and how many each unit can take of the sanctic powers (also great), but when I select one (for example, a strike squad and gate of infinity), the red eye error icon appears and says the maximum allowed for that unit is 0.

**Comment by Mad-Spy** [comment] 2020-01-27 08:55
Duplicate of #6633

**Closed by Mad-Spy** 2020-01-27 08:55 UTC
