### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4973] opened 2019-04-24 05:25 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Ever since the most recent update, I’ve been facing errors in making new lists. When creating a new roster, the only catalogue available is “Chaos - Renegade Knights v15.” This is the only faction shown—the rest are not present. It makes creating lists impossible. I’ve re-downloaded numerous times, and made sure the app was updated as well.

**Comment by williamcaw** [comment] 2019-04-24 06:30
Duplicate of #4959 . This is being investigated.

**Closed** 2019-04-24 07:21 UTC
Labels: ✔ Res: duplicate
