### ISSUE TITLE
[Anon] Bug report: Chaos - Thousand Sons.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2338] opened 2018-01-26 16:52 UTC
**File:** Chaos - Thousand Sons.catz

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** No

**Description:** Thousand Sons Predator has an incomplete stat line. It's missing all values except for a BS of 4 which is incorrect. The wound degradation table is right though.

**Comment by Kohato** [comment] 2018-01-26 17:51
Duplicate of #2337

**Closed by Kohato** 2018-01-26 17:51 UTC
Labels: Resolution - duplicate
