### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3771] opened 2018-10-27 06:12 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Heavy Burst Cannon on Riptide changed to Swiftstrike burstcannon in error.  FAQ/ERRATA was meant to change the Tiger Shark variants Heavy Burst cannon to swiftstrike only.  

The abuse was in players bringing FW Tiger sharks and using the Riptide HBC weapon profile to nasty effect.  Please change back Riptide HBC back to its original codex profile.

**Comment by GenWilhelm** [comment] 2018-10-27 17:03
Duplicate of #3766.

**Closed by GenWilhelm** 2018-10-27 17:03 UTC
