### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6845] opened 2020-03-05 19:17 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.18

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Blood Claws (without any weapons options) can no longer be dropped below 4. So for example, if I wanted to bring a minimum 5 man squad with a flamer, I can't, I have to bring an extra Blood Claw, making it a 6 man squad

**Comment by Mad-Spy** [comment] 2020-03-05 19:35
Duplicate of #6839

**Closed by Mad-Spy** 2020-03-05 19:35 UTC
