### ISSUE TITLE
Renegades and Heretics several things

### ISSUE THREAD

**Issue by 123hans** [BSData/wh40k#964] opened 2017-07-26 07:59 UTC
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by 123hans** [comment] 2017-07-26 08:19
Heavy Weapon Teams 3p to 6p because 2 models

Malefic Lord can only cast one time

Rogue Psyker Coven 20p to 100p because 5 models

Enforcer Ranged Weapons Bolt Pistol 0p to 1p and Plasma Pistol 7p to 5p

General: Ripper Claw is not a valid Melee Weapon from the Melee Weapon List, whereas Brutal Assault Weapon is missing sometimes

General: if frak or frag grenades are an option please autoinclude because free 

Renegade Militia Champion can take krak grenades

Ogryn Pack Master can take Frag grenades

Ogryn Brute are equipped with frag grenades

That's all for now. Haven't checked any vehicles or guns that are in the astra militarum section. Thanks!

Der Hans

**Comment by Penallegion** [comment] 2017-07-26 23:49
been doing generel tidying up, more generic choices and bug fixing, so far i have reached Renegade disciple squad, will continue when time allows

**Comment by 123hans** [comment] 2017-07-27 05:07
Thank you very much, especially for working on it in such a short time. I
might give the army list a full review within the next days, i just hope to
find the time aswell. Take care

Am 27.07.2017 01:49 schrieb "Penallegion" <notifications@github.com>:

been doing generel tidying up, more generic choices and bug fixing, so far
i have reached Renegade disciple squad, will continue when time allows

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BSData/wh40k/issues/964#issuecomment-318215763>, or mute
the thread

**Comment by spesselves** [comment] 2017-07-27 12:34
Just to tack on a few more things:

- [ ] Renegade Command Squad can remove Disciples but the points don't change. For example, it defaults at 4 models (24pts) and if you try to remove two, for instance to add a Weapons Team and get back up to the squad minimum, the Disciples selection remains at 24pts instead of subtracting the removed models, so with the Weapons team the final point total is 36 (+ whatever heavy weapon they take).

- [ ] Disciple Weapons Team for Renegade Command Squad are showing the wrong stats, they should have WS 3+, BS 3+ and a 5+ save like every other Disciple unit.

Additionally, and with due respect, I believe the above poster is incorrect. Renegade Heavy Weapons Squad's Renegade Weapon Teams are ONE model with TWO wounds. Not two models. As far as the datasheet is concerned anyway. For example, in other units' datasheets Weapons Teams are all created by any two models in the unit forming a Weapons Team and slightly altering Unit Composition, two 1W Infantry become a 2W Weapons Team model, hence a separate model entry for Weapons Teams in the Profiles list. However it would seem that for the purposes of unit purchasing they are counted separately towards the unit model total as is sort of traditional in 40k (see the Militia squad's requirement of 10 models before upgrading to a Weapons Team, obviously if the two Militia became one model they would drop to a squad size of 9 and disqualify their own existence). However, none of this applies to the Heavy Weapons Squad as written, as containing three 2W models is their default Unit Composition and Profile. 

Basically, they were never separate militiamen in a Heavy Weapons Squad, only one conjoined shooty blob. But note how the Wargear is very unclear about how many small arms they carry as well, as it says "Each model is armed with frag grenades and either _lasguns_ or _autoguns_." What is that plural supposed to mean there? Does each model have two...three...ten? Logic would dictate that they have two, one for each guy represented on the model itself, and due to 8th rules allowing models to "shoot all of them at the same target, or it can shoot each at a different enemy unit" a Renegade Weapons Team should, by logic, get two autogun shots and a heavy weapon shot each turn. But then this gets back to each model being a single 2W model on the datasheet. So maybe they only have one gun that they share and the plural was in reference to the fact that the unit is minimum 3 models? And if we circle back around to the problem of the "created" Weapons Teams in other units, since two regular models join up to become a Weapons Team "equipped with a weapon from the Renegades and Heretics Heavy Weapons list"...well since it never says they lose their previous Wargear, then these newly created Weapons Teams CERTAINLY have two lasguns or autoguns (or even pistols and CC weapons in some cases), right? Hahaha. Who knows...

Sincere apologies if that's a little off track, but I just wanted to highlight the fact that much of this is unclear and to be honest FW did a particularly bad job on clarity and QA in the AM Imperial Armour book. I really hope we get some more clean-ups by the end of summer, but until then I welcome any other takes/input on this or any other hilariously ambiguous issue in the rules.

**Comment by 123hans** [comment] 2017-07-27 13:17
Answer to weapon teams in short:

You are right. Only one model. My mistake.

Now the but:

I should be right :-) GW is wrong. I thought Imp teams consisted of 2
gunners as in last edition or as in todays squads as you pointed out. But
they don't. I mean not as written in the rules. Your next point concerning
multiple Lasguns is indeed funny. Good one.





Am 27.07.2017 14:34 schrieb "spesselves" <notifications@github.com>:

Just to tack on a few more things:

   -

   Renegade Command Squad can remove Disciples but the points don't change.
   For example, it defaults at 4 models (24pts) and if you try to remove two,
   for instance to add a Weapons Team and get back up to the squad minimum,
   the Disciples selection remains at 24pts instead of subtracting the removed
   models, so with the Weapons team the final point total is 36 (+ whatever
   heavy weapon they take).
   -

   Disciple Weapons Team for Renegade Command Squad are showing the wrong
   stats, they should have WS 3+, BS 3+ and a 5+ save like every other
   Disciple unit.

Additionally, and with due respect, I believe the above poster is
incorrect. Renegade Heavy Weapons Squad's Renegade Weapon Teams are ONE
model with TWO wounds. Not two models. As far as the datasheet is concerned
anyway. For example, in other units' datasheets Weapons Teams are all
created by any two models in the unit forming a Weapons Team and slightly
altering Unit Composition, two 1W Infantry become a 2W Weapons Team model,
hence a separate model entry for Weapons Teams in the Profiles list.
However it would seem that for the purposes of unit purchasing they are
counted separately towards the unit model total as is sort of traditional
in 40k (see the Militia squad's requirement of 10 models before upgrading
to a Weapons Team, obviously if the two Militia became one model they would
drop to a squad size of 9 and disqualify their own existence). However,
none of this applies to the Heavy Weapons Squad as written, as containing
three 2W models is their default Unit Composition and Profile.

Basically, they were never separate militiamen in a Heavy Weapons Squad,
only one conjoined shooty blob. But note how the Wargear is very unclear
about how many small arms they carry as well, as it says "Each model is
armed with frag grenades and either *lasguns* or *autoguns*." What is that
plural supposed to mean there? Does each model have two...three...ten?
Logic would dictate that they have two, one for each guy represented on the
model itself, and due to 8th rules allowing models to "shoot all of them at
the same target, or it can shoot each at a different enemy unit" a Renegade
Weapons Team should, by logic, get two autogun shots and a heavy weapon
shot each turn. But then this gets back to each model being a single 2W
model on the datasheet. So maybe they only have one gun that they share and
the plural was in reference to the fact that the unit is minimum 3 models?
And if we circle back around to the problem of the "created" Weapons Teams
in other units, since two regular models join up to become a Weapons Team
"equipped with a weapon from the Renegades and Heretics Heavy Weapons
list"...well since it never says they lose their previous Wargear, then
these newly created Weapons Teams CERTAINLY have two lasguns or autoguns
(or even pistols and CC weapons in some cases), right? Hahaha. Who knows...

Sincere apologies if that's a little off track, but I just wanted to
highlight the fact that much of this is unclear and to be honest FW did a
particularly bad job on clarity and QA in the AM Imperial Armour book. I
really hope we get some more clean-ups by the end of summer, but until then
I welcome any other takes/input on this or any other hilariously ambiguous
issue in the rules.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BSData/wh40k/issues/964#issuecomment-318348935>, or mute
the thread

**Comment by spesselves** [comment] 2017-07-27 13:22
> I should be right :-) GW is wrong. 

Oh I fully agree with you here. GW and FW have unfortunately made a big mess of certain things in an honest attempt to streamline them. Hopefully as we bring them to their attention they will continue to clean things up over the next year. In the meantime writing code for poorly written/ambiguous rules is...frustrating at best. ;)

**Comment by Penallegion** [comment] 2017-07-27 13:30
Both the command squad bugs are already fixed in next merge :)

**Comment by spesselves** [comment] 2017-07-27 13:31
You are the best!

**Comment by Penallegion** [comment] 2017-07-27 13:50
and as for the heavy weapons team, i can see where the logic comes from, and and yes the heavy weapon team is 1 base/unit selection but as i see it, it's comprised of two model, and yes the team cannot be destroyed before both wounds are gone, so i have made them as singular models comprising one mini unit, hope it makes sense ?

**Comment by spesselves** [comment] 2017-07-27 13:55
Eh, I have to say I still disagree. A big example why is morale. How would that work? If I have a squad that fails a morale check by one, RAW I should lose the whole 2W model. It isn't treated as two models in that case, so why would I treat it as two models for purchasing or anywhere else?

Our problem here is very bad/unclear rules writing by GW. But going with rules as written they are absolutely not comprised of two models for the HEAVY Weapons Squad. Argue whatever you want about Weapons Teams in other units, but the Heavy Support version is almost certainly one model with two wounds that costs (hilariously) 3 pts until errata.

**Comment by 123hans** [comment] 2017-07-27 13:56
Hi. If you haven't changed anything it should be fine. Apologies and thanks
again.

Am 27.07.2017 15:50 schrieb "Penallegion" <notifications@github.com>:

and as for the heavy weapons team, i can see where the logic comes from,
and and yes the heavy weapon team is 1 base/unit selection but as i see it,
it's comprised of two model, and yes the team cannot be destroyed before
both wounds are gone, so i have made them as singular models comprising one
mini unit, hope it makes sense ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BSData/wh40k/issues/964#issuecomment-318367959>, or mute
the thread

**Comment by spesselves** [comment] 2017-07-27 17:01
Guess I'm going back to pen and paper then...

**Comment by Penallegion** [comment] 2017-07-27 17:43
Well i have made extensive changes. So there is hope I have made it so you approve. Well and of course there is the chance for the opposite

**Comment by Penallegion** [comment] 2017-07-27 17:44
Well i have made extensive changes. So there is hope I have made it so you approve. Well and of course there is the chance for the opposite

**Comment by spesselves** [comment] 2017-07-27 17:49
So are you going to address my point or not? Otherwise you've just errata-ed something yourself which, personally though I may agree with your reasoning, I do not agree with as a solution. We should rely on GW to maintain their rules, this project should just be about displaying them in a handy and correct (as written) fashion.

**Comment by Penallegion** [comment] 2017-07-27 18:31
@spesselves 
So are you going to address my point or not? (yes i will)
Otherwise you've just errata-ed something yourself which, personally though I may agree with your reasoning, I do not agree with as a solution. (wouldn't dream of it, i make this as close to what i read as possible.)
We should rely on GW to maintain their rules, this project should just be about displaying them in a handy and correct (as written) fashion.(couldn't agree more, see above)

When that is said, i feel you on the morale issue, that kinda sold it :) will fix heavy so that shouldn't be an issue.
the cost i strongly disagree, you take 2 disciples (3 p each) and merge to 1 heavy weapon team (free) Heavy weapon team = 6 point

As for equipment on on the team, i am for the not fucking things more up, leave it as is untill FW comes with a clear purpose on what they intend with the unit.

And one more thing, noone should apologise for making tickets or argumenting for their point of view, so don't sweat it :)

**Comment by Penallegion** [comment] 2017-07-27 18:44
- [ ] Rework Heavy weapon team composition

**Comment by spesselves** [comment] 2017-07-27 18:48
Thanks for addressing my concerns, sorry if I was a bit testy. The Heavy Weapons Squad is pretty cut and dry as written, if bafflingly cheap. As for the "created" models (be they militia, command or disciple), you are correct, it is an absolute mess as written and I do have an email in to Forge World on this matter, let's see how long (if ever) it takes them to respond and hopefully clarify. But yeah, my standard logic is also that you simply combine the costs of the models who are "forming" the Weapons Team and add the points for the Heavy Weapon selection they are taking. But then (esp. for Militia) with the new team counting as 1 model, now your are down to 9 models and seemingly would have to buy one more regular Militia model to get back up to the minimum model requirement. I agree that this probably isn't what they intended, but if so they really need to clarify...

blerg

**Comment by 123hans** [comment] 2017-07-28 06:08
Hi again. First of all: no sweating, don't worry, be happy.

Btw I never meant that a weapon team consist's of two models. Inaccurately
written by me. I simply thought that it costs the points of two models. I
thought that were the rules. Well. And i think that should be rules, not
just for renegades, what we all seem to agree on. Further thoughts are
irrelevant although being appropriate at the same time.

Furthermore I would like finish this discussion and proceed with making
battlescribe conform with the (partly flawed) rules gw is giving us. 8th
edition has less problems than the previous one anyways and without
battlescribe I would have bigger issues writing lists.   Have a nice
weekend.






Am 27.07.2017 20:48 schrieb "spesselves" <notifications@github.com>:

Thanks for addressing my concerns, sorry if I was a bit testy. The Heavy
Weapons Squad is pretty cut and dry as written, if bafflingly cheap. As for
the "created" models (be they militia, command or disciple), you are
correct, it is an absolute mess as written and I do have an email in to
Forge World on this matter, let's see how long (if ever) it takes them to
respond and hopefully clarify. But yeah, my standard logic is also that you
simply combine the costs of the models who are "forming" the Weapons Team
and add the points for the Heavy Weapon selection they are taking. But then
(esp. for Militia) with the new team counting as 1 model, now your are down
to 9 models and seemingly would have to buy one more regular Militia model
to get back up to the minimum model requirement. I agree that this probably
isn't what they intended, but if so they really need to clarify...

blerg

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BSData/wh40k/issues/964#issuecomment-318452703>, or mute
the thread

**Comment by Penallegion** [comment] 2017-08-02 14:36
hi both of you, have you had time to test out the army building since last update ? i am keen on knowing if i got all the bugs we talked about, and to know if i have done it correct in your opinion

**Comment by 123hans** [comment] 2017-08-02 14:47
Hi,

Well. I like the weapon teams now. I would play them this way and pay for
two crewmen. But it is not RAW. Besides work and my child hindered me from
doing the important stuff :-)

Take care

Am 02.08.2017 16:36 schrieb "Penallegion" <notifications@github.com>:

hi both of you, have you had time to test out the army building since last
update ? i am keen on knowing if i got all the bugs we talked about, and to
know if i have done it correct in your opinion

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BSData/wh40k/issues/964#issuecomment-319692119>, or mute
the thread

**Comment by Penallegion** [comment] 2017-08-02 15:02
well if i make the 2 X disciples to an upgrade, they won't count towards model count and i change the Weapon team option to a upgrade, you still have to pay for the 2 X disciples (RAW) and it only takes 1 model count (RAW) would that work ?
well kids wife and vacation also had quite a big impact here 🗡

**Comment by spesselves** [comment] 2017-08-02 15:10
Again I think the Heavy Weapons Teams (the Heavy Support choice) needs to go back to its ridiculously cheap price. The points per model are very clearly spelled out by GW and each team is very clearly ONE MODEL on the profile. This is RAW, very clear, and something we shouldn't change until GW erratas it.

As for the Weapons teams in Militia, Command and Disciple units...well that is the true confusion. I believe RAW when the units combine you should pay for both...but after becoming one model (as reflected in the profile) they then only count as one model. So to meet squad minimums you will need an extra basic model in most cases. Again...this is something GW needs to clarify and is definitely open to discussion. But RAW this is how I believe it should work.

The Renegade Heavy Weapons Squad I am pretty firm on though. 3 pts per model...as silly as that is...is the current cost as relflected in the rules we have at hand. Period.

**Comment by 123hans** [comment] 2017-08-02 15:17
I was taking about the heavy support weapon teams. I think they are meant
like the way they are now. Those others within squads are a different
matter and are surely also meant to count to the squad size as two.

That is how the casual and fun gamer would play it with friends I think.
And IMHO Tournament players and power gamers should not rely on anything
but the books and should also die a slow and painful death :-)

Am 02.08.2017 17:02 schrieb "Penallegion" <notifications@github.com>:

**Comment by Penallegion** [comment] 2017-08-02 15:25
@spesselves OH crap, haven't even gotten to the Heavy Weapons Teams (the Heavy Support choice) yet :)
i am still trying to get the best of the very complex Militia, Command and Disciple units, as they are pissing me off. but will reach Heavy weapon teams during this week i hope

**Comment by spesselves** [comment] 2017-08-02 15:27
No problem man...you are doing all the heavy lifting. Take your time and thanks a bunch.

**Comment by Penallegion** [comment] 2017-08-02 15:30
> As for the Weapons teams in Militia, Command and Disciple units...well that is the true confusion. I believe RAW when the units combine you should pay for both...but after becoming one model (as reflected in the profile) they then only count as one model. So to meet squad minimums you will need an extra basic model in most cases. Again...this is something GW needs to clarify and is definitely open to discussion. But RAW this is how I believe it should work. > This is how i have done them, price of 12, and count as 1 (in the version i am working on now)

@123hans 

> I was taking about the heavy support weapon teams. I think they are meant
like the way they are now. Those others within squads are a different
matter and are surely also meant to count to the squad size as two. > 
I think they should count as 1 model, since its one 2 wound profile in the datacard, but i think we all agree its the cost of 2

**Comment by Penallegion** [comment] 2017-08-02 17:42
Well the wife fell a sleep tugging in the kids, so got some extra time on my hand, have corrected Militia, Command and Disciple so they keep up with BSData guidelines, and have corrected HW-Team so they are as close to raw as i can get them

**Comment by Penallegion** [comment] 2017-08-03 16:36
So the changes from yesterday is online if you have the time for a review

**Comment by 123hans** [comment] 2017-08-03 16:54
Hi. Just two short things. Renegade Militia: can't be set to lower than 9
models plus champion atm, even if a weapon team is added. It works on
disciples btw.
Heavy support weapon teams are still at 6 points though spesselves pointed
out 3 points would be RAW.
Thanks for your efforts.
Take care

Am 03.08.2017 18:36 schrieb "Penallegion" <notifications@github.com>:

So the changes from yesterday is online if you have the time for a review

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/BSData/wh40k/issues/964#issuecomment-320023363>, or mute
the thread

**Comment by spesselves** [comment] 2017-08-03 16:58
Oh I don't think penallegion meant the changes are live...they are up on git

**Comment by 123hans** [comment] 2017-08-03 17:08
Good point

Am 03.08.2017 18:58 schrieb "spesselves" <notifications@github.com>:

**Comment by Penallegion** [comment] 2017-08-03 17:19
i actually meant it was live, are testing with my Ipad, and enforcer change and HW-Squad works as intended, i get HW-Squad at 3 points, i don't know why the hell militia havent synced

**Comment by Penallegion** [comment] 2017-08-03 17:23
it hasn't changed the command squad either.... F#¤"

**Comment by 123hans** [comment] 2017-08-03 18:55
I am a bit confused now. Live means I refresh and have it. Or not? What is
supposed to be wrong with the command squad? Besides that it doesn't show
an error if you don't take a heavy weapon for the weapon team I can't find
anything.

I found something else but please answer before i continue.

Take care

Am 03.08.2017 19:23 schrieb "Penallegion" <notifications@github.com>:

**Comment by Penallegion** [comment] 2017-08-03 19:12
yeah sorry i wrote before i checked, didnt quite catch i hasn't gone live with last update, so never mind that comment, sorry mate, the update should catch on next update

**Comment by Penallegion** [comment] 2017-08-03 19:14
it's still in V. 1.0.41 the latest changes should hit on 1.0.42

**Comment by spesselves** [comment] 2017-08-03 22:19
The command squad and Disciple squad mins are messed up. Command squad is claiming a 5 model min...should be 4 (so four dudes or three dudes and one weapons team based on how we are interpreting it). Actually disciples seem maybe okay, their min is 5, but it appears maybe the sergeant or weapons team isn't counting towards the total?

**Comment by spesselves** [comment] 2017-08-03 22:22
JK the disciple squad error report says min 4...that is definitely not right. The model counts are not adding up correctly for either unit though, that is for sure.

Heavy Weapons Squad is good now though.

**Comment by 123hans** [comment] 2017-08-04 05:20
I think it counts right but the message says minimum 4 for disciple squad,
when 5 models are in no error. Command counts and displays right... so we
have different versions? Having trouble finding a version's number like
1.0.4xxx anyways. Can you help me? Is there a under Dev section for the
catalogues? Maybe I find with more coffee by myself.

Thank you

Am 04.08.2017 00:22 schrieb "spesselves" <notifications@github.com>:

JK the disciple squad error report says min 4...that is definitely not
right. The model counts are not adding up correctly for either unit though,
that is for sure.

Heavy Weapons Squad is good now though.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/BSData/wh40k/issues/964#issuecomment-320105888>, or mute
the thread

**Comment by spesselves** [comment] 2017-08-04 11:32
I am on v11 of the Renegades data and Command Squad is absolutely not correct. See attached, it very obviously says minimum 5 and a Command Squad is min 4 as per IA AM.
![image](https://user-images.githubusercontent.com/13341215/28966773-006b3ddc-78e6-11e7-90ac-90b5a162afa8.png)
It does appear that the Weapons Team is counting correctly as one model though, see:
![image](https://user-images.githubusercontent.com/13341215/28966845-6216c7f4-78e6-11e7-8552-e58574f5f6b7.png)
(It still erroneously wants 5 models min, but 3 Disciples and a Weapons Team are counting as 4...we are close!)

Also the Disciple Squad does seem to be working as intended after all. I realized the min counts only the regular guys and excludes the Sergeant, so 1 Sergeant, 3 Disciples and a Weapons team correctly meet the unit min of 5 models as per IA AM. Carry on.
![image](https://user-images.githubusercontent.com/13341215/28966964-f5c6e74a-78e6-11e7-8ecf-457cd0d37967.png)

**Comment by 123hans** [comment] 2017-08-04 12:34
Hi folks,

Well. Pretty sure yesterday latest one was 10. Anyways. In 10 it worked. In
11 not. True.


Other litte things: renegade commander also starts with a brutal assault
weapon

Regular Militia (not champion) have frag grenades.

Mutants all have frag grenades though the weapon profile is there, just not
shown under equipment. Maybe also autoinclude an autopistol for the champ
(or lapistol - but those fancy pew pew's are better with loyalist traitors
imho).

General question, but this something for later: the chaos spawn has two
special rules. Fearsome and mutations. One is shown within its profile, one
below. Do you want me to notice such things? Sure general rules like
uncertain worth and common ones like fanatic should not be explained in
each profile.

Have a nice weekend

Am 04.08.2017 1:32 PM schrieb "spesselves" <notifications@github.com>:

**Comment by Penallegion** [comment] 2017-08-07 19:23
Yeah i totally fucked up in command unit, have corrected to 4 inititial models, also have included sergent in disciple squad as to give more intuitive building, i have also reworked marauders to  comply with this way of building, 

- [ ] Other litte things: renegade commander also starts with a brutal assault
weapon

- [ ] Regular Militia (not champion) have frag grenades.

- [ ] Mutants all have frag grenades though the weapon profile is there, just not
shown under equipment. Maybe also autoinclude an autopistol for the champ
(or lapistol - but those fancy pew pew's are better with loyalist traitors
imho).

General question, but this something for later: the chaos spawn has two
special rules. Fearsome and mutations. One is shown within its profile, one
below. Do you want me to notice such things? Sure general rules like
uncertain worth and common ones like fanatic should not be explained in
each profile.   (Yes you notice it all, comment and we build the best Renegade CAT there ever was)

**Comment by Penallegion** [comment] 2017-08-07 19:50
okay, done for the evening i think, should have corrected all of the above, if anything is missed let me know and we will have a go in the near future 💃

**Comment by 123hans** [comment] 2017-08-07 20:03
You are the best. Again.

About those little things like the spawn ability. I used to work at a
software company in product development (though I am not a programmer) so I
kinda know what these "errors" are. They are the last percent that make up
90% of the time and sadly noone will ever notice it. so I won't bother you,
but I will write them down somewhere. When time is right and you just
thought you had time for your family again and thought you could live a
happy life I will send you the list ;-)

Take care

Am 07.08.2017 21:50 schrieb "Penallegion" <notifications@github.com>:

okay, done for the evening i think, should have corrected all of the above,
if anything is missed let me know and we will have a go in the near future
💃

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/BSData/wh40k/issues/964#issuecomment-320762343>, or mute
the thread

**Comment by FarseerVeraenthis** [comment] 2017-08-22 11:49
@Penallegion commented all issues are fixed, so I'm closing this report.

**Closed by FarseerVeraenthis** 2017-08-22 11:49 UTC
Labels: Bug - choice, Bug - cost
