### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4980] opened 2019-04-24 11:54 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I cant open any catalog besides chaos- renegade Knights.

**Comment by Thairne** [comment] 2019-04-24 12:17
Duplicate of #4959

**Closed by Thairne** 2019-04-24 12:17 UTC
Labels: Area: BattleScribe app, Type: bug, ✔ Res: duplicate
