### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4547] opened 2019-02-01 06:02 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** I know this may not be very descriptive but; whenever I have tried to view my roster by tapping the eye icon it loads up as a single page. I have tried redownload the files needed for my army and remaking the roster but still ended up with the blank page when attempting to view it. In the case it is needed i am using the "Warhammer 40,000 v1.2.12"

**Comment by Mad-Spy** [comment] 2019-02-01 08:08
Duplicate of #4541

**Closed by Mad-Spy** 2019-02-01 08:08 UTC
