### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1593] opened 2017-10-08 05:02 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Elites is missing tech-priest engineer. This sentence is to get to 50 characters.

**Comment by GenWilhelm** [comment] 2017-10-08 12:18
Duplicate of #1589.

**Closed by GenWilhelm** 2017-10-08 12:18 UTC
Labels: Bug - choice, Imperium - Astra Militarum, Resolution - duplicate
