### ISSUE TITLE
[Anon] Bug report: Orks.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4484] opened 2019-01-20 04:33 UTC
**File:** Orks.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** when selecting the Megatrakk Scrapjet as 3 seperate fast attack slots it miss adds the power Level it should total 15 for 5 each not 16

**Comment by Mad-Spy** [comment] 2019-01-20 07:20
Duplicate of #4483

**Closed by Mad-Spy** 2019-01-20 07:20 UTC
