### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5946] opened 2019-11-08 15:30 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Master of the Trifold Path strategem is not available for Raven Guard-selected Chapters in the Space Marines data. Therefore, when you choose two Warlord Traits for your Warlord, it shows an error.

**Comment by Mad-Spy** [comment] 2019-11-08 15:32
Duplicate of #5712

**Closed by Mad-Spy** 2019-11-08 15:32 UTC
