### ISSUE TITLE
Field Commander stratagem not working for Adeptus Mechanicus

### ISSUE THREAD

**Issue by Pomguo** [BSData/wh40k#6366] opened 2019-12-13 10:01 UTC
**File/Catalogue:** Imperium - Adeptus Mechanicus.cat

**BattleScribe version:** 2.03.

**Platform:** iOS

**Dropbox:** No

**Description:** The "Field Commander" stratagem is selectable in No Force Org, and does -1CP as intended, but does not unlock the option to give a Character the Specialist Detachment Warlord Trait as it is meant to. I have found this issue to exist for both Specialist Detachments adepts mechanicus has the option to choose, so I assume the issue is with the Field Commander stratagem.

**Comment by Thairne** [comment] 2019-12-13 10:30
duplicate of #6074

**Closed by Thairne** 2019-12-13 10:30 UTC
Labels: Area: BattleScribe app, Area: selections, Type: bug, ✔ Res: duplicate, 💾 Cat: Imperium - Adeptus Mechanicus
