### ISSUE TITLE
Space Marines - Terminator Assault Squad has incorrect Power Level costs

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#5483] opened 2019-08-22 22:07 UTC
**File/Catalogue:** Imperium - Space Marines v110

**BattleScribe version:** 2.03.00

**Platform:** Windows

**Dropbox:** No

**Description:** Terminator Assault Squad has the following incorrect power levels:

- 5 models - Currently 12 Power Level; should be 9 Power Level.
- 6-10 models - Currently 24 Power Level; should be 18 Power Level.

**Comment by WindstormSCR** [comment] 2019-08-22 22:08
Duplicate of #5477

**Closed by WindstormSCR** 2019-08-22 22:08 UTC
