### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4756] opened 2019-03-19 11:52 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.17

**Platform:** Mac

**Dropbox:** No

**Description:** Master of Possession unit entry is good now that he can take marks, Greater possessed has his profile but is still missing the option to take marks.

**Comment by Mad-Spy** [comment] 2019-03-19 12:49
Fixed in the next release. Duplicate of #4752

**Closed by Mad-Spy** 2019-03-19 12:49 UTC
