### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4114] opened 2018-12-15 22:00 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** On Defiliers in Heavy Support, the price of a Reaper Autocannon is 15 points when it should be 10 points as per Chapter Approved 2018.

**Comment by Kohato** [comment] 2018-12-16 04:45
Duplicate of #4078

**Closed by Kohato** 2018-12-16 04:45 UTC
