### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3773] opened 2018-10-27 18:42 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 1.01.68

**Platform:** Android

**Dropbox:** No

**Description:** T'au Empire v29

The Heavy Burst Cannon is changed to Swiftstrike Cannon and had a total cost of 55 points instead of 35 points.
I cant find at any webside an information about this nerf.
Please change it to the old costs and name.

Many thanks
Mathias

**Comment by GenWilhelm** [comment] 2018-10-27 18:58
Duplicate of #3766.

**Closed by GenWilhelm** 2018-10-27 18:58 UTC
