### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6818] opened 2020-02-29 13:58 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.18

**Platform:** Android

**Dropbox:** No

**Description:** Blood claw troop choices are not allowing 5man units with special weapons. This is because when you add 1z special weapons model or 1x plasma pistol model, it won't allow you to reduce the number of basic blood claws below x4.

For grey hunters, I am able to reduce the basic models to x2, allowing me to select 1x special weapons and 1x plasma pistol. Bringing the unit size to 5.

**Comment by Mad-Spy** [comment] 2020-03-01 19:10
Duplicate of #6725

**Closed by Mad-Spy** 2020-03-01 19:10 UTC
Labels: 💾 Cat: Imperium - Space Wolves
