### ISSUE TITLE
Space Marines: Heavy Plasma Incinerator cost incorrect

### ISSUE THREAD

**Issue by Aldran** [BSData/wh40k#1180] opened 2017-08-11 02:24 UTC
Space Marines v27

BattleScribe version: 2.01.

Platform: Windows/Android/Linux

Description: Hellbaster Squad equipment cost for Heavy Plasma Incinerator is wrong. The weapons have an initial cost of 36 points + 17 per member in the squad. In the codex it only says that it should cost 17 per member in the squad.

Thanks

**Comment by ilaunchbury** [comment] 2017-08-11 07:23
Duplicate of #1151

**Closed by ilaunchbury** 2017-08-11 07:23 UTC
Labels: Bug - cost
