### ISSUE TITLE
Infiltrator squad members are counting across squads

### ISSUE THREAD

**Issue by hagamemnon** [BSData/wh40k#4900] opened 2019-04-09 04:14 UTC
**File/Catalogue: Imperium - Dark Angels** 

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** Yes

**Description:** Infiltrator locked at 11PL base cost - checked data file and it appears to be properly coded (Base 5, increment by 6 once exceeds 5 parent models).

**Comment by Thairne** [comment] 2019-04-09 07:26
Works for me, infiltrators got copied from SM cat.
Does the issue persist there as well?

**Comment by Mad-Spy** [comment] 2019-04-09 10:06
It's fine in the SM catalogue. I think people get confused because you can't take 5 models if one of them is a Helix Adept. You *must* take a minimum of 6 models to get an Adept, which would cost 11PL.

**Comment by hagamemnon** [comment] 2019-04-09 15:15
Closed as others are not able to reproduce

**Comment by Mad-Spy** [comment] 2019-04-09 15:34
Sorry all, looks like this one is my fault from the original implementation. The PL increment should be by squad, not by Parent. The below is the corrected version. It'll need to go into all the catalogues.

![image](https://user-images.githubusercontent.com/29306451/55813801-56b19500-5ae5-11e9-95c5-07a567eb6043.png)

**Comment by Mad-Spy** [comment] 2019-04-10 06:42
@hagamemnon, no worries. It was the missing link of "this happens when I add more units to a list" which tipped me off.

**Comment by Thairne** [comment] 2019-04-11 07:24
Oh. So it happens when 2 squads are selected. Yeah, that effing shared box.... Blessing and curse, the two-faced checker, the causer of bugs.

**Comment by alphalas** [comment] 2019-04-13 13:22
Fixed in BA. Also added PHOBOS to Reivers

**Closed** 2019-04-17 20:59 UTC
Labels: Area: selections, 💾 Cat: Imperium - Blood Angels, 💾 Cat: Imperium - Dark Angels, 💾 Cat: Imperium - Space Marines, 💾 Cat: Imperium - Space Wolves
