### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4984] opened 2019-04-24 18:24 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The only data that comes up when I try to add a new force is renegade knights

**Comment by williamcaw** [comment] 2019-04-24 20:43
Just relax. Duplicate of #4959.

**Closed** 2019-04-24 21:55 UTC
