### ISSUE TITLE
[Anon] Bug report: Imperium - Dark Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1069] opened 2017-08-01 15:44 UTC
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** In selecting Devastator Marines, the option to include up to 4 heavy weapons has selections of gear with the correct cost, but just for the weapon itself. The problem is that this also counts as a Marine with regard to the Marine count. For example, the list includes a sergeant and 4 marines by default, and adding 4 heavy bolters (40 points) now claims you have 8 marines, preventing you from bringing the 5 additional Marines allowed without a warning. If you remove the 4 normal Marines, and select 4 heavy bolters, there are no warnings, but you are no longer paying the 52 points for the Marines, only the weapon costs. Adding 13 points to the cost of each weapon option could fix the issue, as each heavy weapon becomes tied with the Marine cost.

**Comment by GenWilhelm** [comment] 2017-08-02 09:29
Duplicate of #907.

**Closed by GenWilhelm** 2017-08-02 09:29 UTC
