### ISSUE TITLE
[Anon] Bug report: Chaos - Daemons.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#823] opened 2017-07-16 16:20 UTC
**File:** Chaos - Daemons.catz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** No

**Description:** No need to pay extra for the Exalted Flamer on a Burning Chariot.  The 100 points "Includes wargear".

**Comment by ilaunchbury** [comment] 2017-07-16 16:53
This is a duplicate of #822. It will be fixed in the next release.

**Closed by ilaunchbury** 2017-07-16 16:53 UTC
Labels: Bug - cost, Resolution - duplicate
