### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3876] opened 2018-11-12 05:19 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.15

**Platform:** Mac

**Dropbox:** No

**Description:** All "biker" units have the infantry keyword when they should not.

**Comment by Mad-Spy** [comment] 2018-11-12 07:32
Duplicate of #3865

**Closed by Mad-Spy** 2018-11-12 07:32 UTC
