### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4903] opened 2019-04-10 00:37 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.24

**Platform:** Android

**Dropbox:** No

**Description:** Chosen Champions are listed as being unable to select only from the Champion Equipment list. The codex allows the chosen to take one item from the Melee weapons list -or- take from the champion equipment list, which is an important distinction as one selection from the melee list allows him to take a Thunder Hammer.

**Comment by Mad-Spy** [comment] 2019-04-10 06:04
Duplicate of #4863

**Closed by Mad-Spy** 2019-04-10 06:04 UTC
