### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4968] opened 2019-04-23 22:02 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** My BattleScribe is only showing Renegade Knights on the forces page

**Comment by WindstormSCR** [comment] 2019-04-23 22:13
Duplicate of #4959

**Closed by WindstormSCR** 2019-04-23 22:13 UTC
