### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5007] opened 2019-04-25 13:18 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.92.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** There are no more army lists. Only Chaos Renegade Knights to select from

**Comment by williamcaw** [comment] 2019-04-25 14:05
Pleas update the app

**Comment by WindstormSCR** [comment] 2019-04-25 14:08
duplicate of #4959

**Closed by WindstormSCR** 2019-04-25 14:08 UTC
