### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2720] opened 2018-03-25 19:40 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** Error for Army Roster. It says: "has 1 too many selections of Aun´Shi (maximum 0).
Vior´la sept is given in Detachment.
Testet with all detachment when hes selectet HQ.

**Comment by amis92** [comment] 2018-03-26 00:39
Duplicate of #2695

**Closed by amis92** 2018-03-26 00:39 UTC
Labels: Bug - validation, Resolution - duplicate, T'au
