### ISSUE TITLE
Imperium - Adeptus Custodes: Vexillus Praetor Storm shield cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4161] opened 2018-12-16 18:26 UTC
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.02.15

**Platform:** Mac

**Dropbox:** Yes

**Description:** The storm shield (character) for a Vexillus Praetor should be 10 points following Chapter Approved 2018, but is currently 15 points.

**Comment by Mad-Spy** [comment] 2018-12-16 19:35
Duplicate of #4144

**Closed by Mad-Spy** 2018-12-16 19:35 UTC
Labels: Area: costs, Type: bug, 💾 Cat: Imperium  - Adeptus Custodes
