### ISSUE TITLE
Aeldari - Harlequins: Masque Warlord Trait and Relic Visibility

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6032] opened 2019-11-27 09:07 UTC
**File:** Aeldari - Harlequins.catz

**BattleScribe version:** 2.03.05

**Platform:** Windows

**Dropbox:** No

**Description:** I try to put together a Harlequin Detachment. When I start the Detachment (I tried with Vanguard, Outrider and Battalion Detachment) it starts with the Masque Form: None (Mixed Detachment). Now I select a HQ unit (Troupe Master or Shadowseer, it does not matter which one) and make it my warlord. At this point I have the option to select every single Enigma of the Black Library option as well as every Warlord Trait (Non-Masque specifics as well as Masque-specifics). Sofar so good. But when I change the Masque Form to (lets say) Soaring Spite, I no longer have the option to choose the Soring Spite Warlord Trait or Enigma of the Black Library. For Warlord Traits I can only choose between the six non-Masque specific Traits and for Enigmas I only have the option between "The Laughing God´s Eye", "The Mask of Secrets", "The Starmist Raiment" and "The Suit of Hidden Knives". In addition: when I select a Masque specific Enigma/Warlord Trait when the detachment is stil a "None" Masque form and I afterwards switch to (for example) The Soaring Spite Masque form I then get the following error message:

"Troupe Master cannot have any selections of Faolchu`s Talon (hidden)"
"Troupe Master cannot have any selections of Soaring Spite: Skystrider (hidden)"

**Comment by corrinavatan** [comment] 2019-11-27 09:40
Replicated on BS. 2.03.16, Harlequins v. 33 list, battalion.

Only way to put the relic on a character is to set the detachment to "None", then assign one of ANY of the Masque-specific relics to a character after designating a warlord.  If I set the detachment to a specific Masque, they are simply not listed.

Switching the detachment to the correct Masque after assigning the relic causes an error, though it will still be "equipped"

**Comment by FarseerVeraenthis** [comment] 2019-11-27 22:14
duplicate of #5986

**Closed by FarseerVeraenthis** 2019-11-27 22:14 UTC
Labels: Area: selections, Type: bug, 💾 Cat: Aeldari - Harlequins
