### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5340] opened 2019-07-27 05:14 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Astra Militarum Tank Commander HQ choice must take all available cannon types and pay the points for them as well, older entries will create errors that not enough choices have been taken since they only have one cannon and newly created entries will force the user to create a 7 cannon over-pointed Tank Commander.  Though if you could pay 275 points for a Leman Russ with every main gun that would be cool.

**Comment by GenWilhelm** [comment] 2019-07-27 10:53
Duplicate of #5338

**Closed by GenWilhelm** 2019-07-27 10:53 UTC
