### ISSUE TITLE
[Anon] Bug report: Orks.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5542] opened 2019-08-26 04:23 UTC
**File:** Orks.catz

**BattleScribe version:** 2.03.00

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Correction of my previous bug report - ork hq regular “warboss” is not missing. I' ve found this unit in “uncategorisied” instead of “hq”

**Comment by Mad-Spy** [comment] 2019-08-26 05:05
Duplicate of #5496

**Closed by Mad-Spy** 2019-08-26 05:05 UTC
