### ISSUE TITLE
[Anon] Bug report: Tyranids.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1756] opened 2017-11-14 20:28 UTC
**File:** Tyranids.catz

**BattleScribe version:** 2.01.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Genestealers should be able to have one model with flesh hooks AND/or one model with acid maw for every 4 models in unit.
In my unit of 14, it allows me to take 3 acid maws but I cannot also add a flesh hook without getting a warning, although the codex states "and/or"

**Comment by GenWilhelm** [comment] 2017-11-14 21:32
Duplicate of #1754.

**Closed by GenWilhelm** 2017-11-14 21:32 UTC
