### ISSUE TITLE
[Anon] Bug report: Imperium - Grey Knights.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6636] opened 2020-01-26 20:59 UTC
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.03.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Get an error when adding psychic powers to non-character Grey Knight units. The error indicates they that the maximum numbers of power they can know is 0 when it should be 1.

**Comment by Mad-Spy** [comment] 2020-01-27 08:55
Duplicate of #6633

**Closed by Mad-Spy** 2020-01-27 08:55 UTC
