### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5689] opened 2019-09-23 14:57 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.01

**Platform:** Windows

**Dropbox:** Yes

**Description:** The new Space marine codex updated the weapon profile for "Icarius Rocket Pod" to damage 2. Current data file has the old statistics everywhere I can find it as an option (Repulsor, Repulsor Executioner, Redemptor Dreadnought)

**Comment by Mad-Spy** [comment] 2019-09-24 05:42
Duplicate of #5589

**Closed by Mad-Spy** 2019-09-24 05:42 UTC
