### ISSUE TITLE
[Anon] Bug report: Tyranids.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2777] opened 2018-04-05 20:24 UTC
**File:** Tyranids.catz

**BattleScribe version:** 2.01.10

**Platform:** Windows

**Dropbox:** No

**Description:** Take 4 zoanthrobes and click second Psy power and the Unit gets deleted from Rooster.
take carnifex and take any morph and change it to other and unit is deleted.
take Tyranofex and take any other weapon option and the unit is deleted.
and much more units with this error

**Comment by Kohato** [comment] 2018-04-05 20:33
Duplicate of #2774 - Known bug, no fix at this time.

**Closed by Kohato** 2018-04-05 20:33 UTC
Labels: Bug - choice, Problem - BattleScribe bug, Resolution - duplicate
