### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#803] opened 2017-07-14 20:10 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** Yes

**Description:** In matched play, we are able to use units with less miniatures than minimun as it shows  in their profiles, so we can use units of 1 bloodletter and it's (at least at the moment) legal. The price is the same when you play with power levels, but not in matched or competitive game.

**Comment by GenWilhelm** [comment] 2017-07-14 20:54
Duplicate of #780

**Closed by GenWilhelm** 2017-07-14 20:54 UTC
