### ISSUE TITLE
[Anon] Bug report: Orks.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3441] opened 2018-08-25 09:57 UTC
**File:** Orks.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** It says that a commander in xv86 coldstar battlesuit must have a minimum of 1 mjssile pods. Thats wrong. You can choose to change it with another weapon from the list.

**Comment by GenWilhelm** [comment] 2018-08-25 12:49
Duplicate of #3442.

**Closed by GenWilhelm** 2018-08-25 12:49 UTC
