### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4049] opened 2018-12-15 10:51 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.15

**Platform:** Mac

**Dropbox:** No

**Description:** Points cost for Reaper Autocannon on Helbrute should be 10, not 15.

**Comment by GenWilhelm** [comment] 2018-12-15 13:51
Duplicate of #4032

**Closed by GenWilhelm** 2018-12-15 13:51 UTC
