### ISSUE TITLE
[Anon] Bug report: Chaos - Daemons.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4131] opened 2018-12-16 01:39 UTC
**File:** Chaos - Daemons.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Be'lakor is showing as 280 points instead of the updated 240 points from Chapter Approved. Thanks for all your time and hardwork!

**Comment by Kohato** [comment] 2018-12-16 04:45
Duplicate of #4079

**Closed by Kohato** 2018-12-16 04:45 UTC
Labels: Area: costs, Type: bug, ✔ Res: duplicate, 💾 Cat: Chaos - Daemons
