### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4158] opened 2018-12-16 17:00 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Chaos spawn were updated to be 25 points in chapter approved, but are still 33 points in battlescribe

**Comment by Mad-Spy** [comment] 2018-12-16 17:03
Duplicate of #4078

**Closed by Mad-Spy** 2018-12-16 17:03 UTC
