### ISSUE TITLE
[Anon] Bug report: Imperium - Deathwatch.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6219] opened 2019-12-10 19:33 UTC
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** Deathwatch intercessor weapons point vaiue not update with the new CA2019

**Comment by Mad-Spy** [comment] 2019-12-10 22:44
Duplicate of #6140

**Closed by Mad-Spy** 2019-12-10 22:44 UTC
