### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4985] opened 2019-04-24 20:10 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When starting a new 40k list the only faction that can be chosen is renegade knights. There are no other factions available.

**Comment by williamcaw** [comment] 2019-04-24 20:44
Duplicate of #4959.

**Closed** 2019-04-24 21:55 UTC
