### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1971] opened 2017-12-07 15:21 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.07

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Please reduce the points of the space wolves thunderwolf Calvary pack leader’s storm shield from 15 to 10 points.

**Comment by ilaunchbury** [comment] 2017-12-07 15:27
Duplicate of #1967. Fixed in next release.

**Closed by ilaunchbury** 2017-12-07 15:27 UTC
