### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6931] opened 2020-03-30 07:35 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.20

**Platform:** Android

**Dropbox:** No

**Description:** Notte really a bug, just the mar h of the ancients stratagems missing to upgrade dreadnoughts to character and give them a warlord trait. Any way to add it?

**Comment by Mad-Spy** [comment] 2020-03-30 09:54
Duplicate of #5702

**Closed by Mad-Spy** 2020-03-30 09:54 UTC
