### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4842] opened 2019-04-02 15:41 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.21

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** New CSM Havocs - missile launcher profile not showing when missile launcher is selected as an option

**Comment by GenWilhelm** [comment] 2019-04-02 18:17
Duplicate of #4841

**Closed by GenWilhelm** 2019-04-02 18:17 UTC
