### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Astra Telepathica.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6011] opened 2019-11-23 08:45 UTC
**File:** Imperium - Adeptus Astra Telepathica.catz

**BattleScribe version:** 2.03.14

**Platform:** Android

**Dropbox:** No

**Description:** Hi! The Warlord traits does not exist in the files. When you select for example, a shield captain as Warlord you dont get any warlord traits to select.

**Comment by Dunamis55** [comment] 2019-11-23 23:47
Confirmed on PC that the Warlord traits aren't showing for any of the Adeptus Custodes characters, with the exception of Trajann Valoris.
![image](https://user-images.githubusercontent.com/36267768/69487046-81b9e080-0e4b-11ea-98b4-cb21edb0558d.png)

**Comment by WindstormSCR** [comment] 2019-11-24 14:49
Duplicate of #5975

**Closed by WindstormSCR** 2019-11-24 14:49 UTC
