### ISSUE TITLE
[Anon] Bug report: Aeldari - Craftworlds.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3174] opened 2018-05-28 04:09 UTC
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.01.13

**Platform:** Windows

**Dropbox:** Yes

**Description:** Illic Nightspear has been removed and cannot be added to a list even if Alaitoc is selected as the craftworld attribute.

**Comment by Kohato** [comment] 2018-05-28 13:42
Duplicate of #3173

**Closed by Kohato** 2018-05-28 13:42 UTC
