### ISSUE TITLE
Imperium - Blood Angels: No access to WLTs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6271] opened 2019-12-11 09:41 UTC
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** Blood Angel warlords cannot select from the BA specific warlord traits.
Only the generic 3 traits appear.

Battle scribe version v2.03.16.325 with data set  v1.4.1 released 10th Dec

**Comment by Mad-Spy** [comment] 2019-12-11 10:41
Duplicate of #6246

**Closed by Mad-Spy** 2019-12-11 10:41 UTC
Labels: Area: selections, Type: bug, ✔ Res: duplicate, 💾 Cat: Imperium - Blood Angels
