### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5838] opened 2019-10-25 20:53 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 1.03.25

**Platform:** Windows

**Dropbox:** No

**Description:** Raven Guard and their successor chapters need a selection for "Master of the Trifold Path" which allows the warlord a second warlord trait for 1 CP.  I don't see this as a current option.

**Comment by Mad-Spy** [comment] 2019-10-26 20:19
Duplicate of #5712

**Closed by Mad-Spy** 2019-10-26 20:19 UTC
