### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6023] opened 2019-11-26 00:19 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** No relic can be added in Space marine. Reproduce: Get a character, select warlord, choose a relic. Alert raise, relic maximum 0.

**Comment by WindstormSCR** [comment] 2019-11-26 20:21
duplicate of #5998

**Closed by WindstormSCR** 2019-11-26 20:21 UTC
