### ISSUE TITLE
[Anon] Bug report: Aeldari - Craftworlds.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6208] opened 2019-12-10 18:57 UTC
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** Vibro cannon is currently listed as 15 pts. Needs to be 10 pts.

**Comment by KalChoedan** [comment] 2019-12-10 21:16
Duplicate of #6192

**Closed** 2019-12-10 22:38 UTC
Labels: Type: bug, ✔ Res: duplicate, 💾 Cat: Aeldari - Craftworlds
