### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6514] opened 2019-12-30 03:19 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.17

**Platform:** Android

**Dropbox:** No

**Description:** Selecting Wolf Claw (pair) on Wolf Guard Pack Leader for Grey Hunters (haven't confirmed other WGPL options) doesn't count as replacement for bolt pistol/CCW

**Comment by Mad-Spy** [comment] 2020-01-01 21:30
Duplicate of #6513

**Closed by Mad-Spy** 2020-01-01 21:30 UTC
