### ISSUE TITLE
[Anon] Bug report: Imperium - Deathwatch.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6936] opened 2020-03-31 10:36 UTC
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.20

**Platform:** Android

**Dropbox:** No

**Description:** Deathwatch Terminator Cyclone Missile Launcher appears to be counting itself as including a storm bolter without reflecting the points value and allocating an extra storm bolter. Resulting in a "too many storm bolters" error.

**Comment by Mad-Spy** [comment] 2020-03-31 10:43
Duplicate of #6900

**Closed by Mad-Spy** 2020-03-31 10:43 UTC
Labels: Area: validation, Type: bug, ✔ Res: duplicate, 💾 Cat: Imperium - Deathwatch
