### ISSUE TITLE
[Anon] Bug report: Aeldari - Harlequins.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5989] opened 2019-11-18 06:59 UTC
**File:** Aeldari - Harlequins.catz

**BattleScribe version:** 2.03.12

**Platform:** Android

**Dropbox:** No

**Description:** Unable to select Masque-specific relics in Harlequin detachments. For example, Faolchu's Talon is not available in list of relics, even when Soaring Spite is the selected Masque.

**Comment by Mad-Spy** [comment] 2019-11-20 21:28
Duplicate of #5986

**Closed by Mad-Spy** 2019-11-20 21:28 UTC
