### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4972] opened 2019-04-24 04:55 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.00

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** They is currently only one catalog available for force selection

**Comment by williamcaw** [comment] 2019-04-24 06:31
Duplicate of #4959 You can find out more information in the main thread

**Closed** 2019-04-24 07:23 UTC
Labels: Type: bug, ✔ Res: duplicate
