### ISSUE TITLE
adeptus mechanicus and space wolves don't work

### ISSUE THREAD

**Issue by pjklan** [BSData/wh40k#6306] opened 2019-12-11 20:10 UTC
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:**can't load or create rosters for swolves and ad mech

**Comment by CrusherJoe** [comment] 2019-12-11 22:51
Space Wolves works just fine for me.

**Comment by CrusherJoe** [comment] 2019-12-13 06:14
Unable to reproduce. Closing.

**Closed by CrusherJoe** 2019-12-13 06:14 UTC
Labels: ⛔ Problem: not reproducing
