### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4979] opened 2019-04-24 11:44 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.00

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The only army lists available are chaos and space marines.

**Comment by Thairne** [comment] 2019-04-24 11:51
Duplicate of #4959

**Closed by Thairne** 2019-04-24 11:51 UTC
Labels: Area: BattleScribe app, Type: bug, ✔ Res: duplicate
