### ISSUE TITLE
[Anon] Bug report: Imperium - Blood Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6601] opened 2020-01-21 09:00 UTC
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** Yes

**Description:** Blood Angels Inferno Pistols are showing as being 7 points when they should be 9

**Comment by Mad-Spy** [comment] 2020-01-21 09:03
Duplicate of #6598

**Closed by Mad-Spy** 2020-01-21 09:03 UTC
