### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4068] opened 2018-12-15 13:42 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 1.02.00

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Chaos landraider has 2 twin lascannons listed as 100 points.
2 twin lascannons should be 80 points.

**Comment by GenWilhelm** [comment] 2018-12-15 13:54
Duplicate of #4054

**Closed by GenWilhelm** 2018-12-15 13:54 UTC
