### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Custodes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6231] opened 2019-12-10 21:37 UTC
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** The Vexilus storm shield cost should be 10pts as they're characters but it's showing up as 5pts. 
The storm shield cost for Custodian Guard should be 5pts each instead of 10pts. 
Note: this is the same issue on Windows (FYI). 
Thanks for your great work.

**Comment by tekton** [comment] 2019-12-10 22:12
Thank you kindly! This is a duplicate of #6118 and will be fixed in the next release!

**Closed by tekton** 2019-12-10 22:12 UTC
