### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4105] opened 2018-12-15 21:12 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Reaper autocannon for Helbrute, Defiler, and Chaos Terminators is listed at 15 points, should be 10.

**Comment by Kohato** [comment] 2018-12-16 04:46
Duplicate of #4078

**Closed by Kohato** 2018-12-16 04:46 UTC
Labels: Area: costs, Type: bug, ✔ Res: duplicate, 💾 Cat: Chaos - Chaos Space Marines
