### ISSUE TITLE
[Anon] Bug report: Necrons.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2752] opened 2018-04-01 22:59 UTC
**File:** Necrons.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** In the necron roster, the "lychguard" and "deathmark" options are listed as elites.  They are now considered troops as per the code release.  Thank you!

**Comment by WindstormSCR** [comment] 2018-04-01 23:06
Duplicate of #2743

**Closed by WindstormSCR** 2018-04-01 23:06 UTC
Labels: Necrons, Resolution - duplicate
