### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6860] opened 2020-03-08 20:11 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.18

**Platform:** Android

**Dropbox:** No

**Description:** The Blood Claws entry does not allow me to uses less than 4 basic Blood Claws.  This is a problem because it means I can't run a 5 man squad with a special weapon.  The Gray hunters entry is similarly built and does allow you to use less than 4 basic Gray Hunters.

**Comment by Mad-Spy** [comment] 2020-03-09 08:33
Duplicate of #6725

**Closed by Mad-Spy** 2020-03-09 08:33 UTC

**Comment by deweywolf** [comment] 2020-03-11 23:16
Thanks!!
