### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5015] opened 2019-04-25 16:40 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Only chaos- renegade knights showing up when choosing a force for a new list

**Comment by williamcaw** [comment] 2019-04-25 17:08
The issue has been fixed please update the app

**Comment by williamcaw** [comment] 2019-04-25 17:11
duplicate of #4959

**Closed** 2019-04-25 20:03 UTC
