### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4845] opened 2019-04-02 17:07 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.21

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** CSM Havoc lists price of Havoc with Missile Launcher at 14pts. Cost should be 34pt (14 + 20)

**Comment by GenWilhelm** [comment] 2019-04-02 18:18
Duplicate of #4841

**Closed by GenWilhelm** 2019-04-02 18:18 UTC
