### ISSUE TITLE
[Anon] Bug report: Chaos - Death Guard.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3688] opened 2018-09-27 14:52 UTC
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** No entry present for beasts of gurgle under elite choices

**Comment by Mad-Spy** [comment] 2018-09-27 14:53
Duplicate of #3684

**Closed by Mad-Spy** 2018-09-27 14:53 UTC
