### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5699] opened 2019-09-24 23:42 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.03

**Platform:** Android

**Dropbox:** No

**Description:** Apologies if this is not the right place, but the Stormhawk Interceptor "Halo Infernum Launcher" rule has changed in the new codex and has not been updated.

**Comment by Mad-Spy** [comment] 2019-09-25 05:39
Duplicate of #5633

**Closed by Mad-Spy** 2019-09-25 05:39 UTC
