### ISSUE TITLE
[Anon] Bug report: Orks.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4792] opened 2019-03-27 08:18 UTC
**File:** Orks.catz

**BattleScribe version:** 2.01.20

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The elite troop unit: Runtherd is missing from the elites menu despite being in the orks 8th edition codex

**Comment by Mad-Spy** [comment] 2019-03-27 10:00
Duplicate of #4791

**Closed by Mad-Spy** 2019-03-27 10:00 UTC
Labels: Area: selections, Type: bug, ✔ Res: duplicate, 💾 Cat: Orks
