### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5983] opened 2019-11-17 14:42 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.07

**Platform:** Windows

**Dropbox:** Yes

**Description:** error (!) new roster (Warhammer 40K v110) has 1 too many selections from chapter relics (maximum 0)

This error occurs even when the only unit in the roster is the warlord and you give him a relic.

**Comment by Mad-Spy** [comment] 2019-11-20 21:20
Duplicate of #5978

**Closed by Mad-Spy** 2019-11-20 21:20 UTC
