### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2775] opened 2018-04-05 17:24 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.10

**Platform:** Windows

**Dropbox:** No

**Description:** Can't change the Sept from T'au sept without it dissapiring. Also trying to change the gun-drones on the Devilfish to the smart missile system it also goes away. Might be the same for other units.

**Comment by Kohato** [comment] 2018-04-05 17:27
Duplicate of #2774 - Issue is a BS bug in 2.01.10 for desktop.

**Closed by Kohato** 2018-04-05 17:27 UTC
