### ISSUE TITLE
Space Marines - Aggressor Squad Sergeant cost is wrong

### ISSUE THREAD

**Issue by bowgs** [BSData/wh40k#1880] opened 2017-12-03 12:00 UTC
**File/Catalogue:** Space Marines v36

**BattleScribe version:** 2.01.

**Platform:** Windows/Android

**Dropbox:** Yes

**Description:** The Aggressors have dropped in price to 21pts.  The regular aggressors reflect this change, but the sergeant still costs 25pts.

**Comment by ilaunchbury** [comment] 2017-12-04 10:11
Duplicate of #1877

**Closed by ilaunchbury** 2017-12-04 10:11 UTC
Labels: Bug - cost, Imperium - Space Marines, Resolution - duplicate
