### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4904] opened 2019-04-10 07:50 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.17

**Platform:** Windows

**Dropbox:** No

**Description:** Inflitrator Squad power level increases from 5 to 11 when multiple squads are added to the roster.

**Comment by Mad-Spy** [comment] 2019-04-10 08:04
Duplicate of #4900

**Closed by Mad-Spy** 2019-04-10 08:04 UTC
Labels: Area: validation, Type: bug, ✔ Res: duplicate, 💾 Cat: Imperium - Space Marines
