### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4746] opened 2019-03-18 09:00 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.23

**Platform:** Android

**Dropbox:** No

**Description:** Shadowspear latest entries are not available uns et SPACE WOLVES,  although they are OK for regular Space marine s

**Comment by Mad-Spy** [comment] 2019-03-18 09:01
Duplicate of #4742

**Closed by Mad-Spy** 2019-03-18 09:01 UTC
Labels: 💾 Cat: Imperium - Space Wolves, 📋 Task: update (new publication)
