### ISSUE TITLE
Problem with Warlord's Traits of the Blood Angels

### ISSUE THREAD

**Issue by Victorius-Vasc** [BSData/wh40k#6354] opened 2019-12-12 22:00 UTC
**File/Catalogue:**  Imperium - Blood Angels v107

**BattleScribe version:** 2.03.10.139

**Platform:** Windows 10 / Android

**Dropbox:** No

**Description:** Greetings, Since the recent update of the catalog, where the rules of the codex supplement Blood of Baal are incorporated, there is an error in the data of the traits when designating a unit as Warlord. Only the general traits option for Space Marines is displayed, but NOT those of the Blood Angels chapter.
I also tried the Phobos unit traits, and these do appear
![Error BS BA](https://user-images.githubusercontent.com/56646608/70752516-8cacb600-1d11-11ea-97eb-528160f0cd0f.JPG)
.

**Comment by alphalas** [comment] 2019-12-12 23:09
It’s fixed in the latest release

**Closed by alphalas** 2019-12-12 23:09 UTC

**Comment by tbaart** [comment] 2019-12-13 09:28
I have version 1.4.2 but I still have this issue. Created a completely new roster as well, but still can't select warlord traits.

**Comment by Victorius-Vasc** [comment] 2019-12-13 13:38
> I have version 1.4.2 but I still have this issue. Created a completely new roster as well, but still can't select warlord traits.

Try updating your BS to the latest version, it should work now.

**Comment by tbaart** [comment] 2019-12-13 13:54
> > I have version 1.4.2 but I still have this issue. Created a completely new roster as well, but still can't select warlord traits.
> 
> Try updating your BS to the latest version, it should work now.

I did, 1.4.2 is the latest version right?

I was explained on Discord what the problem is.
The latest BA update changed the BA version number from 107 to 104, making BS think it's an older version. BS then doesn't update the BA data.
When I completely removed the w40k data and redownloaded it, it correctly updated BA data. It works now.

So if the BA version is updated to 108 or higher so that BS recognizes that it's a newer version, it'll work properly for everyone.

I was also told that Alphalas has already been informed about the wrong version number.

**Comment by Victorius-Vasc** [comment] 2019-12-13 14:55
> I did, 1.4.2 is the latest version right?

On both PC and Android, I have version 2.03.16.325.
With 1.42, you mean the version of what?

**Comment by tbaart** [comment] 2019-12-13 14:58
Ah, I see, you meant the BS version (which is also what you said), but I misinterpreted it as the w40k data version. My bad.

I had BS version 2.03.10.something, so that wasn't the latest version.
I updated BS, but I can't really say if that fixed it. What I explained above already fixed it for me.

**Comment by tbaart** [comment] 2019-12-13 14:59
> On both PC and Android, I have version 2.03.16.325.
> With 1.42, you mean the version of what?

Ah, I see, you meant the BS version (which is also what you said), but I misinterpreted it as the w40k data version. My bad.

I had BS version 2.03.10.something, so that wasn't the latest version.
I updated BS, but I can't really say if that fixed it. What I explained above already fixed it for me.

**Comment by Victorius-Vasc** [comment] 2019-12-13 15:01
Now I understand.
Thanks for clarifying it. At least the list and the information work for now.

**Comment by tbaart** [comment] 2019-12-13 15:02
Yep! Thanks for your time anyway :)
