### ISSUE TITLE
[Anon] Bug report: Imperium - Deathwatch.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6207] opened 2019-12-10 18:57 UTC
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** No

**Description:** Cyclone Missile Launchers were dropped to 32 points in Chapter Approved 2019, they are still showing as 38 points in BS

**Comment by Mad-Spy** [comment] 2019-12-10 22:37
Duplicate of #6140

**Closed by Mad-Spy** 2019-12-10 22:37 UTC
