### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5697] opened 2019-09-24 20:01 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.03.03

**Platform:** Android

**Dropbox:** No

**Description:** Pathfinder with Ion Rifle is 12 should be 17
Pathfinder with Rail Rifle is 17 should be 22
Missile Pod is 15 should be 24
Flamer is 6 should be 9
Advanced Targeting system is 6 should be 12
High Output burst cannon is 16 should be 20
High Output missile pod is missing
Cyclic Ion Blaster is missing for Coldstar Battlesuit
Coldstar Battlesuitrules are incorrect, must not necesseraly need Missile pod

**Comment by amis92** [comment] 2019-09-24 20:04
Essentially duplicate of #5690 - see resolution there.

Re: Coldstar. HYBC has to be taken with MissilePod. Read the rules carefully.

**Closed by amis92** 2019-09-24 20:04 UTC
Labels: 💾 Cat: T'au Empire
