### ISSUE TITLE
T'au: XV25 Stealthsuits Fusion blaster limit broken

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5924] opened 2019-11-03 17:49 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.03.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** When taking 3 Stealth suits, the Codex allows one of them to change out their Burst cannon for a Fusion Blaster. When selecting this option in BS it error and shows the Max allowed is 0.

**Comment by amis92** [comment] 2019-11-03 18:15
Again...? :(

**Comment by amis92** [comment] 2019-11-03 18:19
Duplicate of #4958

**Comment by amis92** [comment] 2019-11-15 14:06
This was fixed in an app update, marked in the issue referenced above.

**Closed by amis92** 2019-11-15 14:06 UTC
Labels: Area: BattleScribe app, Area: validation, Type: bug, ✔ Res: external, 💾 Cat: T'au Empire
