### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Custodes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5977] opened 2019-11-15 19:11 UTC
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.12

**Platform:** Android

**Dropbox:** No

**Description:** Custodes hqs cannot take any warlords traits after last update.

**Comment by Mad-Spy** [comment] 2019-11-18 08:33
Duplicate of #5975

**Closed by Mad-Spy** 2019-11-18 08:33 UTC
