### ISSUE TITLE
Tyranids - Genestealer Cults: Field Commander validation error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4769] opened 2019-03-21 20:35 UTC
**File:** Tyranids - Genestealer Cults.catz

**BattleScribe version:** 2.01.16

**Platform:** Mac

**Dropbox:** No

**Description:** Detachment errors

When taking a Deliverance Broodsurge or an Anointed Throng, and you select the Field Commander ability... you get an error message telling you that you must have (1) of the Warlord Trait from the other detachment.

e.g. Take Anointed Throng, make Abominant the Field Commander, assign the WL trait... Insidious Mindwyrm, you get the error: Abominant must have 1 more from selection of Augur of the Insurgent.
e.g. Take Deliverance Broodsurge, make Iconward the Field Commander, assign the WL trait... Augur of the Insurgent, you get the error: Iconward must have 1 more from selection of Insidious Mindwyrm.

**Comment by GenWilhelm** [comment] 2019-03-21 21:47
Duplicate of #4720

**Closed by GenWilhelm** 2019-03-21 21:47 UTC
Labels: Area: validation, Type: bug, 💾 Cat: Tyranids - Genestealer Cults
