### ISSUE TITLE
Chaos - Chaos Space Marines: Dark Vengeance unit validation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5192] opened 2019-06-07 22:23 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** Yes

**Description:** Vrosh Tattersoul, Kranon the Relentless, and Draznicht's Ravagers have the wrong Legion for validation.  The data set only validates when 'Renegade Chapters' is selected.  The correct validation for all three should be the legion 'Crimson Slaughter'.  The lists are also missing the two unique Chaos Cultists units (Sect Anarkus and Sect Tetchvar) as well as the unique Hellbrute (Mortis Metalikus).  However, the last three may be unnecessary as they don't have any special rules.  updated data sheets for all of the above from the DV update pdf can be found here:  https://imgur.com/gallery/xYz4a

**Comment by Mad-Spy** [comment] 2019-06-07 22:41
Not sure what the problem is with the validation. The above units are valid for both Crimson Slaughter and Renegade Chapters. Either is valid, as you can play Crimson Slaughter using either the Codex or Vigilus Ablaze rules.

The Cultist and Helbrute units are, as you say, not needed as they do not deviate from standard loadouts, unlike the others.

**Comment by Mad-Spy** [comment] 2019-06-10 06:52
Closing as there's been no update from the OP.

**Closed by Mad-Spy** 2019-06-10 06:52 UTC
Labels: Area: validation, Type: bug, ✔ Res: no OP clarification, 💾 Cat: Chaos - Chaos Space Marines

**Comment by g-pechorin** [comment] 2019-09-18 11:26
I have the same problem with "Chaos Space Marines v108" and "BattleScribe v2.03.01.128"

I have a Patrol with the Vrosh and the stuff from Dark Vengeance. If I choose "Crimson Slaughter" I get told off for the three named selections, however, it works fine with the Legion set to "Renegade Chapters"

[I attached a roster (renamed as .txt) showing the problem](https://github.com/BSData/wh40k/files/3626097/DV-Chaos-Crimson.ros.txt)

**Comment by g-pechorin** [comment] 2019-09-18 11:45
Looks like Kranon and Vrosh were allowed in "Renegade" and "No Legion" whereas Ravagers were only allowed in "No Legion"?

[This pull request "fixes" the three named units to all be accepted in "Renegade" / "No Legion" / "Crimson" and bumps the Chaos version to v109](https://github.com/BSData/wh40k/pull/5668)
