### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5003] opened 2019-04-25 09:49 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Hi there (love the app by the way!), after updating the app yesterday, when trying to create a new roster in 40k I can only see Chaos Renagade Knights. I have tried updating the data but the issue remains.

**Comment by williamcaw** [comment] 2019-04-25 14:06
The app is updated to 2.02.02

**Comment by WindstormSCR** [comment] 2019-04-25 14:08
duplicate of #4959

**Closed by WindstormSCR** 2019-04-25 14:08 UTC
