### ISSUE TITLE
Aeldari - Craftworlds: Exalted of Ynnead should allow additional WLT

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5075] opened 2019-05-03 10:45 UTC
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.02.01

**Platform:** Windows

**Dropbox:** No

**Description:** 'Exalted of Ynnead' selection in the 'No Force Org' area does not allow valid allocation of a second warlord trait. This should work in a similar way to the Imperial Knights 'Exalted Court' Stratagem

**Comment by WindstormSCR** [comment] 2019-05-04 15:18
duplicate of #5052

**Closed by WindstormSCR** 2019-05-04 15:18 UTC
Labels: Area: edit UX, Type: request, 💾 Lib: Aeldari - Ynnari
