### ISSUE TITLE
Imperial Knights catalogue loading issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3711] opened 2018-10-03 20:42 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.22.00

**Platform:** Windows

**Dropbox:** No

**Description:** Imperial Knight data will not load nor can it be added to any list. Screen will stall and not go to page when you add list individually. When adding to another already made list, data will display error message and will not add.

**Comment by Kohato** [comment] 2018-10-04 17:46
It loads fine on iOS for me.  What version IK Data are you using?  The current version should be v23

**Comment by williamcaw** [comment] 2018-10-06 06:04
It’s a issue on app spot there is nothing this team of coders can do

**Comment by amis92** [comment] 2018-10-06 18:32
@williamcaw can you share more details? What's the issue on Appspot?

**Comment by Kohato** [comment] 2018-10-06 18:54
I’m guessing the issue is old data or old bs version. Older bs will crash with ik due to a flag I use from the newer versions

**Comment by williamcaw** [comment] 2018-10-06 20:16
@amis92 the file has just been loading then deloading from the page of hosting for the last 2 weeks

**Comment by Kohato** [comment] 2018-10-06 21:57
Separate issue. 

~Earl Bishop

**Comment by Kohato** [comment] 2018-10-07 15:47
No update from user for 4 days - closing issue.  Likely due to old version of BS which cannot support a Count of Forces - which is used in this catalog for validation.

**Closed by Kohato** 2018-10-07 15:47 UTC
Labels: Area: BattleScribe app, Type: bug, ⛔ Problem: not reproducing, 💾 Cat: Imperium - Imperial Knights
