### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4694] opened 2019-03-08 08:56 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** New publication placeholder, new discipline psychic powers,  Area :  selection

**Comment by Mad-Spy** [comment] 2019-03-08 10:30
Duplicate of #4677

**Closed by Mad-Spy** 2019-03-08 10:30 UTC
