### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3396] opened 2018-08-03 04:22 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Redemptor dreadnought should have <CHAPTER> category/keyword, as per space marine codex

**Comment by sparklenecrons** [comment] 2018-08-03 04:31
"Chapter" keyword

**Comment by Mad-Spy** [comment] 2018-08-03 13:18
Duplicate of #3397

**Closed by Mad-Spy** 2018-08-03 13:18 UTC
Labels: Area: text/rule/profile, Type: bug, ✔ Res: duplicate, 💾 Cat: Imperium - Space Wolves
