### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5419] opened 2019-08-20 18:23 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.02.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Invictor Warsuit Twin Autocannon showing as a free option. Should be 20 points

**Comment by WindstormSCR** [comment] 2019-08-20 19:15
Duplicate of #5404

**Closed by WindstormSCR** 2019-08-20 19:15 UTC
