### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1643] opened 2017-10-18 00:07 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The point cost for adding a heavy weapons team in an infantry squad, veteran squad, and command squad are off by 4/6 points respectively as it is only paying for a single model instead of the two models that are allocated to being a heavy weapons team.

The telepathica stave carried by astropaths is 6 points instead of 0

**Comment by GenWilhelm** [comment] 2017-10-18 09:53
Duplicate of #1636.

**Closed by GenWilhelm** 2017-10-18 09:53 UTC
