### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2012] opened 2017-12-10 20:29 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.09

**Platform:** Android

**Dropbox:** No

**Description:** On the storm raven the double hurricane boaters are showing as 8 but they should be 20.  This is because of the point update in chapter approved

**Comment by ilaunchbury** [comment] 2017-12-11 08:28
Duplicate of #1986.

**Closed by ilaunchbury** 2017-12-11 08:28 UTC
Labels: Bug - cost, Imperium - Space Marines, Resolution - duplicate
