### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5621] opened 2019-09-06 10:02 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Icarus Rocket Pod is now causing 2 wounds. This should be changed in the datasheets of BattleScribe, too.

**Comment by Mad-Spy** [comment] 2019-09-06 10:08
Duplicate of #5589

**Closed by Mad-Spy** 2019-09-06 10:08 UTC
