### ISSUE TITLE
Imperium - Questor Imperialis: Exalted Court and Heirlooms not validating correctly

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6944] opened 2020-04-02 06:29 UTC
**File:** Imperium - Questor Imperialis.catz

**BattleScribe version:** 2.03.20

**Platform:** Android

**Dropbox:** No

**Description:** The Exalted Court and Heirlooms of the Household stratagems 3 CP versions only add 1 character choice when they should add 2.

**Comment by DrTobogganMD** [comment] 2020-04-02 11:19
Duplicate of #6918 - This has been fixed. It will be pushed out *soon

**Closed by DrTobogganMD** 2020-04-02 11:19 UTC
Labels: Area: validation, Type: bug, 💾 Cat: Imperium - Imperial Knights
