### ISSUE TITLE
[Anon] Bug report: T'au Empire.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3442] opened 2018-08-25 09:59 UTC
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** It says, the commander in xv86 coldstar battlesuit has a minimum of 1 missile pods. Thats wrong. You can change it with another weapon.

**Comment by amis92** [comment] 2018-08-25 12:07
Indeed, you can. You just can't have High-output Burst Cannon *without* missile pod. Duplicate of #2936

**Closed by amis92** 2018-08-25 12:07 UTC
Labels: Area: validation, Type: bug, ✔ Res: duplicate, 💾 Cat: T'au Empire
