### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4961] opened 2019-04-23 15:24 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.00

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Updated BattleScribe to v2.20.00 from App Store and refreshed wh40k data to v1.3.0 today (23 April). Can now only create Chaos - Renegade Knight v15 list from catalogue when selecting a new roster and editing any existing rosters causes app to crash.

**Comment by DrTobogganMD** [comment] 2019-04-23 18:05
Duplicate of #4959

**Closed by DrTobogganMD** 2019-04-23 18:05 UTC
