### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6731] opened 2020-02-11 04:41 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.17

**Platform:** Android

**Dropbox:** No

**Description:** Space wolves entry troop choice Blood claws.  You cannot have less than 4 basic Blood claws.  This is a problem if you want to add special weapons to a 5 man squad.  It functions properly on the gray hunters entry.

**Comment by Mad-Spy** [comment] 2020-02-11 06:24
Duplicate of #6725

**Closed by Mad-Spy** 2020-02-11 06:24 UTC
