### ISSUE TITLE
[Anon] Bug report: Necrons.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2817] opened 2018-04-10 02:05 UTC
**File:** Necrons.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** The Elites list for units is wrong only elites in the new codex are Flayed ones, praetorians,and triarch stalkers

**Comment by WindstormSCR** [comment] 2018-04-10 02:54
Duplicate of #2743

**Closed by WindstormSCR** 2018-04-10 02:54 UTC
Labels: Necrons, Resolution - duplicate
