### ISSUE TITLE
Warhammer 40,000 8th Edition: Detachment validation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5049] opened 2019-04-30 01:13 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.01

**Platform:** Windows

**Dropbox:** No

**Description:** Validation issue with Spearhead Detachment. Says must include 3 Elite choices, when 3 elite choices are added it invalidates list stating "Maximum selection is 2"

**Comment by Mad-Spy** [comment] 2019-04-30 07:42
Please can you let us have some more details of your Force setup? Have you accidentally nested the detachments? We are unable to reproduce this error.

**Comment by Dunamis55** [comment] 2019-04-30 11:12
I'd say this is a duplicate of #4957. Saving then re-opening the roster file should make the errors go away, as a possible temporary workaround.

**Closed** 2019-05-10 10:22 UTC
Labels: Area: validation, ✔ Res: no OP clarification
