### ISSUE TITLE
[Anon] Bug report: Fallen.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7057] opened 2020-04-25 12:02 UTC
**File:** Fallen.catz

**BattleScribe version:** 2.03.21

**Platform:** Android

**Dropbox:** No

**Description:** Fallen specialist detachment sorcerer with jump-pack has wrong point value. Please fix it

**Comment by Mad-Spy** [comment] 2020-04-25 14:01
Duplicate of #7051

**Closed by Mad-Spy** 2020-04-25 14:01 UTC
