### ISSUE TITLE
Tank Aces do not validate

### ISSUE THREAD

**Issue by BaconCatBug** [BSData/wh40k#7044] opened 2020-04-23 14:14 UTC
**File/Catalogue:** Astra Militarum v264

**BattleScribe version:** 2.03.15

**Platform:** Windows

**Description:** Tank Aces do not give an error if selected without an Astra Militarum Warlord. Furthermore, no error is given if you take a second Tank Ace ability without using the stratagem.
Further, furthermore, you can take more than two Tank Ace abilities with no error.

**Comment by DrTobogganMD** [comment] 2020-04-23 15:03
This is likely fixed in the latest update. I pushed a release this morning, so appspot should pick it up by the afternoon.  Duplicate of #6945

**Closed by DrTobogganMD** 2020-04-23 15:03 UTC
Labels: Area: selections, Type: bug, ✔ Res: duplicate, 💾 Cat: Imperium - Astra Militarum
