### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5434] opened 2019-08-21 04:32 UTC
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** No

**Description:** Missing Exemplar of the Chapter strategem option for Warlords, at least for Ultramarines. This would allow a user to add an additional Warlord Trait to a Warlord, so long as it was a chapter warlord trait.

**Comment by WindstormSCR** [comment] 2019-08-21 06:05
Duplicate of #5431

**Closed by WindstormSCR** 2019-08-21 06:05 UTC
