### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4254] opened 2018-12-18 19:21 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Adeptus Custodes Storm Shields cost 2 points in this version while the correct value should be 10.

**Comment by WindstormSCR** [comment] 2018-12-18 20:05
Duplicate of #4213

**Closed by WindstormSCR** 2018-12-18 20:05 UTC
Labels: ✔ Res: duplicate
