### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7036] opened 2020-04-22 04:41 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.21

**Platform:** Android

**Dropbox:** No

**Description:** Whenever I choose a tank ace, I get the message that I have 1 too many tank aces (max 0), even though I did not choose a warlord trait for my warlord.  I also have a similar message whenever I try to use the tank ace stratagem to get a second tank ace ability.

**Comment by alphalas** [comment] 2020-04-23 20:52
duplicate of #6945

**Closed by alphalas** 2020-04-23 20:52 UTC
