### ISSUE TITLE
[Anon] Bug report: Orks.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5514] opened 2019-08-24 07:23 UTC
**File:** Orks.catz

**BattleScribe version:** 2.03.00

**Platform:** Android

**Dropbox:** No

**Description:** Orks Warboss is listed in uncategorized rather than HQ slot.

**Comment by Mad-Spy** [comment] 2019-08-24 18:21
Duplicate of #5496

**Closed by Mad-Spy** 2019-08-24 18:21 UTC
