### ISSUE TITLE
[Anon] Bug report: Aeldari - Drukhari.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2787] opened 2018-04-07 22:59 UTC
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.01.10

**Platform:** Windows

**Dropbox:** No

**Description:** Scourge Solarite has no option to take melee weapons.

**Comment by WindstormSCR** [comment] 2018-04-07 23:45
Duplicate of #2783

**Closed by WindstormSCR** 2018-04-07 23:45 UTC
Labels: Aeldari - Drukhari, Resolution - duplicate
