### ISSUE TITLE
[Anon] Bug report: Orks.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3361] opened 2018-07-21 01:48 UTC
**File:** Orks.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Ork unit Mega Dread stats profile is not 
presented and cannot be found anywhere

**Comment by Mad-Spy** [comment] 2018-07-21 05:45
Duplicate of #3360

**Closed by Mad-Spy** 2018-07-21 05:45 UTC
