### ISSUE TITLE
Aeldari - Craftsworlds - Visarch not triggering Ynnari options

### ISSUE THREAD

**Issue by mooftak** [BSData/wh40k#6788] opened 2020-02-22 02:53 UTC
**File/Catalogue:** 
Aeldari - Craftworlds.cat
**BattleScribe version:** 2.03.11.140

**Platform:** Windows

**Dropbox:** No

**Description:** When adding Visarch to your detachment, you are unable to make the detachment a Ynnari one. It seems to work as intended if you add the Yncarne or Yvraine.

**Comment by mooftak** [comment] 2020-02-22 19:30
Looks like the issue is at line 14915 column 178, but I could be wrong. Relevant code below. I think ff5c-6397-4052-63eb should be replaced with 6c95-9f0a-0951-30ab. That may be the issue or may be part of it. Again, first time ever looking at these and I'm working in Notepad so I could be way off.


<selectionEntry id="7219-d2ab-d87a-d467" name="Ynnari" hidden="true" collective="false" import="true" type="upgrade">
          <modifiers>
            <modifier type="set" field="hidden" value="false">
              <conditionGroups>
                <conditionGroup type="or">
                  <conditions>
                    <condition field="selections" scope="force" value="0.0" percentValue="false" shared="true" includeChildSelections="true" includeChildForces="false" childId="1409-e740-c7c9-3758" type="greaterThan"/>
                    <condition field="selections" scope="force" value="0.0" percentValue="false" shared="true" includeChildSelections="true" includeChildForces="false" childId="c0ea-f722-6a2e-6d65" type="greaterThan"/>
                    <condition field="selections" scope="force" value="0.0" percentValue="false" shared="true" includeChildSelections="true" includeChildForces="false" childId="ff5c-6397-4052-63eb" type="greaterThan"/>
                  </conditions>
                </conditionGroup>
              </conditionGroups>
            </modifier>
          </modifiers>
          <constraints>
            <constraint field="selections" scope="parent" value="1.0" percentValue="false" shared="true" includeChildSelections="false" includeChildForces="false" id="5f10-4683-a2d2-a37a" type="max"/>
          </constraints>
          <profiles>
            <profile id="3ded-c71a-25bb-b082" name="Ynnari" hidden="false" typeId="72c5eafc-75bf-4ed9-b425-78009f1efe82" typeName="Abilities">
              <characteristics>
                <characteristic name="Description" typeId="21befb24-fc85-4f52-a745-64b2e48f8228">Requires a Ynnari Character in Detachment. Detachment loses subfaction keywords and gains the REBORN keyword instead, and my not be the target of original subfaction stratagems.</characteristic>
              </characteristics>
            </profile>
          </profiles>
          <categoryLinks>
            <categoryLink id="786b-6690-69ee-34aa" name="Faction: Ynnari" hidden="false" targetId="ebb3-4f37-6e57-7a8e" primary="false"/>
          </categoryLinks>
          <costs>
            <cost name=" PL" typeId="e356-c769-5920-6e14" value="0.0"/>
            <cost name="pts" typeId="points" value="0.0"/>
            <cost name="CP" typeId="2d3b-b544-ad49-fb75" value="0.0"/>
          </costs>
        </selectionEntry>

**Comment by Mad-Spy** [comment] 2020-02-22 23:17
![image](https://user-images.githubusercontent.com/29306451/75100706-4a350e80-55c9-11ea-82d5-a94ffb0ceae9.png)

The highlighted entry is both using a link (which won't work) and a duplicate of the entry for the Yncarne. Switching it over to the Visarch will fix it.

**Closed** 2020-03-01 15:03 UTC
Labels: Area: validation, Type: bug, 💾 Cat: Aeldari - Craftworlds
