### ISSUE TITLE
[Anon] Bug report: Tyranids.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3385] opened 2018-07-27 21:24 UTC
**File:** Tyranids.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** If I select genestealers, I can only have them with tending claws. I cannot switch this option off to have just 2x scything talons.

**Comment by Mad-Spy** [comment] 2018-07-28 08:46
Duplicate of #3289

**Closed by Mad-Spy** 2018-07-28 08:46 UTC
Labels: Area: selections, Type: bug, ✔ Res: duplicate, 💾 Cat: Tyranids
