### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6275] opened 2019-12-11 09:47 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** No

**Description:** The Valkyrie Lascannon hasn't dropped down to 15 points with all the other lascannons.

**Comment by Mad-Spy** [comment] 2019-12-11 10:37
Duplicate of #6256

**Closed by Mad-Spy** 2019-12-11 10:37 UTC
Labels: Area: costs, Type: bug, ✔ Res: duplicate, 💾 Cat: Imperium - Astra Militarum
