### ISSUE TITLE
[Anon] Bug report: Imperium - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4391] opened 2019-01-03 00:56 UTC
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Wolf guard are supposed to be 14 points per model and wolf guard Terminators are supposed to be 23 points per model as per chapter approved 2018

**Comment by Mad-Spy** [comment] 2019-01-03 05:01
Duplicate of #4390

**Closed by Mad-Spy** 2019-01-03 05:01 UTC
Labels: Area: costs, Type: bug, ✔ Res: duplicate, 💾 Cat: Imperium - Space Wolves
