### ISSUE TITLE
[Anon] Bug report: Imperium - Astra Militarum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1626] opened 2017-10-12 23:36 UTC
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Taurox Prime's 2x Hot Shot Volley Guns are incorrectly costed. Should be 6 points each, not 9.

**Comment by ilaunchbury** [comment] 2017-10-13 07:14
Duplicate of #1618

**Closed by ilaunchbury** 2017-10-13 07:14 UTC
Labels: Bug - cost, Imperium - Astra Militarum, Resolution - duplicate
