### ISSUE TITLE
Add new rules for Necron Seraptek Heavy Construct 

### ISSUE THREAD

**Issue by lewis0460** [BSData/wh40k#3769] opened 2018-10-26 18:32 UTC
**File/Catalogue:** Necrons

**BattleScribe version:** 2.01.

**Platform:** Mac

**Dropbox:** No

**Description:** Add the data for the new Necron Seraptek Heavy Construct from Forge World.

**Comment by Kohato** [comment] 2018-10-26 18:39
What did I say? Duplicate of #3670

**Closed by Kohato** 2018-10-26 18:39 UTC

**Comment by lewis0460** [comment] 2018-10-26 19:09
Sorry! (didn't check that far back)

**Comment by Kohato** [comment] 2018-10-26 19:15
Yea, I got eager and tried to stave off issues way back when it was revealed. It just took them a month to give the rules.  It'll be added tonight.
