### ISSUE TITLE
[Anon] Bug report: Chaos - Questor Traitoris.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3309] opened 2018-06-26 23:00 UTC
**File:** Chaos - Questor Traitoris.catz

**BattleScribe version:** 2.01.14

**Platform:** Windows

**Dropbox:** Yes

**Description:** avenger gatling cannon cost is wrong, now it cost 92 pts (with flamers) not 112 anymore

**Comment by Mad-Spy** [comment] 2018-06-27 07:42
Duplicate of #3302. Fixed in v9.

**Closed by Mad-Spy** 2018-06-27 07:42 UTC
