### ISSUE TITLE
Space Marines: Warlord trait selection issue

### ISSUE THREAD

**Issue by rsochia** [BSData/wh40k#3190] opened 2018-05-30 14:12 UTC
The options to select what warlord trait you want on a unit that you have made warlord is gone.

**Comment by Kohato** [comment] 2018-05-30 14:16
Warlord Traits for Space Marines have been reworked.  This is fixed with our next release Soon^tm

Duplicate of #3188

**Closed by Kohato** 2018-05-30 14:16 UTC
Labels: Area: selections, Type: bug, ✔ Res: duplicate, 💾 Cat: Imperium - Space Marines

**Comment by rsochia** [comment] 2018-05-30 14:22
OK. I submitted this because there has been no commits to the space marine file with the fixes for this issue since the most recent release was built and did not know the bug was already known.

**Comment by Kohato** [comment] 2018-05-30 14:45
No problems :)
