### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6723] opened 2020-02-10 00:44 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** No

**Description:** Bolt Rifles carried by Deathwatch Intercessor Sergeants cost one point when they should cost zero.

**Comment by Mad-Spy** [comment] 2020-02-10 09:21
Duplicate of #6504

**Closed by Mad-Spy** 2020-02-10 09:21 UTC
Labels: ✔ Res: duplicate, 💾 Cat: Imperium - Deathwatch
