### ISSUE TITLE
[Anon] Bug report: Chaos - FW Heretic Astartes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4566] opened 2019-02-04 12:37 UTC
**File:** Chaos - FW Heretic Astartes.catz

**BattleScribe version:** 2.01.15

**Platform:** Linux

**Dropbox:** No

**Description:** Lugft Huron is missing his 4+ iron halo Invuln save that's listed in the forgeworld release.

**Comment by DrTobogganMD** [comment] 2019-02-04 14:52
Duplicate of #4567

**Closed by DrTobogganMD** 2019-02-04 14:52 UTC
