### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4989] opened 2019-04-24 21:23 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I have no faction options other that renegade knights for 40k 8th. This happened right after making a list for Sisters of Battle list, may be coincidence.

**Comment by WindstormSCR** [comment] 2019-04-24 21:55
Duplicate of #4959

**Closed by WindstormSCR** 2019-04-24 21:55 UTC
