### ISSUE TITLE
[Anon] Bug report: Imperium - Deathwatch.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6977] opened 2020-04-08 01:06 UTC
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.12

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Deathwatch Terminator w/ Heavy Weapon. When choosing cyclone missile launcher and storm bolter, maximum of storm bolter is 0. The maximum should be 1. If you can help, thanks!

**Comment by Mad-Spy** [comment] 2020-04-08 08:17
Duplicate of #6900

**Closed by Mad-Spy** 2020-04-08 08:17 UTC
Labels: Area: validation, Type: bug, 💾 Cat: Imperium - Deathwatch
