### ISSUE TITLE
Imperium - Space Marines: Validation error when giving Primaris Captain a power sword

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5565] opened 2019-08-27 17:44 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.01

**Platform:** Windows

**Dropbox:** Yes

**Description:** Select "Primaris Captain" as HQ selection for a Space Marine detachment. Equip him with power sword (first checkbox). 
Error will be "Primaris Captain has 1 too many selections of Power sword (maximum 0)"

The default model from GW has equiped bolter and power sword - this is not possible in the current data repository.

Data is Warhammer 40K 1.3.21 (26th of august)

**Comment by Mad-Spy** [comment] 2019-08-28 07:46
Unable to reproduce in Marines v115. This will be in the next release.

**Closed by Mad-Spy** 2019-08-28 07:46 UTC
Labels: Area: validation, Type: bug, ✔ Res: deprecated, 💾 Cat: Imperium - Space Marines
