### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Mechanicus.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7246] opened 2020-06-19 02:09 UTC
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** When attempting to create a Mechanicus list containing Serberys Sulphurhounds,  adding a phosphor blast carbine removes both of the model's sulphur blast pistols. The rules for this unit clearly state that each model has 2 phosphor pistols, and only one is lost when adding a blast carbine. This problem can easily be reproduced by adding a unit of sulphur hounds, and adding serberys sulphurhound (Carbine).

**Comment by Mad-Spy** [comment] 2020-06-19 06:05
Duplicate of #7217

**Closed by Mad-Spy** 2020-06-19 06:05 UTC
