### ISSUE TITLE
Imperium - Astra Militarum - Malcador Heavy Tank Autocannon Miscosted

### ISSUE THREAD

**Issue by plaguedroneofblight** [BSData/wh40k#3119] opened 2018-05-21 12:06 UTC
File: Imperium - Astra Militarum v114

Autocannons should cost 12 pts as per Chapter Approved 2017.

**Comment by plaguedroneofblight** [comment] 2018-05-23 14:49
The catalogue added by Mad+Spy is incorrect. This issue is for the mainline AM cataglogue.

**Comment by Mad-Spy** [comment] 2018-05-23 15:34
Oops, fixed.

**Comment by CrusherJoe** [comment] 2018-05-25 16:56
Dupe of #3120

**Comment by plaguedroneofblight** [comment] 2018-05-25 21:28
This is not a dupe of #3120. This one is a different catalogue, AND for a different weapon (autocannon vs battle cannon).

**Closed** 2018-05-25 23:31 UTC
Labels: Area: costs, Type: bug, 💾 Cat: Imperium - Astra Militarum

**Comment by CrusherJoe** [comment] 2018-05-25 23:33
Oh, man...perhaps I should learn to read.

Or, maybe, pay closer attention...

Regardless, I'll fix this right now.
