### ISSUE TITLE
Space Wolves: Wargear options needed for eliminators, phobos BL and infiltrators

### ISSUE THREAD

**Issue by knotdragon** [BSData/wh40k#5516] opened 2019-08-24 09:49 UTC
**File/Catalogue:** Space Wolves.catz

**BattleScribe version:** 2.03.00

**Platform:** Android

**Dropbox:** No

**Description:** 

- No weapon options for eliminators

- No weapon (and hence no Reiver) option for phobos battle leader

- Comms array not available for infiltrators, no way to field 10 men squad of same without taking helix adept

- No thunder hammer option for intercessor pack leader

**Comment by Mad-Spy** [comment] 2019-08-24 18:22
Duplicate of #5498

**Closed by Mad-Spy** 2019-08-24 18:22 UTC

**Comment by knotdragon** [comment] 2019-08-27 10:08
It's not a duplicate of that ticket - battle leader, infiltrator and intercessor issues aren't on #5498
