### ISSUE TITLE
Chaos - Chaos Space Marines - Missing Chapter Approved Changes

### ISSUE THREAD

**Issue by funguykharn** [BSData/wh40k#4159] opened 2018-12-16 17:31 UTC
**File/Catalogue:** Chaos - Chaos Space Marines.cat

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Two missed point changes:
Maulerfiends are 120pts (old 140)
Havoc Autocannons are 10pts (old 15)

**Comment by GenWilhelm** [comment] 2018-12-16 17:32
Duplicate of #4078

**Closed by GenWilhelm** 2018-12-16 17:32 UTC
