### ISSUE TITLE
[Anon] Bug report: Tyranids.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2579] opened 2018-03-02 21:16 UTC
**File:** Tyranids.catz

**BattleScribe version:** 2.01.09

**Platform:** Android

**Dropbox:** No

**Description:** Same as the windows version. The points cost is wrong for Genestealers in codex Tyranids. They are listed at 12 PPM when they should be 10.

**Comment by Mad-Spy** [comment] 2018-03-03 08:20
Duplicate of #2578.

**Closed by Mad-Spy** 2018-03-03 08:20 UTC
