### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4971] opened 2019-04-24 04:40 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.00

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When i try to create a new roster using the version 96 of the 40k 8th ed repository the only army offered for selection are renegade knights, i deleted and redownloaded the repository but it is still getting this issue, i wonder if it has to do with the update put out today
4/23/2019

**Comment by williamcaw** [comment] 2019-04-24 06:33
Just relax this is being looked at. Duplicate of #4959

**Closed** 2019-04-24 07:24 UTC
Labels: Area: BattleScribe app, Type: bug, ✔ Res: duplicate
