### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4969] opened 2019-04-23 22:23 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.01

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The only catalogue available is the chaos renegades roster

**Comment by DrTobogganMD** [comment] 2019-04-23 22:50
Duplicate of #4959

**Closed by DrTobogganMD** 2019-04-23 22:50 UTC
Labels: Area: BattleScribe app, Type: bug, ✔ Res: duplicate
