### ISSUE TITLE
[Anon] Bug report: Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4348] opened 2018-12-28 20:29 UTC
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** #4343 #4345 #4342

WindstormSCR is not allowing inspection of the information in to the interpretation of may @mad-spy
during the last edition with space marines may was prevalent used  possibility of weapons.
all models have control in the actions that that can take .
it is a rehash of what consts of a unit rehash of what is in side that is throwing off the user WindstormSCR describes at unit level.
                        v1
default choice  
                        v2
now where is the choice of keeping the default weapon for a model.

model of per bases of weapon choice 
                           v1
default, choice                      choosing to keep default weapon 
                          v2

**Comment by Kohato** [comment] 2018-12-28 20:50
Keep opening them, we'll keep closing them.

**Closed by Kohato** 2018-12-28 20:50 UTC

**Comment by Mad-Spy** [comment] 2018-12-28 23:43
I don't really know why I'm being appealed to. I am not the owner of the Space Marines catalogue, nor do I have any more authority than anyone else in the maintainer community.

I also disagree with your interpretation of this rule. The text for all Primaris units (Intercessors, Hellblasters, Reivers, Inceptors and Aggressors) all contain the text in the format "All models in the unit may...". This means that ALL models must do this, not some.

Units where individual models may take separate wargear options are denoted with "Any", see any type of Veteran, or vehicle squadron.

In addition, GW have _never_ shown a picture of a Primaris squad where models within the squad have different weapons (excluding where a Sergeant may take a slightly different loadout). In almost all other cases, GW clearly show mixed loadouts where applicable.

Until and unless GW issue a clarifying statement to say that these units may have mixed loadouts, I do not expect this to be changed.

**Comment by amis92** [comment] 2019-01-06 16:14
For clarity, as OP himself noted, it's a duplicate of #4342, duplicate of #4343, duplicate of #4345.

Games Workshop is quite consistent in their usage of various English rule wordings.

## Codex Space Marines (2017):

* Intercessor squad:
![image](https://user-images.githubusercontent.com/2671396/50738501-f43eb500-11d4-11e9-8fa7-b9a6f5a256dc.png)

* Scout Squad:
![image](https://user-images.githubusercontent.com/2671396/50738505-07ea1b80-11d5-11e9-80bf-8f6eebf33cef.png)

As you can see, if the option has
* model-level granularity (so in the same unit, one model may take it while the other doesn't), the wording is **Any model may …**
* unit-level granularity (so in the same unit, *either* all models *or* none take the option), the wording is **All models in the unit may ...**

Other examples both from this and previous edition:

## Codex T'au Empire (2018):

* Strike Team (Any model may):
![image](https://user-images.githubusercontent.com/2671396/50738533-526b9800-11d5-11e9-8efb-6496b3e5e258.png)

## Codex Space Marines (2013):

* Tactical Squad (just for OPs request):
![image](https://user-images.githubusercontent.com/2671396/50738546-7d55ec00-11d5-11e9-86a1-bbbfa3911dbc.png)

* Veteran Vanguard Squad (Any model may, The entire squad may):
![image](https://user-images.githubusercontent.com/2671396/50738549-88108100-11d5-11e9-9f75-b2f4923f4306.png)

**Comment by williamcaw** [comment] 2019-01-06 16:35
person is referring the ways of equipment from 7 ed and was notorious of using may in equipment selection and expatiation of a unit 8e uses can in expansion of unit size .

**Comment by amis92** [comment] 2019-01-06 16:40
@williamcaw I don't understand:
> 8e uses can in expansion of unit size
