### ISSUE TITLE
[Anon] Bug report: Chaos - Chaos Space Marines.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4848] opened 2019-04-02 19:01 UTC
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.17

**Platform:** Windows

**Dropbox:** Yes

**Description:** Havoc with Missile Launcher is missing the Missile Launcher weapon profile and point cost.

**Comment by GenWilhelm** [comment] 2019-04-02 19:04
Duplicate of #4841

**Closed by GenWilhelm** 2019-04-02 19:04 UTC
